### ISSUE TITLE
Is it possible to use WireMock as a proxy server for HTTPS requests?

### ISSUE THREAD

**Issue by robvangeloven** [WireMock-Net/WireMock.Net#1007]
So I have a use case where I'm stuck with a hardcoded URL embedded in an external SDK. There is no way for me to change that behaviour and I do need to verify the output somehow for my current use case.

I though to myself: what if I make WireMock the default proxy server? And that does work, but only for HTTP calls. HTTPS calls get a 
```
System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
    ---- System.Security.Authentication.AuthenticationException : Cannot determine the frame size or a corrupted frame was received.
```

However, if I remove the WireMock-as-proxy setting and make the call directly it works just fine. Only I have trouble figuring out why this is.

```csharp
var wireMockServer = WireMockServer.Start(new WireMockServerSettings
  {
      Urls = new[] { "http://localhost:9091", "https://localhost:9443" },
      UseSSL = true,
  });

  // If I remove the DefaultProxy setting everything works just fine
  HttpClient.DefaultProxy = new WebProxy
  {
      Address = new Uri(wireMockServer.Url!),
      BypassProxyOnLocal = false,
  };

  wireMockServer
      .Given(Request.Create())
      .RespondWith(
          Response.Create()
          .WithStatusCode(200)
          .WithBody(@"{ ""msg"": ""Hello world!"" }"));
 
  var result = await new HttpClient().PostAsync(wireMockServer.Urls[1], null);
```

**Comment by PG-RichT** [comment]
@robvangeloven I'd be interested to see a response to this as I find myself in the same position. This wouldn't happen to be the Adyen SDK by any chance?

**Comment by robvangeloven** [comment]
> @robvangeloven I'd be interested to see a response to this as I find myself in the same position. This wouldn't happen to be the Adyen SDK by any chance?

Buckaroo, so same difference really 😅

**Comment by StefH** [comment]
When calling the https endpoint from WireMock.Net via Postman (SSL certificate verification= true), does that work ?

And maybe these pages can help you?
- https://github.com/WireMock-Net/WireMock.Net/wiki/Using-HTTPS-%28SSL%29
- https://github.com/WireMock-Net/WireMock.Net/wiki/Settings#certificatesettings

**Comment by robvangeloven** [comment]
> When calling the https endpoint from WireMock.Net via Postman (SSL certificate verification= true), does that work ?
> 
> And maybe these pages can help you?
> 
> * https://github.com/WireMock-Net/WireMock.Net/wiki/Using-HTTPS-%28SSL%29
> * https://github.com/WireMock-Net/WireMock.Net/wiki/Settings#certificatesettings

I haven't tested it via Postman, mostly because the code works just fine if I don't point the default httpclient proxy to the WireMock instance. If WireMock is configured to be the default proxy though (no other changes). I get weird SSL errors. 

See also the code I linked: if I remove the 
```csharp
HttpClient.DefaultProxy = new WebProxy
  {
      Address = new Uri(wireMockServer.Url!),
      BypassProxyOnLocal = false,
  };
```

Everything works just fine. With it: SSL errors. HTTP calls work fine in both cases by the way.

**Comment by StefH** [comment]
@robvangeloven 
I'm able to reproduce your issue (https://github.com/WireMock-Net/WireMock.Net/pull/1010), however I do not have any idea on the root cause.

**Comment by StefH** [comment]
@robvangeloven  / @PG-RichT 

After some investigating I now understand what you are trying to to.

However, configuring WireMock.Net to act as a proxy-server is possible. For this purpose you should use a different solution / NuGet.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1010

**Comment by robvangeloven** [comment]
@PG-RichT / anyone reading  this: the [FryProxy](https://github.com/eger-geger/FryProxy ) or [BenderProxy](https://github.com/jimevans/BenderProxy) could help as a MITM proxy your solution
