### ISSUE TITLE
Readme: links to the specific request matches do not work

### ISSUE THREAD

**Issue by dmytro-pryvedeniuk** [WireMock-Net/WireMock.Net#1022]
### Describe the bug
When trying to open the link to the concrete request matcher here (https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matchers) I am redirected to _1️⃣ Request Matching_ page (not to the section with the matcher).

### Expected behavior:
Section with the selected matcher is shown

### Test to reproduce
- Open https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matchers
- Click on any matcher from the list
- Request matching page is shown, not the selected matcher

As a workaround I have to scroll down as the links don't work as expected.

**Comment by StefH** [comment]
@dmytro-pryvedeniuk 
Which matcher do you click in the list?
Because on firefox, the links seem to work fine?

**Comment by dmytro-pryvedeniuk** [comment]
UPD: GraphQLMatcher works. Maybe because it has the different link - https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching-GraphQLMatcher

**Comment by StefH** [comment]
@dmytro-pryvedeniuk 

Thanks.

Links have been fixed.
