### ISSUE TITLE
How to enable the Swagger UI

### ISSUE THREAD

**Issue by gaojianzhuang** [WireMock-Net/WireMock.Net#1027]
How to enable the Swagger UI?

Request the "/__admin/mappings" only display the json string, could we display the expected UI as blow?
For example: if we request "__admin/mappings/swagger/index.html"
![image](https://github.com/WireMock-Net/WireMock.Net/assets/1866009/802e9bb3-ffce-4d8b-bb14-608967e843c9)

Thank you so much.

**Comment by StefH** [comment]
@gaojianzhuang 
Sorry, this is not (yet) supported.
