### ISSUE TITLE
Support for Faults

### ISSUE THREAD

**Issue by MiguelAlho** [WireMock-Net/WireMock.Net#103]
Are there any plans for implementing the support for faulty responses, as in http://wiremock.org/docs/simulating-faults/ ?

**Comment by StefH** [comment]
Can you explain which part of the *faults* functionality you would like to see in this project ?

**Comment by MiguelAlho** [comment]
EMPTY_RESPONSE and MALFORMED_RESPONSE_CHUNK (at the end of the page) are currently interesting to me to create integratoon tests that verify a retry cycle. CONNECTION_RESET_BY_PEER also but that doesn't seem to be supported.

I'm also trying to figure out how to simulate a timeout...

**Comment by StefH** [comment]
1. EMPTY_RESPONSE - I'll take a look
2. MALFORMED_RESPONSE_CHUNK - I'll take a look
3. Timeout - Would this help you ? https://github.com/WireMock-Net/WireMock.Net/wiki/Stubbing-and-Request-Matching#simulating-delays

**Comment by MiguelAlho** [comment]
I've been trying delay (response an extra second more then the amount of time i have for HttpClient timeout), but my instance o HttpClient seems to be receiving a 504 response than actually throwing the exception it's known to throw. I might need o up on the time on the delay to account for other factors.

**Comment by StefH** [comment]
1. EMPTY_RESPONSE ; That's just returning an empty byte[] or string ? This is already supported I think?
2. MALFORMED_RESPONSE_CHUNK ; that's just returning a byte[] or random length / random data ?
3. I will take a look

**Comment by MiguelAlho** [comment]
(sorry for the delayed response). Yes, those seem to help. In the timeout case, I have figured out the problem to my approach, and fixed the setup. The delay setup on the mock server works correctly and is suficiente.
