### ISSUE TITLE
Reset resets only mappings and logentries, not scenarios.

### ISSUE THREAD

**Issue by MJLHThomassenHadrian** [WireMock-Net/WireMock.Net#1030]
### Describe the bug
Calling `WireMockServer.Reset()` only resets Mappings and LogEntries, not scenarios. Since there are 3 methods for resetting them all seeprately (`WireMockServer.ResetLogEntries()`, `WireMockServer.ResetMappings()` and `WireMockServer.ResetScenarios()`) i would expet `Reset()` to reset everything, not just 2 of the 3.

### Expected behavior:
Scenarios are also reset.

**Comment by StefH** [comment]
good point

**Comment by MJLHThomassenHadrian** [comment]
@StefH thanks!
