### ISSUE TITLE
Is it possible to use WireMock as a middleware?

### ISSUE THREAD

**Issue by adrianiftode** [WireMock-Net/WireMock.Net#1035]
Currently I see that I can use wiremock hosted in different forms, however what I would like to do is to have a path prefix and everything after that path to be handled by wiremock.

So something like

```
app.Use(async (context, next) =>
{
    if (context.Request.Path.StartsWith("wiremock"))
    {
        await UseWiremock()
        return;
    }

    await next(context);
});
```

I would like to deploy an arbitrary .NET Service, but still use wiremock at the port 80 and let it handle some prefixed requests.

**Comment by StefH** [comment]
@adrianiftode 
Sounds like an interesting idea.

I guess you are using a modern .NET version like 6 or higher?

There is already an internal class named `WireMockMiddleware` which I register in the AspNetCoreSelfHost.cs:
```
appBuilder.UseMiddleware<WireMockMiddleware>();
```

Maybe that can be used?

**Comment by adrianiftode** [comment]
Yes, but the reason for asking this is I would like to deploy it with the tested service.

 I have a service ServiceB that I would like to mock.
 Then I have the client service, ServiceA, that will do requests to ServiceB. ServiceB is an external (and expensive and legacy) service, and the only way to use it in test scenarios is to mock it.
 
 I want to configure WireMock inside ServiceA. So when ServiceA is started, the Mocked ServiceB is also started and ready to accept requests. The Mock should listen to any HTTP request to a path  that starts with `/service-b-mock`.
 
 I will give it a try to the WireMockMiddleware.
 
 To expand this, I would also like to deploy a WireMock image configured with different mocked services
 
 - appBuilder.UseMiddleware<WireMockMiddleware>("service-b")
 - appBuilder.UseMiddleware<WireMockMiddleware>("service-c");
 
 This image is then deployed and accessible from the Sandbox/Tests servers, and it has some kind of "mock isolation". So each path prefix has its own WireMock configuration.

**Comment by StefH** [comment]
A quick question:

Why not deploy 1 (or multiple) docker container(s) of WireMock.Net ?

**Comment by adrianiftode** [comment]
Even deploying it within a separated container, I was hoping to be a single one. I think I will go with this route anyway (multiple containers per mocked service)

**Comment by StefH** [comment]
Or use one container and register the mappings with a prefix in the path?

**Comment by matteus6007** [comment]
Why not just use wiremock as a docker container using docker compose, see https://github.com/matteus6007/MyDomain.Api.Template/blob/main/docker-compose.dev-env.yml#L58 as an example of setting this up, then add your mocks in the normal JSON format into the `__files` folder and change any paths in your config to `http://localhost:8081/api-name/` where `api-name` is a unique name for each API you want to mock. Doing it like this means you don't have to add anything specific to your code.

**Comment by matthewyost** [comment]
I actually built this as a combination of a .NET HostedService (for Wiremock Server) and a DelegatingHandler which checks the original request headers for something like "X-WireMockStatus" and then rerouted all HttpClient calls to WireMockServer.  This worked well to allow me to run this WireMockServer in all our lower environments for testing purposes.

**Comment by StefH** [comment]
@matteus6007 
Is it possible that you share this complete solution?

**Comment by matthewyost** [comment]
@StefH Let me see what I can do about sharing this with you all.

**Comment by Act0r** [comment]
I'm very interested in that question as well. I'm working in enviroment where every service must have a bunch of specific middlewares, i can't avoid it. So i have to add that middlewares to wiremock or wiremock middleware to my service. So if this is possible please provide some hint in either direction

**Comment by Act0r** [comment]
Thank you very much for the detailed example

**Comment by StefH** [comment]
@matteus6007 
This indeed looks like a workable solution.

Would it be an idea that I create an project+nuget for this? 
Like `WireMock.Net.Middleware` or `WireMock.Net.AspNetCore.Middleware` ?

**Comment by StefH** [comment]
@matteus6007 
I did try your solution, however it seems that the path defined in `WithPath` is not available, it returns a 404.

**Comment by StefH** [comment]
@matthewyost 
I did try your solution, however it seems that the path defined in WithPath is not available, it returns a 404.

**Comment by matthewyost** [comment]
@StefH The stuff between the < > is just supposed to be whatever path you want to use.  It's meant to be replaced with whatever path you're attempting to mock a response for.

**Comment by StefH** [comment]
> @StefH The stuff between the < > is just supposed to be whatever path you want to use. It's meant to be replaced with whatever path you're attempting to mock a response for.

About the "path" : I did chaage that. If you have time, please review my PR: https://github.com/WireMock-Net/WireMock.Net/pull/1175

**Comment by StefH** [comment]
@Act0r did you get it working?

**Comment by Act0r** [comment]
@StefH  Actually i posponed the idea and decide to implement requested features by myself.

**Comment by StefH** [comment]
@Act0r
@matteus6007 
@matthewyost 

I got it working. I was thinking in the wrong direction...

This solution actually translates any calls made from a WebApplication to another API (e.g. `https://real-api:12345/test1`) to a call to the running WireMock.Net instance (as background service) in the same WebApplication. This is done by changing the behavior from the **HttpClient** used in that WebApplication.

Example:
``` c#
app.MapGet("/weatherforecast", async (HttpClient client) =>
{
    // ⭐ This injected HttpClient will not call the real api, but will call WireMock.Net !
    var result = await client.GetStringAsync("https://real-api:12345/test1");

    return Enumerable.Range(1, 3).Select(index =>
        new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
            Random.Shared.Next(-20, 55),
            result
        ));
});
```

I'm not sure that is the same idea as @adrianiftode had?

My thoughts were initially that this WireMock.Net instance would be handling additional calls in a WebApplication.
- So `/weatherforecast` was handled by the WebApplication itself.
- And `/test` was handled by the WireMock.Net instance.

**Comment by StefH** [comment]
PR is merged.
