### ISSUE TITLE
WithoutHeader fluent assertion

### ISSUE THREAD

**Issue by jvmlet** [WireMock-Net/WireMock.Net#1048]
Please  support `WithoutHeader`  in `WireMockAssertions`
Thanks

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1049

**Comment by StefH** [comment]
@jvmlet 
Can you check the PR if this is what you need?

**Comment by StefH** [comment]
If you want, you can try preview version 1.5.46-ci-18207

**Comment by jvmlet** [comment]
>  Can you check the PR if this is what you need?

Thanks @StefH , would you please add `WihtoutHeader(string name)`, regardless the value ?

**Comment by StefH** [comment]
The problem is that I cannot keep that proposed method definition.
That because and becauseArgs will make the other existing WithoutHeader methods invalid.

So I can do:
``` c#
public AndConstraint<WireMockAssertions> WithoutHeader(string unexpectedKey, (string Text, object[] Args)? because = null)
```

or / and

``` c#
public AndConstraint<WireMockAssertions> WithoutHeaderKey(string unexpectedKey, string because = "", params object[] becauseArgs)
```

**Comment by jvmlet** [comment]
`WithoutHeaderKey` looks great, thanks a lot.
