### ISSUE TITLE
Issue: Params does not work, when there are multiple values for a key

### ISSUE THREAD

**Issue by raghavendrabankapur** [WireMock-Net/WireMock.Net#106]
For a request in the Param's, if we have multiple values for a key, we are not able to match the score for that request and return 410 saying could not find the mapping.

In a request for a query string parameter, we can have only one value. But in the structure, we are allowing an array of values that can be passed. That means for that key, it can be anything among the passed values.

example
``` json
  "Params": [
        {
          "Name": "searched",
          "Values": ["test","test2"]
        }
      ]
````

here in params, we have the key "searched" and values being "test" and "test2". Now my request can be like
http://localhost:9092/xyz?searched=test
http://localhost:9092/xyz?searched=test2

We can have either of them. But we cannot have like http://localhost:9092/xyz?searched=test1,test2

In this case, in the RequestMessageParamMatcher.cs file, we are deciding the score based on the count of values. Ideally, this should have been done if the list contains the requests param value.

**Comment by StefH** [comment]
Thanks for this report.

**Comment by StefH** [comment]
Will be fixed soon, please watch updates here + NuGet.

**Comment by raghavendrabankapur** [comment]
I have a fix for the same. I will create a pull request.

**Comment by StefH** [comment]
Already fixed, no need for PR.
