### ISSUE TITLE
Dynamic http status code?

### ISSUE THREAD

**Issue by eetawil** [WireMock-Net/WireMock.Net#1070]
Hi,
I have this mock setup like this and now I want to also make the status code dynamic (200 or 400) based on the request that I will parse in the "GenerateBody" method, how can I achieve that here?

``` c#
wireMockServer
                .Given(Request.Create().WithPath("/validatePDFA").UsingPost())
                .RespondWith(Response.Create()                   
                    .WithHeader("Content-Type", "application/json")
                    .WithBody(req => GenerateBody(req))
                    .WithStatusCode(??) 
                    // the "req" returned from the "GenerateBody" could contain the status, but how to retrieve it afterward?
                );
```

**Comment by StefH** [comment]
So you are looking for this code?

``` c#
.WithStatusCode(Func<IRequestMessage, int> statusCodeFactory) 
```

which can be used like:
``` c#
.WithStatusCode(req => GenerateStatus(req)) 
```

**Comment by eetawil** [comment]
Yes this could work , but I was wondering if there's a way to do it in a single shot?

```
 .WithBody(req => GenerateBody(req))
.WithStatusCode(??)  <== Use here the result from GenerateBody
```
Here when generating the body dynamically can it also set the status code without the need of reprocessing the request again? 

Or maybe the Obj returned by GenerateBody  => `Func<IRequestMessage, Obj> ` could be retrieved and reused in `.WithStatusCode` ???

**Comment by StefH** [comment]
In that case. You need "WithCallback".

**Comment by StefH** [comment]
In that case. You need "WithCallback".

**Comment by eetawil** [comment]
Thank you I didn't know about that, I'll look into that. Again, thank you for answering our questions and being available!
