### ISSUE TITLE
Support for multipart formdata in RequestMessage

### ISSUE THREAD

**Issue by chrischu** [WireMock-Net/WireMock.Net#1076]
**Is your feature request related to a problem? Please describe.**
As far as I can tell the `RequestMessage` only has good support for URL-encoded form data. 

**Describe the solution you'd like**
It would be cool if there was support for multipart form data as well (e.g. like `HttpRequest.Form` from .NET Core).

**Describe alternatives you've considered**
An alternative would be to implement the form parsing myself, which is something I'll do in the short term, but long term I would prefer if WireMock.Net had support for this pretty common content type (afaik it is still the default solution when doing large file uploads with accompanying other data).

**Comment by StefH** [comment]
@chrischu 
I think you can use https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching-MimePartMatcher for that.

**Comment by chrischu** [comment]
Interesting, but can I use these matchers to assert the requests that were sent?

**Comment by StefH** [comment]
@chrischu Does this answer your question?

**Comment by StefH** [comment]
I understand your points.

1. Correct, this should be added in more detail in the wiki.
2. The main reason that it's an `object?` is that the dependency on MimeKitLite is not for all frameworks. In the future I'll split the packages and projects (https://github.com/WireMock-Net/WireMock.Net/issues/1071)
