### ISSUE TITLE
Use mocked response data in Webhook body data

### ISSUE THREAD

**Issue by rmeshksar** [WireMock-Net/WireMock.Net#1081]
Hi,
Imagine a mocked API returns response from this template:

```json
{
   "id": "{{Random Type='Guid'}}",
   "name":  "John"
}
```

This mock API triggers a Webhook call with some delays.

Is it possible in the body data of the WebhookRequest, use the value of **id** of the response of the original call?

**Comment by StefH** [comment]
I think you can use:

request.bodyAsJson.id

See
https://github.com/WireMock-Net/WireMock.Net/wiki/Response-Templating#the-request-model

**Comment by rmeshksar** [comment]
Would that be request of the original call or response from the original call?
I am looking to use the response form the original call.

**Comment by rmeshksar** [comment]
This worked for me:
{{JsonPath.SelectToken response.bodydata.bodyAsString 'Id'}}
