### ISSUE TITLE
Regex support for JsonMatcher 

### ISSUE THREAD

**Issue by pluma9** [WireMock-Net/WireMock.Net#1088]
**Is your feature request related to a problem? Please describe.**
I'd like to use regex in JsonMatcher (just like in JsonPartialMatcher)

**Describe the solution you'd like**
Add the option to turn on regex. Similar to: https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching-JsonPartialMatcher#use-regex

**Describe alternatives you've considered**
No alternative solution I can think of

**Is your feature request supported by [WireMock (java version)](https://www.wiremock.org)? Please provide details.**
I am not sure. Please let know if this is important. I can do some more research.

**Additional context**
No.

**Comment by StefH** [comment]
@pluma9 
I'll see if this can be added easily.

Is there a reason you cannot use the JsonPartialMatcher ?

**Comment by pluma9** [comment]
Thanks. That is because I want to assert that the request contains exactly certain fields. Adding more fields may make the real API server returns an error.

**Comment by StefH** [comment]
I've added this logic, can you please test preview version `WireMock.Net.1.5.51-ci-18462`?

See https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by pluma9** [comment]
Thanks very much. It works great in terms of regex.

There seems to be a regression.
Given matcher:
```json
{
  "Contact": {
    "Phone": "1234",
    "Street": "King Street"
  },
  "Info": {
    "Occupation": "Developer"
  }
}
```

In previous versions, it does **not** match the following body:
```json
{
  "Contact": {
    "Phone": "1234",
    "Street": "King Street"
  },
  "Info": {
    "Occupation": "Developer"
  },
  "OtherInfo": {
    "NickName": "Jimmy"
  }
}
```

However, in WireMock.Net.1.5.51-ci-18462, it **does**

**Comment by StefH** [comment]
I see.
Thanks for this observation.

I need to adjust the logic to match exact. I'll check tomorrow.

**Comment by pluma9** [comment]
The previous case works great now.

However, there is one more case. Given the matcher above, the following body does not match (expected):
```json
{
  "Contact": {
    "Phone": "1234",
    "Street": "King Street"
  },
  "Info": {
    "Occupation": "Dancer"
  }
}
```

The following body oddly matches:

```json
{
  "Contact": {
    "Phone": "1234",
    "Street": "King Street"
  },
  "Info": {
    "Occupation": "Developer2"
  }
}
```
```

**Comment by StefH** [comment]
All strings should be defined as valid regular expressions.

So in this case like this:


`^Developer2$`

**Comment by pluma9** [comment]
Ah, I see. Then things great work now.

I really appreciate your support.

**Comment by StefH** [comment]
I'll merge the PR and create a new normal NuGet soon.
