### ISSUE TITLE
FindLogEntries present in WireMockServer but not IWireMockServer

### ISSUE THREAD

**Issue by AHarman** [WireMock-Net/WireMock.Net#1092]
Hello, when trying to write some extension methods I noticed that FindLogEntries is defined on WireMockServer but not the IWireMockServer interface, having taken a look at the source I can see that it _is_ present in IWiremockServer but it's been commented out.

Is there any intention to add this method to the interface?

**Comment by StefH** [comment]
@AHarman 
I can't remember anymore why this is not yet implemented, probably a good reason I think. I'll take a look.

**Comment by StefH** [comment]
This is now added.


https://github.com/WireMock-Net/WireMock.Net/pull/1224
