### ISSUE TITLE
WireMock standalone and Linqpad

### ISSUE THREAD

**Issue by asherber** [WireMock-Net/WireMock.Net#1102]
Has anyone had success running WireMock as a standalone process in Linqpad?

I'm using Linqpad 7 with .net 7, and `StandAloneApp.Start(args);` gives me:

```
FileNotFoundException: Could not load file or assembly
'Microsoft.Extensions.DependencyInjection.Abstractions, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

I've tried playing with the "Copy all assemblies into local output folder" and "Use a non-collectible load context" settings, since those sometimes clear up issues, but no luck.

**Comment by StefH** [comment]
I can also confirm that for LINQPad 6, the same issue. I'm not sure yet if this is an issue for WireMock for for LINQPad.

**Comment by asherber** [comment]
**Solution:** In the Linqpad Query Properties window (F4), you need to check "Reference ASP.NET Core".

![image](https://github.com/WireMock-Net/WireMock.Net/assets/5248041/6f8606dd-5c58-4b18-a5a0-c5fdf4eb0087)

Maybe add a note about this to the [docs](https://github.com/WireMock-Net/WireMock.Net/wiki/WireMock-as-a-standalone-process)?
