### ISSUE TITLE
Master branch doesn't build

### ISSUE THREAD

**Issue by asherber** [WireMock-Net/WireMock.Net#1103]
I'm trying to build the master branch of the solution on Windows 11/VS2022, and I'm getting these errors:

![image](https://github.com/WireMock-Net/WireMock.Net/assets/5248041/fc189dec-a4fe-4bb2-bfb1-5507db7f046c)

Is this expected?

**Comment by StefH** [comment]
Ah I see, It seems that some old examples need some NuGet updates. I'll take a look.
