### ISSUE TITLE
Docs: Documentation is misleading/incomplete for BodyAsFile

### ISSUE THREAD

**Issue by dotnetprofessional** [WireMock-Net/WireMock.Net#1106]
### Describe the bug
The sample code at:

https://github.com/WireMock-Net/WireMock.Net/wiki/Response-Templating#mapping-json-example-using-handlebarsnet

Is incomplete which leads to a very frustrating experience. Tried for an hour or two to get transformers working until I found the following issue:

https://github.com/WireMock-Net/WireMock.Net/issues/386

The docs need to be updated to include that we also need to have the following property for this to work (btw why introduce another property?):

"UseTransformerForBodyAsFile": true

I did notice (now I know what to look for), a reference at:

[UseTransformerForBodyAsFile](https://github.com/WireMock-Net/WireMock.Net/wiki/Response-Templating#transform-the-content-from-a-referenced-file)

However, that should be a little clearer too, as it doesn't call out its to be included in the response.json file.

### Expected behavior:
Docs provide clear and working example, which they don't.

**Comment by StefH** [comment]
documentation has been updated
