### ISSUE TITLE
WireMock.Net.Client Request Builder Matchers

### ISSUE THREAD

**Issue by hmiguel** [WireMock-Net/WireMock.Net#1115]
Hello,

I'm trying to replicate the following server mapping using wiremock.net rest client.

```c#
var server = WireMockServer.Start();
server.Given(WireMock.RequestBuilders.Request.Create()
    .WithPath("/test1")
    .UsingPost()
    .WithBody(new JmesPathMatcher("things.name == 'RequiredThing'")))
    .RespondWith(
           WireMock.ResponseBuilders.Response.Create()
           .WithHeader("Content-Type", "application/json")
           .WithStatusCode(200)
           .WithDelay(TimeSpan.FromMilliseconds(50))
    );
```

Right now, I successfully made it using @R0boC0p extension from [here](https://github.com/WireMock-Net/WireMock.Net/issues/886#issue-1587423344). It look like this:

```c#

var api = RestClient.For<IWireMockAdminApi>("http://localhost:2080");
var builder = api.MappingBuilder();
builder.Given(WireMock.RequestBuilders.Request.Create()
        .WithPath("/test1")
        .UsingPost()
        .WithBody(new JmesPathMatcher("things.name == 'RequiredThing'")))
        .RespondWith(
            WireMock.ResponseBuilders.Response.Create()
           .WithHeader("Content-Type", "application/json")
           .WithStatusCode(200)
           .WithDelay(TimeSpan.FromMilliseconds(50))
    );
await builder.BuildAndSendAsync();

```

My question is: is there any built-in way to do it?

**Comment by R0boC0p** [comment]
I am not sure if I can follow correctly, but if you are intending to have a builder for the admin-interface, this has been added by the link you posted, and there is no extension code (the one that I proposed) needed, as it's now working out of the box.

What is your exact issue, as your code seems to be just fine?

from what I can see the only difference here is that the example code has
```c#
   var result = await mappingBuilder.BuildAndPostAsync().ConfigureAwait(false);
```

Cheers.

**Comment by hmiguel** [comment]
My issue is that you don't have an ```api.MappingBuilder()```, only a ```api.GetMappingBuilder()```;

And then, ```api.GetMappingBuilder()``` doesn't have the same syntax, neither access to ```WithBody(IMatcher matcher)```, i.e..

Best

**Comment by StefH** [comment]
For an example on the mapping builder: see https://github.com/WireMock-Net/WireMock.Net/blob/master/examples/WireMock.Net.Client/Program.cs#L22

**Comment by hmiguel** [comment]
@StefH I can't see any example with body using matchers, only strings, i.e. ```.WithBody(new JmesPathMatcher("things.name == 'RequiredThing'")))```.

**Comment by StefH** [comment]
Correct, the JmesPathMatcher (from the server project) is not available if you use the **client** builder.

If you only have use client-side, you need code like this:


``` c#
mappingBuilder.Given(m => m
            .WithRequest(req => req
                .WithPath("/test1")
                .UsingPost()
                .WithBody(b => b
                    .WithMatcher(match => match
                        .WithName("JmesPathMatcher")
                        .WithPattern("things.name == 'RequiredThing'")
                    )
                )
            )
            .WithResponse(rsp => rsp
                .WithHeaders(h => h.Add("Content-Type", "application/json"))
                .WithDelay(TimeSpan.FromMilliseconds(50))
                .WithStatusCode(200)
                .WithBodyAsJson(new
                {
                    status = "ok"
                }, true)
            )
        );
```

**Comment by hmiguel** [comment]
If so, I prefer to use @R0boC0p extension. Thanks

**Comment by StefH** [comment]
As stated by @R0boC0p, that extension is not available. The only code which is available on the **client** is the code I posted.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1116
