### ISSUE TITLE
AbstractJsonPartialMatcher: Regex Value is Uppercased when IgnoreCase is set to true

### ISSUE THREAD

**Issue by epDugas** [WireMock-Net/WireMock.Net#1117]
### Describe the bug
AbstractJsonPartialMatcher
When IgnoreCase is true, and Regex is true, the value used as a regex is upper-cased.
This changes a given regex and causes a non-match. Example:
"^\d+$" is changed to "^\D+$"

### Expected behavior:
Expect the given regex to be used.

### Test to reproduce
- Create a request mapping, with Regex = true and IgnoreCase = true
- Define json object with regex: { "x" : "^\\d+$" }

### Other related info
Test to Demonstrate:
```csharp
[Fact]
public void JsonPartialWildcardMatcher_IsMatch_WithIgnoreCaseTrueAndRegexTrue_JObject()
{
    // Assign 
    var matcher = new JsonPartialWildcardMatcher(new { id = 1, Number = "^\\d+$" }, true, true);

    // Act 
    var jObject = new JObject
    {
        { "Id", new JValue(1) },
        { "Number", new JValue(1) }
    };
    double match = matcher.IsMatch(jObject).Score;

    // Assert 
    Assert.Equal(1.0, match);
}
```

**Comment by StefH** [comment]
@epDugas Thanks for this finding.

A fix will be released shortly.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/commit/86f8877039d89674f4191f40b2d85320398167d1
