### ISSUE TITLE
Generating mappings from Payroc open-api file gives ArgumentException: Property with the same name already exists on object

### ISSUE THREAD

**Issue by Cherepoc** [WireMock-Net/WireMock.Net#1118]
Hi!
I'm trying to use WireMock for testing my Payroc integration. There's an open-api file I thought I could use to generate the client mock, but when I use WithMappingFromOpenApiFile method, it gives me the following error:
```
Unhandled exception. System.ArgumentException: Can not add property orderId to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
```
I used several tools to generate the C# client classes from the very same open-api file, and all of them succeeded and did not have any critical errors.
[The open-api file](https://raw.githubusercontent.com/payroc/api-specs/main/payroc-openapi-spec.yaml)
[Example on dotnet fiddle](https://dotnetfiddle.net/evvKwS)
Hope this can be fixed. Thanks!

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1122

**Comment by StefH** [comment]
@Cherepoc 

Can you try preview version `1.5.58-ci-18736`?

See
https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by StefH** [comment]
@Cherepoc did you have time to test this version?

**Comment by StefH** [comment]
@Cherepoc did you have time to test this version?

**Comment by Cherepoc** [comment]
@StefH Thanks! I'll test it in a few days.

**Comment by Cherepoc** [comment]
@StefH The error is still there

**Comment by StefH** [comment]
I will create a new preview version tomorrow.

**Comment by StefH** [comment]
@Cherepoc 
Can you try preview 1.5.60-ci-18958?

**Comment by Cherepoc** [comment]
@StefH Just tried it and now it works. Thanks!

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1122
