### ISSUE TITLE
How do I access admin endpoints if WireMock.Net is hosted behind AWS application load balancer?

### ISSUE THREAD

**Issue by rui-ktei** [WireMock-Net/WireMock.Net#1129]
Hello,
Right now, all the admin paths are hardcoded as `/__admin/*`. But if I host this server behind AWS ALB, when I set up a listener rule, I usually specify a route prefix so that the ALB knows how to distribute traffic to the correct container. In that case, the requests coming through will all carry route prefix, say, `/myprefix`, and then the built-in admin endpoints will not work because `/myprefix/admin/*` does not exist.

Here is the code I found where admin paths are hardcoded: https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Server/WireMockServer.Admin.cs

Could you tell me if what I understand so far is correct and if so, will there be any solution to it?

Thank you!

**Comment by StefH** [comment]
@rui-ktei 
The solution would be to replace the hardcoded admin paths with configurable admin paths. I need to look into that.

**Comment by rui-ktei** [comment]
> @rui-ktei Your understanding is correct. The solution would be to replace the hardcoded admin paths with configurable admin paths. I need to look into that.

@StefH Thank you for looking into that! Do you have a roadmap such as when you think it could be supported in the next release? The reason I'm asking is because I'm struggling to decide whether I should wait for the offical fix or fork this repository.

**Comment by luap-podium** [comment]
> Hello, Right now, all the admin paths are hardcoded as `/__admin/*`. But if I host this server behind AWS ALB, when I set up a listener rule, I usually specify a route prefix so that the ALB knows how to distribute traffic to the correct container. In that case, the requests coming through will all carry route prefix, say, `/myprefix`, and then the built-in admin endpoints will not work because `/myprefix/admin/*` does not exist.
> 
> Here is the code I found where admin paths are hardcoded: https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Server/WireMockServer.Admin.cs
> 
> Could you tell me if what I understand so far is correct and if so, will there be any solution to it?
> 
> Thank you!

@rui-ktei I just came across the same problem today but in my case GCP LB.  I was able to add a `rewriteTarget: "/"` to the ingress spec so the service path is matched then replaced with the slash when forwarded on.  

I'm not sure if this is supported in AWS ALB these days (or something similar) but thought I'd mention if useful.

**Comment by StefH** [comment]
> @StefH Thank you for looking into that! Do you have a roadmap such as when you think it could be supported in the next release? The reason I'm asking is because I'm struggling to decide whether I should wait for the offical fix or fork this repository.

I'll try to make a fix.

Do you use a Docker image? Or run WireMock.Net as a service / webapp?

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1130

**Comment by StefH** [comment]
@rui-ktei 
A PR is in progress, you can take a look if you want.

And I guess you will also need a new Docker image version?

**Comment by rui-ktei** [comment]
> @rui-ktei 
> A PR is in progress, you can take a look if you want.
> 
> And I guess you will also need a new Docker image version?

@StefH Thank you so much! I use the standalone version to build my own docker image so technically I won't use the official docker image.

**Comment by rui-ktei** [comment]
@luap-podium Thank you for your comment. Unfortunately as far as I know, AWS ALB doesn't have the same feature as GCP, which seems to be a way smarter LB. But anyways, the author is very kind to open a PR to implement my feature request. I guess I'll just wait until that PR is merged.

**Comment by StefH** [comment]
If you use the standalone NuGet, you can try preview `1.5.59-ci-18863` (see https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions)

**Comment by rui-ktei** [comment]
> @rui-ktei 
> Were you able to test this?

Hi, I did download the preview package and it worked fine for me. I'm just waiting for the official release now 🙂

**Comment by StefH** [comment]
Good to hear.
New version will be released this afternoon.
