### ISSUE TITLE
Allow WithMappings to support scanning SubDirectories when building a WireMockContainer

### ISSUE THREAD

**Issue by Xor-el** [WireMock-Net/WireMock.Net#1139]
First of all, I must thank you for this amazing project.
Now to my question, when using static mappings, is there an overload that allows us indicate that we want to include sub directories in our scan?
please see the code below for an example of what I mean.

```csharp   
   private const string PATH_TO_MAPPINGS = @"my/path/toMappings";

    private readonly WireMockContainer _api = new WireMockContainerBuilder()
        .WithAutoRemove(autoRemove: true)
        .WithMappings(PATH_TO_MAPPINGS, includeSubDirectories: true) // additional flag
        .WithCleanUp(cleanUp: true)
        .Build();
        
    public async Task StartAsync() => await _api.StartAsync();
```
If such functionality does not exist, I think it would be nice to have.

**Comment by StefH** [comment]
@Xor-el 
It's not yet supported I think using this command.
However you maybe can use this for now:
```c#
. WithWatchStaticMappings(true)
```

**Comment by Xor-el** [comment]
Thanks for the quick response @StefH 
Can confirm that your suggested approach works.
will use the workaround for now, very much appreciated.

maybe we can leave this issue open for now as a reminder if you plan to implement it later.

**Comment by StefH** [comment]
Will be solved in next release.

https://github.com/WireMock-Net/WireMock.Net/pull/1141

**Comment by Xor-el** [comment]
Thanks for your quick action @StefH
