### ISSUE TITLE
Ability To Pin WireMock.NET Test Container To A Particular Version Of WireMock.NET

### ISSUE THREAD

**Issue by Xor-el** [WireMock-Net/WireMock.Net#1150]
**Is your feature request related to a problem? Please describe.**

As of today, it is not possible to anchor a WireMock.NET test container to a specific version of WireMock, unlike other test containers such as Redis and SQL Server that offer this capability. Recently, the SQL Server Docker Image incorporated a [breaking change](https://github.com/microsoft/mssql-docker/issues/892), [which subsequently disrupted](https://github.com/testcontainers/testcontainers-dotnet/issues/1220) SQL Server test containers in numerous CI/CD pipelines where the image was not pinned to a fixed version. Fortunately, these containers permit version pinning, thereby providing a provisional solution for development teams while the underlying issue is addressed.

Furthermore, it is deemed [best practice](https://dotnet.testcontainers.org/api/best_practices/) by the test container team to consistently pin the image to a specific version.

**Describe the solution you'd like**
Having the ability to pin the needed WireMock.NET version when building a WireMock.NET test container would be a welcome development.

**Describe alternatives you've considered**
N/A

**Is your feature request supported by [WireMock (java version)](https://www.wiremock.org)? Please provide details.**
Provide relevant information if requested feature is supported in [Handlebarsjs](https://handlebarsjs.com/) but is missing in our implementation.
N/A

**Additional context**
N/A

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1181

**Comment by StefH** [comment]
@Xor-el 
This is already possible.

By default you would use this code:
``` c#
var container = new WireMockContainerBuilder()
            .WithAdminUserNameAndPassword("x", "y")
            .WithAutoRemove(true)
            .WithCleanUp(true)
            .Build();
```

And in case you want to use a different version, use:
``` c#
var container = new WireMockContainerBuilder()
            .WithImage("sheyenrath/wiremock.net-alpine:1.6.4")
            .WithAdminUserNameAndPassword("x", "y")
            .WithAutoRemove(true)
            .WithCleanUp(true)
            .Build();
```

**Comment by Xor-el** [comment]
Hello @StefH thanks for the sample.
very much appreciated.

**Comment by StefH** [comment]
If you have time, can you also take a quick look  at the PR https://github.com/WireMock-Net/WireMock.Net/pull/1181

If it's correct, I'll merge this PR to master.

**Comment by Xor-el** [comment]
PR looks good to me. I just added one minor comment, please take a look at it.

**Comment by Xor-el** [comment]
> > PR looks good to me. I just added one minor comment, please take a look at it.
> 
> I cannot see your comment? Did you save it?

apologies, submitted now
