### ISSUE TITLE
MappingsToCSharpCode should use RegexMatcher when specified

### ISSUE THREAD

**Issue by carlin-q-scott** [WireMock-Net/WireMock.Net#1151]
**Is your feature request related to a problem? Please describe.**
I used the MappingsToCSharpCode on the WiremockServer class to get C# mappings for my json mocks and it did not respect the matchers. It assumed everything was an exact match.

My json defined mock:
```json
{
  "Request": {
    "Methods": [
      "POST"
    ],
    "Path": "/auth",
    "Params": [
      {
        "Name": "clientId",
        "Matchers": [
          {
            "Name": "RegexMatcher",
            "Pattern": "^scenario_(.+)$"
          }
        ]
      }
    ]
  }
}
```

The resulting CSharpCode:
```c#
builder
    .Given(Request.Create()
        .UsingMethod("POST")
        .WithPath("/auth")
        .WithParam("clientId", $"^scenario_(.+)$")
    )
```

**Describe the solution you'd like**
If the Matcher.Name is RegexMatcher, then create a RegexMatcher instead of directly passing the pattern to the RequestBuilder method.

```c#
builder
    .Given(Request.Create()
        .UsingMethod("POST")
        .WithPath("/auth")
        .WithParam("clientId", new RegexMatcher($"^scenario_(.+)$"))
    )
```

**Describe alternatives you've considered**
Manually fixing the generated code.

**Is your feature request supported by [WireMock (java version)](https://www.wiremock.org)? Please provide details.**
I don't think this relevant.

**Additional context**

**Comment by StefH** [comment]
@carlin-q-scott 
This is indeed invalid. 
(ExactMatcher and LinqMatcher are also not correctly transformed)

However fixing this needs a complete rewrite from the generating logic...
(Currently the logic is defined in 1 class, but the knowledge about the parameters should be moved to the matcher itself...)

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1152
