### ISSUE TITLE
Listen on all ips

### ISSUE THREAD

**Issue by cocoon** [WireMock-Net/WireMock.Net#1154]
I ask this as question, maybe I missed something obvious.

When I want to listen to all public IPs I thought I could use http://0.0.0.0 as URL, but it was not working.
So I had to get all my current IPs and add them as List.

And when I check this line of code:

https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Owin/AspNetCoreSelfHost.NETStandard.cs#L79

it looks like it should use "ListenAnyIP" but instead it is listed in "ListenLocalhost"?

**Comment by StefH** [comment]
I need to double check that.

BTW what .NET version are you using?

**Comment by cocoon** [comment]
I usually use .net 8 now.

**Comment by cocoon** [comment]
I tried it and moved the host check for 0.0.0.0 at top and return it as ListenAnyIP and it works:

``` 
if (urlDetail is { Port: > 0, Host: "0.0.0.0" })
 {
     kestrelOptions.ListenAnyIP(urlDetail.Port, configure);
     return;
 }
```

```
var Settings = new WireMock.Settings.WireMockServerSettings
{
    Urls = new string[] { "http://0.0.0.0:80" },
    AllowPartialMapping = true,
    StartAdminInterface = true,
};

var server = WireMockServer.Start(Settings);
```


![WireMock NET-0 0 0 0](https://github.com/user-attachments/assets/3aba5700-b473-4936-81cb-5d469e3ec393)

**Comment by StefH** [comment]
Looks good.

Can you make a PR and if possible add/update a unit test?

**Comment by cocoon** [comment]
PR created and tried to add a test.
