### ISSUE TITLE
Question: What's guideline to be project contributor

### ISSUE THREAD

**Issue by evanlwj** [WireMock-Net/WireMock.Net#116]
Hello project owner
I'm using WireMock in unit test within my internal project, and want to contribute to get it improved, change is ready in my local branch, tried to push the branch but failed with following error

fatal: could not read Username for 'https://github.com': terminal prompts disabled
Pushing to https://github.com/WireMock-Net/WireMock.Net.git

What's guideline for contributing?

Thanks
Evan

**Comment by evanlwj** [comment]
I have figured out the contributor workflow at here https://github.com/CoolProp/CoolProp/wiki/Contributing:-git-development-workflow.

The error is resolved by using GitHub desktop client rather than Visual Studio 2017 with GitHub extension installed

**Comment by StefH** [comment]
Normally I use GitKraken.

BTW that's a nice workflow page, maybe I'll copy this also to my wiki.

**Comment by evanlwj** [comment]
Thanks recommendation of GitKraken, I just installed and it looked good

**Comment by StefH** [comment]
closing...
