### ISSUE TITLE
WireMock.NET TestContainer Dependency Constraint Issue

### ISSUE THREAD

**Issue by Xor-el** [WireMock-Net/WireMock.Net#1176]
### Describe the bug
[WireMock.Net.Testcontainers 1.6.3](https://www.nuget.org/packages/WireMock.Net.Testcontainers) has a hard version dependency constraint on [TestContainer 3.9.0](https://www.nuget.org/packages/Testcontainers/3.9.0) making it difficult to update both TestContainer and WireMock.Net.Testcontainers to their latest version in a project that uses both.

### Expected behavior:
I should be able to update the packages to their latest versions without issues.

### Test to reproduce
try updating the nuget packages in the project below to their latest versions

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="Testcontainers" Version="3.10.0" />-->
    <PackageReference Include="Testcontainers.MsSql" Version="3.9.0" />
    <PackageReference Include="WireMock.Net.Testcontainers" Version="1.5.62" />
  </ItemGroup>

</Project>
```

### Other related info
referencing the latest TestContainer nuget package (3.10.0 at this time) directly in our project works albeit with some warnings.
unfortunately, this doesn't work for us as we have a strict policy where we treat Warnings as Errors.

**Comment by StefH** [comment]
@Xor-el 
I'll check if I can remove the hard dependency on the version from TestContainer.

**Comment by Xor-el** [comment]
Thanks, @StefH very much appreciated.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1177
