### ISSUE TITLE
Incompatibility with TestContainers 3.10

### ISSUE THREAD

**Issue by marcinjahn** [WireMock-Net/WireMock.Net#1180]
I'm using a few TestContainer-based dependencies, TestContainers.WireMock is one of them. Recently, other TestContainer-based packages got updated to 3.10.0. After updating those, my project no longer builds due to WireMock requiring the 3.9.0 version of TestContainers.

> error NU1107: MyProject -> WireMock.Net.Testcontainers 1.6.3 -> Testcontainers (= 3.9.0)

**Comment by StefH** [comment]
Hello @marcinjahn 

This was already fixed in https://github.com/WireMock-Net/WireMock.Net/issues/1176, however I need to create a new version.
