### ISSUE TITLE
.WithBodyFromFile() + .WithTransformer(transformContentFromBodyAsFile: true) = empty string

### ISSUE THREAD

**Issue by vitalyve** [WireMock-Net/WireMock.Net#1184]
### Describe the bug
When .WithBodyFromFile(responseFilePath) is used in combination with .WithTransformer(transformContentFromBodyAsFile: true) the server returns empty string.

### Expected behavior:
The server should return transformed contents of the file.

### Test to reproduce
I've created a project with tests to demonstrate the problem. Please look at it.
https://github.com/vitalyve/WireMockNetBodyFromFileWithTransformerBug

**Comment by vitalyve** [comment]
Hi.
After some debugging of the WireMock.Net I've found that .WithTransformer(transformContentFromBodyAsFile: true) should be placed before .WithBodyFromFile() to be able to work as expected, but in examples form the [Wiki](https://github.com/WireMock-Net/WireMock.Net/wiki/Response-Templating) it is placed after .WithBodyFromFile().
So, just need to update the article and the issue may be closed.
Anyway. thank you for the great project!

**Comment by StefH** [comment]
Yes. I just made a branch with your testcase.

And indeed the order is important. However from a user perspective it should always work.

I will check if I can update the code.

**Comment by StefH** [comment]
Changing the internal logic is some work.

Adding a check and throw exception is better for now.

See PR:
https://github.com/WireMock-Net/WireMock.Net/pull/1185

**Comment by vitalyve** [comment]
Thank you!
