### ISSUE TITLE
WithMappings path is null on Build() call

### ISSUE THREAD

**Issue by mantasburokas** [WireMock-Net/WireMock.Net#1186]
### Describe the bug
After upgrading to 1.6.5 WithMappings no longer works because on Build() call the _staticMappingsPath is null.

### Expected behavior:
_staticMappingsPath is not null on Build() call

### Test to reproduce
        var wireMock = new WireMockContainerBuilder()
            .WithMappings($"{AppDomain.CurrentDomain.BaseDirectory}")
            .WithPortBinding(5000, 80)
            .Build();

**Comment by StefH** [comment]
Hello @mantasburokas, thank you for noticing this bug. I'll to fix it.
