### ISSUE TITLE
JsonPathMatcher - not matching? Correct syntax?

### ISSUE THREAD

**Issue by rangerranger** [WireMock-Net/WireMock.Net#120]
Hi - I'm not having my json match with the JsonPathMatcher. For example, I use:
``` c#
Request.Create().WithPath("/api/beta03").UsingPost()
    .WithBody(new JsonPathMatcher("{Scope:[{Sources:[{Shard:\"beta03\"}]}]}"))
```
But it never matches that request. Does the "pattern" to JsonPathMatcher have to be in a specific syntax? 
I ended up adding a JsonExactMatcher (that just matches json exactly), since the JsonPathMatcher wasn't working for me. Could you suggest if something is wrong with the above code?

**Comment by kwucode** [comment]
Please see [JSONPath syntax](http://goessner.net/articles/JsonPath).

**Comment by rangerranger** [comment]
Thanks Kevin. I guess in terms of json path syntax i need “$..*” - to match all members of my json exactly?
How would i create the request object in the above code?

**Comment by StefH** [comment]
The latest version from WireMock does now also support using a normal WildcardMatcher if you want to match a json message.

So this code should also work like this example:
``` c#
Request.Create().WithPath("/api/beta03").UsingPost()
    .WithBody("*beta03*"))
```

**Comment by StefH** [comment]
A new `JsonMatcher` has been added in latest version which enables you to match a json object 1:1.

See also https://github.com/WireMock-Net/WireMock.Net/issues/154

Closing this issue now...
