### ISSUE TITLE
Mapping file parse errors are not logged to the console

### ISSUE THREAD

**Issue by mikekberg** [WireMock-Net/WireMock.Net#1201]
**Is your feature request related to a problem? Please describe.**
When there is an issue loading a mapping file Wiremock.net only logs a `Static MappingFile : '/app/__admin/mappings/test.json' could not be read. This file will be skipped.`. This doesn't help understand why this is the cause or what is wrong with the syntax of the mapping file

**Describe the solution you'd like**
Detailed information about why the mapping file could not be loaded

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1202
