### ISSUE TITLE
ISO8601 Date response 

### ISSUE THREAD

**Issue by tyurtyubek** [WireMock-Net/WireMock.Net#1203]
How to return ISO8601 Date from __admin/mappings with Z in the end like
`"signed_at": "2024-10-29T08:40:18.510383Z"`
always got in such format
`"2024-10-29T21:51:06+02:00"`

**Comment by StefH** [comment]
Please provide your full code or json mapping.

**Comment by StefH** [comment]
Just use `"yyyy-MM-ddTHH:mm:ss.fffffffZ"` as custom formatter.

Like:

``` json
"signed_at": "{{Format signed_at \"yyyy-MM-ddTHH:mm:ss.fffffffZ\"}}"

```

**Comment by tyurtyubek** [comment]
Thank you! I tried to follow a similar approach. I’m attaching some code as an example.
`{
  "Request": {
    "Path": {
      "Matchers": [
        {
          "Name": "RegexMatcher",
          "Pattern": "/api/test",
          "IgnoreCase": true
        }
      ]
    },
    "Methods": [
      "POST"
    ]
  },
  "Response": {
    "StatusCode": 200,
    "BodyAsJson": {
      "data": {
        "eta": "{{DateTime.UtcNow}}",
        "signed_at": "{{String.Format (DateTime.UtcNow) \"yyyy-MM-ddTHH:mm:ss.fffffZ\"}}",
        "signed_at2": "{{String.Format (DateTime.UtcNow) \"yyyy-MM-ddTHH:mm:ss.fffffffZ\"}}",
        "signed_atZExample": "{{String.Format (DateTime.UtcNow) \"yyyy-MM-ddTHH:mm:ss.fffffffZ\"}}Z"
      }
    },
    "UseTransformer": true,
    "UseTransformerForBodyAsFile": true,
    "Headers": {
      "Content-Type": "application/json"
    }
  }
}`

and the results is 
`{
    "data": {
        "eta": "2024-11-02T15:12:15.802873+02:00",
        "signed_at": "2024-11-02T15:12:15.80502+02:00",
        "signed_at2": "2024-11-02T15:12:15.806856+02:00",
        "signed_atZExample": "2024-11-02T13:12:15.8086470ZZ"
    }
}`
