### ISSUE TITLE
Supplying Values From Request for Webhook Body and Headers

### ISSUE THREAD

**Issue by mathgr22** [WireMock-Net/WireMock.Net#1204]
**Is your feature request related to a problem? Please describe.**
I need the ability to digitally sign a Webhook due to interaction with third-party software. My digital signature needs to be based off of the post-transformed Webhook body. Currently it is not possible to insert a header after the Webhook body has been transformed.

**Describe the solution you'd like**
I would like the ability to generate an HMAC digital signature based off of the transformed Webhook body and insert it into the Webhook header before it is sent.

**Describe alternatives you've considered**
As far as I know there is no work-around to obtain this functionality in WireMock.Net.

**Comment by StefH** [comment]
https://github.com/orgs/WireMock-Net/discussions/1195

**Comment by StefH** [comment]
@mathgr22 
did you check my last comment on the discussion? https://github.com/orgs/WireMock-Net/discussions/1195

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1223
