### ISSUE TITLE
JsonPartialMatcher fails to match on property name that JsonMatcher matches

### ISSUE THREAD

**Issue by epDugas** [WireMock-Net/WireMock.Net#1210]
### Describe the bug
JsonPartialMatcher fails to match when the json object contains a property name with value: `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User`

### Expected behavior:
The same json object that matches with JsonMatcher would match with JsonPartialMatcher. 

### Test to reproduce
- Created test in JsonPartialMatcherTests.cs
- Used input: `{ "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User": "foo" }`
- Did not match

### Notes
The JToken.SelectToken fails to find the token, presumably because it treats the value as a JPath expression, and returns null causing the INPUT param of the IsMatch method to be null.

**Comment by StefH** [comment]
@epDugas 
I'm looking into this...

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1216

**Comment by epDugas** [comment]
Thanks @StefH !
