### ISSUE TITLE
Response Body Does Not Include Text After Path Segment

### ISSUE THREAD

**Issue by adambricelis** [WireMock-Net/WireMock.Net#1212]
### Describe the bug
When a field in the response body is prefixed with a path segment from the request, the text after that path segment is not included in the response body.

### Expected behavior:
WireMock should evaluate all of the text in the mapping and include all of it in the response.

### Test to reproduce
Mapping:
```
[
  {
    "Request": {
      "Path": "/path",
      "Methods": [
        "GET"
      ]
    },
    "Response": {
      "StatusCode": 200,
      "BodyAsJson": {
        "field": "{{request.PathSegments.[0]}}text_being_removed_incorrectly"
      },
      "UseTransformer": true,
      "Headers": {
        "Content-Type": "application/json"
      }
    }
  }
]
```
Request: `GET http://{WIREMOCK_SERVER_HOST}/path`
Expected response:
```
{
  "field": "pathtext_being_removed_incorrectly"
}
```
Actual response:
```
{
  "field": "path"
}
```

### Other related info
This issue only occurs when the request path segment is the prefix of a field in the response body. Adding any characters before the request path segment resolves the issue.

Mapping:
```
[
  {
    "Request": {
      "Path": "/path",
      "Methods": [
        "GET"
      ]
    },
    "Response": {
      "StatusCode": 200,
      "BodyAsJson": {
        "field": "prefix{{request.PathSegments.[0]}}text_being_removed_incorrectly"
      },
      "UseTransformer": true,
      "Headers": {
        "Content-Type": "application/json"
      }
    }
  }
]
```
Request: `GET http://{WIREMOCK_SERVER_HOST}/path`
Response:
```
{
  "field": "prefixpathtext_being_removed_incorrectly"
}
```

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1213
