### ISSUE TITLE
Order of WireMockContainerBuilder WithX calls caused duplicate Networks in Configuration

### ISSUE THREAD

**Issue by epDugas** [WireMock-Net/WireMock.Net#1217]
### Describe the bug
The order of the .WithX calls to WireMockContainerBuilder can cause duplicate Networks in Configuration.

### Expected behavior:
Expected the order of WireMockContainerBuilder.WithX calls to not duplicate Networks in the Configuration.

### Test to reproduce
- 1 Call `WireMockContainerBuilder.WithNetwork(x);`
- 2 Call `WireMockContainerBuilder.WithMappings(x)` and  `WireMockContainerBuilder.WithWatchStaticMappings(true);`
- 3 Observe the configuration has two Networks, when only one was added.

### Other related info
This was observed when updating WireMock.net. Some previous working code failed, an exception was thrown because of the duplicate Network entries in:
https://github.com/testcontainers/testcontainers-dotnet/blob/develop/src/Testcontainers/Clients/ContainerConfigurationConverter.cs at line 30.

```csharp
Networks = new ToNetworks(configuration).Convert(configuration.Networks)?.ToDictionary(item => item.Key, item => item.Value);
```

Changing the order of the .WithX calls resolved the issue.
![image](https://github.com/user-attachments/assets/e8f914d4-b410-4601-8540-d08f8b65c34e)

**Comment by StefH** [comment]
@epDugas 
Can you please provide a full working example (console app or unit test) which shows this issue?

**Comment by epDugas** [comment]
See attached for console app demonstrating issue. 
[dotnet_console_test.zip](https://github.com/user-attachments/files/18217305/dotnet_console_test.zip)

**Comment by StefH** [comment]
> See attached for console app demonstrating issue. [dotnet_console_test.zip](https://github.com/user-attachments/files/18217305/dotnet_console_test.zip)

Are you using Linux or Windows containers?

**Comment by StefH** [comment]
@epDugas 
Thanks for creating this issue. Some more entries where duplicated it seems.

It should be fixed now, can you use preview version 1.6.10-ci-19504
(https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions)

**Comment by epDugas** [comment]
Thanks @StefH !

> Are you using Linux or Windows containers?

Linux

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1222

**Comment by StefH** [comment]
@epDugas 
If you have time, you can test version `1.6.10-ci-19519`.

**Comment by epDugas** [comment]
> @epDugas If you have time, you can test version `1.6.10-ci-19519`.

Verified issue resolved. Thanks @StefH !
