### ISSUE TITLE
WireMock.Net not responding in unit tests - same works in console application

### ISSUE THREAD

**Issue by raheel0452** [WireMock-Net/WireMock.Net#122]
Dear Team,

In a console application, I've below code to start WireMock.Net 

// setup
            var server1 = FluentMockServer.Start(new FluentMockServerSettings
            {
                Urls = new[] { "http://localhost:9091" },
                ReadStaticMappings = true,
                StartAdminInterface = true
            });

This works all good.

When i write same in Unit tests, WireMock.Net does not respond
- unable to access localhost:9091
- static mappings are not read
- isStarted status though displays as true

It's mandatory for us to use port (i've referred to https://github.com/WireMock-Net/WireMock.Net/wiki/Using-WireMock-in-UnitTests)

Thanks in advance

**Comment by raheel0452** [comment]
Thank you for response.

Couple of questions from above request
1. can we not specify a port when running mockserver.net within unit tests?
2. can we not read static mappings when running mockserver.net within unit tests?

We've  attempted to start server without specifying any port. However the behavior remained same
- unable to access localhost:<port>
- static mappings are not read
(isStarted status though displays as true)

It's important for us to read static mapping from specified location.

Code we're trying with

var server1 = FluentMockServer.Start();
server1.ReadStaticMappings("<ProjectDirectory>\\bin\\Debug\\netcoreapp2.0\\__admin\\mappings");

Any thoughts ?

Thanks.

**Comment by StefH** [comment]
1. It is possible to use a fixed port, but then you have to start wiremock once, else you get conflicts. And when running the tests on a build server you can never be 100% sure that the port is free. Thats the reason that I start the server without a port, so that a free port is chosen. And use that port further.

2. This should work. Please search in my unit tests for the code which uses static mappings. Maybe the code has troubles finding the relative path?

**Comment by raheel0452** [comment]
Thank you. This is working now.

However one last point worth mentioning - when i execute unit test in debug mode, even though isStarted is set to true, i can't access the mockserver through browser until the continue debug. Is that expected ?

**Comment by StefH** [comment]
Probably expected, maybe not all async code is really listening.
