### ISSUE TITLE
How to get date in handlebar template 'yyyy-MM-dd' format

### ISSUE THREAD

**Issue by jusski** [WireMock-Net/WireMock.Net#1220]
If i set mapping to return date in "yyyy-MM-dd" format
``` json
"Response": {
    "StatusCode": 200,
    "BodyAsJson": {
      "date": "{{String.Format (DateTime.UtcNow) \"yyyy-MM-dd\"}}"
    },
    "Headers": {
      "Content-Type": "application/json; charset=utf-8"
    },
    "UseTransformer": true,
    "TransformerType": "Handlebar"
  }
```
im getting back wrong date format:
`
{
    "date": "2024-12-20T00:00:00"
}
`
Tried Scriban transformer too, with same results

**Comment by StefH** [comment]
It should be `"TransformerType": "Handlebars"`, however Handlebars should be take as default value.

I did test it in a unit test and it seems to work fine. Can you provide the complete mapping and the code how you use it?

**Comment by jusski** [comment]
Seems like i need to add option:
` "TransformerReplaceNodeOptions": "EvaluateAndKeep"`
And now it will not evaluate '2024-12-20' string value after transforming as date primitive again
Full example with added 'TransformerReplaceNodeOptions is:
`{
  "Request": {
    "Path": {
      "Matchers": [
        {
          "Name": "WildcardMatcher",
          "Pattern": "/test",
          "IgnoreCase": false
        }
      ]
    },
    "Methods": [
      "POST"
    ],
    "HttpVersion": "1.1",
    "Body": {
      "Matcher": {
        "Name": "JsonMatcher",
        "Pattern": {
          "personalCode": "11111"
        },
        "IgnoreCase": true,
        "Regex": false
      }
    }
  },
  "Response": {
    "StatusCode": 200,
    "BodyAsJson": {
      "date": "{{String.Format (DateTime.UtcNow) \"yyyy-MM-dd\"}}"
    },
    "Headers": {
      "Content-Type": "application/json; charset=utf-8"
    },
    "UseTransformer": true,
    "TransformerType": "Handlebar",
    "TransformerReplaceNodeOptions": "EvaluateAndKeep"
  }
}`
