### ISSUE TITLE
grpc client side loadbalancer support

### ISSUE THREAD

**Issue by GomesNayagam** [WireMock-Net/WireMock.Net#1226]
my code i am using [Static](https://learn.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-9.0) 
StaticResolverFactory to address client side LB, how do i create similar stuff here, will it work with single url?

the grpc wiremock, appreciate with e.g.

**Comment by StefH** [comment]
I don't understand what you are trying to do.

WireMock.Net runs on a single URL, so just configure the client to use that URL, and it will work.

**Comment by GomesNayagam** [comment]
probably i dint explain in detail, in my actual code i cant make changes, it is using client side LB for grpc. the above msdn link will show the e.g. i am testing by passing single url, let me update this thread if works. thx.

**Comment by GomesNayagam** [comment]
this works can be closed.
