### ISSUE TITLE
Fix for DateTime Header causing null value in ResponseBuilder

### ISSUE THREAD

**Issue by rangerranger** [WireMock-Net/WireMock.Net#123]
Having the below header in a static mapping file as part of the response results in a NULL value being returned to ResponseBuilder in InitResponseBuilder, since it either expects a string or json - but this header value is being read in as a DateTime object.

"Rate-Limit-Reset": "2018-04-09T20:39:46.956Z",

I added a quickfix like so, please let me know if that looks ok?
In src/WireMock.Net/Server/FluentMockServer.Admin.cs:
https://github.com/rangerranger/WireMock.Net/commit/747524c03fdd79915075e307e11b20795f5ccc69#diff-8633a9484e8c211d1cc3fc5d0c12f4de

**Comment by StefH** [comment]
This quickfix contains two things? JsonExactMatcher code, do you still need that?
And the datetime fix.

Can you make a PR with just the datetime header fix and also add some unittests?

**Comment by rangerranger** [comment]
I will add the unit tests for the DateTime fix and create a separate PR. As to the ExactJsonMatcher - please can you tell me how to correctly use the JsonPathMatcher if we want to just record request/responses via proxy WireMock and then use them to mock? In that case the JsonPathMatcher is not matching the subsequent requests even when they are exact same Json, Does the recording need to be changed to some JsonPath syntax after recording? Thank you Stef.

**Comment by StefH** [comment]
If using WireMock to proxy request, please take a look at this code here:

https://github.com/WireMock-Net/WireMock.Net/blob/master/examples/WireMock.Net.Console.Proxy.Net452/Program.cs

Change this code
``` c#
SaveMapping = true,
SaveMappingToFile = true
```

This will save each request and response in a file.

I hope this helps?

**Comment by rangerranger** [comment]
I think i didnt explain clearly. I am able to proxy and record. But when using the recorded mapping files for mocking, the jsonpathmapper never matches the requests - same requests that were recorded. Thats the reason i created the JsonExactMatcher. Is there something im doing wrong in using JsonPathMapper if i want it to match the complete json in the recorded request exactly?

**Comment by StefH** [comment]
Ok I see.

When using the saved request, sometimes it's needed to manually adjust the mapping a bit because the matching is too strict because not only the body is matched but also headers, query and others.

Make sure to enable partial mapping and then do a http get request to /__admin/requests to see the matching details from the request you did send. Look for matchings where the match is 0.

**Comment by rangerranger** [comment]
Right. Still keeping PartialMatching to FALSE, i can match with JsonExactMatcher but not with JsonPathMatcher. Not sure why - couldnt get JsonPathMatcher to work. Therefore wrote the simple JsonExactMatcher. I can send you the mapping file as an example repro if uou want - but JsonPathMatcher returns score 0.

**Comment by StefH** [comment]
From now on it's also possible to use a simple Wildcard (string-matcher) for JSON messages, will this help you in this case?

**Comment by rangerranger** [comment]
Hi Stef, apologies for the late response (have been slammed). Yes that
would be a great addition indeed. What I discovered was that while *proxy
recording*, the body (or bodyasjson or bodyasbytes) in the *request* is not
recorded. And hence when we try to match with a specific body difference it
is not available in the mapping.
I can understand why this is the case, as the library wouldnt know what
matcher to use (esp for bodyasbytes).
While I added a matcher that is useful for our work and put it in the
library, that is not an extensible approach.
Instead could we have a mechanism where a matcher is created outside the
library and provided to the FluentServer as part of the settings? Just like
for the logger.
There can be a CustomBodyMatcher, CustomBodyAsJsonMatcher and
CustomBodyAsBytes matcher fields in the FluentServerSettings, which are
then used during recording. Similarly they would have to be passed in also
for standard mocking (ie non-proxy server).
Thoughts?
Aroon

**Comment by StefH** [comment]
Hi Aroon,

1]
The code block you mention is not changed in latest releases. However I think the proxy code works fine.

When you post a string as body, or a json string, the body is added to the request and the exact string is added as pattern and exact matcher is used.

So when I send this using postman:
![post](https://user-images.githubusercontent.com/249938/40310571-802993dc-5d0d-11e8-957c-2722c92bb14d.png)

I get exactly what I posted in option 1 above.

Now it's up to the user from WireMock to analyze the whole request, and check if some thing need changing. In order to craft the correct mapping.


2]
The bodyasbytes is not supported as is, but I believe that when you send a binary using post, the body is recorded as base64.

3]
When you want custom matchers, you can just use one of the `Func` methods:
``` c#
/// <summary>
/// WithBody: func (string)
/// </summary>
/// <param name="func">The function.</param>
/// <returns>The <see cref="IRequestBuilder"/>.</returns>
IRequestBuilder WithBody([NotNull] Func<string, bool> func);

/// <summary>
/// WithBody: func (byte[])
/// </summary>
/// <param name="func">The function.</param>
/// <returns>The <see cref="IRequestBuilder"/>.</returns>
IRequestBuilder WithBody([NotNull] Func<byte[], bool> func);

/// <summary>
/// WithBody: func (object)
/// </summary>
/// <param name="func">The function.</param>
/// <returns>The <see cref="IRequestBuilder"/>.</returns>
IRequestBuilder WithBody([NotNull] Func<object, bool> func);
```
See https://github.com/WireMock-Net/WireMock.Net/blob/a8ddd31c9ce3a77d3c6c32df7f0d6652a3727fd4/src/WireMock.Net/RequestBuilders/IBodyRequestBuilder.cs#L48

**Comment by StefH** [comment]
Hello @rangerranger : Is my post above clear ?

**Comment by rangerranger** [comment]
Hi Stef, does the recording of json in body work when you set content-type header as application/json? I believe it puts the content in bodyAsJson member of the request object and the body is empty in recorded mapping.

With regards to custom matchers and your suggestion of using func: im not sure how it would work for recorded mappings? 

Aroon

**Comment by StefH** [comment]
a] The recording of **any** body should work, you don't need to use that content-type.

b] Correct. You cannot use that directly. There is no possible way yet to convert a recorded mapping (json) into the C# code which defines that mapping. I can investigate if this is easy to build...

**Comment by rangerranger** [comment]
My testing shows that if the application being mocked(recorded) sets the application/json header then the body is not recorded. If i remember that was because the body content is placed in BodyAsJson and that segment of wiremock code is empty. I could ld be wrong, can test again.

**Comment by StefH** [comment]
A quick question: you are using a POST or PUT request ?

**Comment by StefH** [comment]
Latest version support a new matcher : `JsonMatcher` which can be used to match a json body 1:1.

See also https://github.com/WireMock-Net/WireMock.Net/issues/154

I'm closing this issue now, please open a new one with details if you still have issues.

Or start a chat at https://gitter.im/wiremock_dotnet/Lobby
