### ISSUE TITLE
Question: How to specify Transfer-Encoding response header?

### ISSUE THREAD

**Issue by o7g8** [WireMock-Net/WireMock.Net#137]
Hello,

I need to specify my own `Transfer-Encoding` response header as it's shown in the example below:

```csharp
        [TestMethod]
        public async Task CheckMockHeaders() {
            var responseBody = @"<?xml version=""1.0""?><empty/>";
            mockServer
                .Given(Request
                    .Create()
                    .WithPath("/test")
                    .UsingPost())
                .RespondWith(Response
                    .Create()
                    .WithStatusCode(200)
                    .WithHeader("content-type", "text/xml")
                    .WithHeader("Content-Length", responseBody.Length.ToString())
                    .WithHeader("Transfer-Encoding", "identity")
                    .WithBody(responseBody));
            using (var httpClient = new HttpClient()) {
                var uri = mockServer.Urls.Single() + "test";
                using (var response = await httpClient.PostAsync(uri, new StringContent(""))) {
                    response.EnsureSuccessStatusCode();
                    
                    var transferEncoding = response.Headers.SingleOrDefault(x => x.Key == "Transfer-Encoding");
                    Assert.IsNotNull(transferEncoding);
                    Assert.IsTrue(transferEncoding.Value.Contains("identity"));
                }
            }
        }
```

The last `Assert` fails, because the `Transfer-Encoding` is always `chunked`.
Is it possible to override it?

WireMock.Net  version `1.0.3.16`.

**Comment by StefH** [comment]
Linked to #136

**Comment by StefH** [comment]
Solved, see NuGet 1.0.3.18

**Comment by GMPrakhar** [comment]
I am seeing this issue again.. Transfer-encoding always goes as chunked when used with WithBodyFromFile

**Comment by gorillapower** [comment]
I am seeing this issue too, the Transfer-Encoding header should be allowed to contain multiple values, as long as the last value is chunked, then it should be valid as a chunked request.


![image](https://user-images.githubusercontent.com/8879065/232445053-167acda6-f779-4178-aec0-eb75ce394a6f.png)


https://www.rfc-editor.org/rfc/rfc9112#section-6.1-4:~:text=If%20any%20transfer%20coding%20other%20than%20chunked%20is%20applied%20to%20a%20response%27s%20content%2C%20the%20sender%20MUST%20either%20apply%20chunked%20as%20the%20final%20transfer%20coding%20or%20terminate%20the%20message%20by%20closing%20the%20connection.
