### ISSUE TITLE
Wiki link https://github.com/StefH/WireMock.Net/wiki/Record-(via-proxy)-and-Save is dead

### ISSUE THREAD

**Issue by o7g8** [WireMock-Net/WireMock.Net#139]
The wiki main page https://github.com/WireMock-Net/WireMock.Net/wiki has a wrong link for `Wiki : Record (via proxy) and Save. ` it refers to https://github.com/StefH/WireMock.Net/wiki/Record-(via-proxy)-and-Save which redirects to the main page again.

**Comment by StefH** [comment]
Fixed
