### ISSUE TITLE
CORS headers for the admin API

### ISSUE THREAD

**Issue by alastairtree** [WireMock-Net/WireMock.Net#141]
I have a requirement to support CORS requests on the admin API. Either I add these extra headers to all admin API responces, or i add a setting to enable them and allow users to switch them on as they wish. Normally I prefer security by default, and so CORS would be an opt-in feature, however in this case I cannot think of any realistic scenario where you would want to disable CORS support on the admin API. Wiremock is purely a test tool and not designed for production use, and besides it already has admin API security if needed, and CORS defence is to stop dodgy iframing, which does not seem relevant to wiremock. I think productivity weights more to me than security here - any reason not to just allow all CORS requests on the admin API?

**Comment by alastairtree** [comment]
(Work started over at https://github.com/alastairtree/WireMock.Net/commit/06a7122d6620155b889232ce9c42ed31de61c722)

**Comment by StefH** [comment]
CORS support sounds OK to add, at least when it's configurable.

In your code I see that you are adding the CORS header manually, isn't there an settings in OWIN to configure this?

**Comment by StefH** [comment]
@alastairtree Any status on this one?

**Comment by StefH** [comment]
@alastairtree Any updates on your work?

**Comment by alastairtree** [comment]
No sorry, this stalled and I have not taken it any further. Realisticly I am unlikely to carry this on so maybe we should just close it?

**Comment by StefH** [comment]
No problem. I'll just close this issue.

Take care !
