### ISSUE TITLE
Hang possibly due to Windows firewall prompt

### ISSUE THREAD

**Issue by alexangas** [WireMock-Net/WireMock.Net#146]
Hello again 😃

Unfortunately after [this change to PortUtil.cs](https://github.com/WireMock-Net/WireMock.Net/blob/a9e6064422dc77bfdd27e813c5bd501dc28eef21/src/WireMock.Net/Http/PortUtil.cs) introduced in WireMock.Net 1.0.3.19, the behaviour has changed which is causing some issues.

When trying to use this version on our build server, unit tests that use WireMock hang as soon as their execution commences. I noticed when running them on my dev machine that I was now prompted by Windows Firewall to grant dotnet.exe extra permissions. So my guess is that this same prompt is happening on the build server which we don't have access to.

I tried a couple of things which seem to have fixed the issue on my dev machine, but may well cause problems for others! Without a NuGet package (pre-release would do) I can't test on the build servers.

1. In PortUtil.cs line 21, changed `AddressFamily.InterNetwork` to `DefaultLoopbackEndpoint.AddressFamily`
2. In AspNetCoreSelfHost.cs lines 79 and 85, changed `System.Net.IPAddress.Any` to `System.Net.IPAddress.Loopback`

What are your thoughts?

**Comment by StefH** [comment]
Hello Alex,

I'll revert back the code for point 1.

About point 2 ; this was not changed by me I guess in the last checkin?

**Comment by alexangas** [comment]
Sorry for not being clear - those points 1 and 2 are things I changed to try and fix this issue based off the WireMock 1.0.3.19 release. It seemed to do it, but i'm not sure if it has unintended site effects.

**Comment by StefH** [comment]
For now I close this one.
