### ISSUE TITLE
Feature: Expose scenario states

### ISSUE THREAD

**Issue by benjamin-bader** [WireMock-Net/WireMock.Net#163]
I'd like to be able to ask the server what the current state is for a given feature, for example to concisely verify that all expected requests were received, e.g.

```csharp
Check.That(server.Scenarios["oauth flow"].State).Is("finished");
```

One could get the same effect today by groveling through the LogEntries, but this is tedious and duplicates the logical chain set up by the scenario itself.

**Comment by StefH** [comment]
Good idea.

I need to extend the admin api with some get request to retrieve the state from a certain scenario.

Also add this logic to the fluent interface.

**Comment by StefH** [comment]
Hello @benjamin-bader,

I've added some functionality in this branch, you can already take a look how it can be used as you proposed here:
https://github.com/WireMock-Net/WireMock.Net/blob/Expose_scenario_states/test/WireMock.Net.Tests/StatefulBehaviorTests.cs#L66

**Comment by benjamin-bader** [comment]
Oh, cool!  I was going to try my hand at this, but you've beaten me to it.  Thank you for taking the effort!

**Comment by StefH** [comment]
OK, I'll change the code and create a new NuGet in some time...
