### ISSUE TITLE
Feature: Mapping files lost when restarting an Azure app service

### ISSUE THREAD

**Issue by craigt00** [WireMock-Net/WireMock.Net#173]
I've found that when hosting WireMock.Net in an Azure app service the mappings are lost when the app service restarts.  I presume this is due to the resolved location of Directory.GetCurrentDirectory() when running in Azure which may be getting cleaned out during a restart.

If this is the case, could I suggest that the base directory is injected in (via IFluentMockServerSettings?) and, if set, used instead of GetCurrentDirectory()?  This can then be specifically set for the example projects which need to control the location of their files such as WireMock.Net.WebApplication.NETCore2.

As an alternative, the files could be stored within Azure File or Blob storage (again, via dependancy injecting in a new class to handle file system activity).

**Comment by StefH** [comment]
Good point. The same issue will probably be the case for a docker image.
The best solution would be via dependency injection / new classes to handle file system activity.

Example:
``` c#
interface IDirectoryHandler
{
  string GetCurrent();

  bool Exists(string path);
}

interface IFileHandler
{
  string ReadAllText(string path);

  void WriteAllText(string text);
}
```

Where by default these classes will handle the local file-system.

**Comment by StefH** [comment]
@craigt00 

I've implemented this change into this branch:
https://github.com/WireMock-Net/WireMock.Net/blob/stef_issue_173_mappingfiles_location/src/WireMock.Net/Handlers/IFileSystemHandler.cs

Can you please review ? If it's good enough, I'll merge to master.

**Comment by craigt00** [comment]
That looks great, and will allow me to create a azure-specific implementation.  Thanks for working on this @StefH 

Is the web application example intended to be Azure-specific?  If so then I'll fork and update the web application to implement an AzureFileSystemHandler which places the mapping files alongside the site.

**Comment by StefH** [comment]
The web-application can run as standalone, web-IIS or Azure.

So for your idea, maybe best to create a new example project called **WireMock.Net.Azure.NETCore2** which implements that `AzureFileSystemHandler`.

Or update the original example to use a switch in the configuration to choose the FileHandler.

I'll create a PR merge tho master in some time today.

**Comment by StefH** [comment]
Linked https://github.com/WireMock-Net/WireMock.Net/pull/180
