### ISSUE TITLE
Issue: Case of header key/name not ignored in RequestBuilder when ignoreCase == true

### ISSUE THREAD

**Issue by SubjectiveReality** [WireMock-Net/WireMock.Net#189]
Given the following C# mapping:
``` c#
        server
                .Given(
                Request.Create()
                    .WithPath("/blah/blah")
                    .WithHeader("SOAP", "myHeaderBlah", true)
                )
                .RespondWith(
                    Response.Create()
                        .WithBody("found your soap header")
               );
```
WireMock.net mapping will be found if a request is made with a header where SOAP casing matches exactly, but will not be found if the casing does not match exactly (i.e. Soap).

**Comment by StefH** [comment]
Issue is confirmed. I'll investigate.

Probably the same issue is with cookies...

**Comment by StefH** [comment]
Solved. A new NuGet will be uploaded shortly...

**Comment by SubjectiveReality** [comment]
Wow, that's awesome speed, Stef!  Thank you!
