### ISSUE TITLE
Cannot upgrade from 1.0.4.10 to 1.0.4.12 without upgrading to .net core 2.1

### ISSUE THREAD

**Issue by bgiot** [WireMock-Net/WireMock.Net#192]
Got the following error :
NU1605: Detected package downgrade: Microsoft.Extensions.Configuration.Json from 2.1.1 to 2.0.2.
The dependency on Microsoft.AspNetCore has been changed from >=2.0.0 to >=2.1.2. 
Why this happens for a such WireMock.Net minor upgrade version ?

**Comment by StefH** [comment]
The reason for this is that I was solving a bug related to net461 and OWIN.

But if it helps you, I can revert back to the most recent 2.0.x version, which would be 2.0.4 ?

**Comment by bgiot** [comment]
Can be an option. I'lltry first to see in my own dependencies can be upgraded and still work on .net core 2.0.  Maybe by design keep lowest working dependencies to avoid forcing upgrade unless necessary...

**Comment by StefH** [comment]
Please keep me updated on your investigation.

It's not much work for me to downgrade and create a new NuGet.

Thanks for the advice about the dependencies, I know this rule, but sometimes I forget ;-)

**Comment by bgiot** [comment]
Seems to be fine on my side. I succeeded to do the necessary upgrade without any big issues. Let's close this bug.

**Comment by StefH** [comment]
ok
