### ISSUE TITLE
Question: WireMock in Azure

### ISSUE THREAD

**Issue by cpneale** [WireMock-Net/WireMock.Net#193]
Hi,

Is it possible to start a standalone WireMock server from a Web App or Web Job in Azure and then hit the WireMock instance on an external uri?

Thanks!

**Comment by StefH** [comment]
I doubt that this is possible.

However you can run WireMock.Net as a full server as WebApp or in Azure, take a look at:
https://github.com/WireMock-Net/WireMock.Net/wiki/WireMock-as-a-(Azure)-Web-App

**Comment by cpneale** [comment]
Thanks.  Appreciate the quick response and advice.

**Comment by StefH** [comment]
Let me know if this works for you. If all works fine, you can close this issue.

**Comment by cpneale** [comment]
Yes, works fine. Thanks for your help.
