### ISSUE TITLE
Could not load file or assembly 'netstandard, Version=2.0.0.0 On Build Server

### ISSUE THREAD

**Issue by gifthove** [WireMock-Net/WireMock.Net#194]
I have this issue on my Jenkins build server _"System.BadImageFormatException : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)"_.   To give you context, i have a unit testing  project with .Net Framework 4.6.1 and i  am using Wiremock for stubbing out an API. So the error occurs when starting the  stub server _"this._stubServer = FluentMockServer.Start();_" On the build server i have ASP.NET Core/.NET Core: Runtime & Hosting Bundle installed. What could be the issue?

**Comment by StefH** [comment]
This issue is new for me.

Are you running the build on a non-windows machine?

**Comment by gifthove** [comment]
Our build server is windows 2012  Server.

**Comment by StefH** [comment]
I don't have a clue what's wrong here. Do you still have this issue?

**Comment by StefH** [comment]
Closing this issue.

If you still have an problem, please comment and re-open this one.
