### ISSUE TITLE
Issue : creating response using .WithBody(Func<RequestMessage, string>...) and .WithStatusCode

### ISSUE THREAD

**Issue by rickm-pra** [WireMock-Net/WireMock.Net#198]
If I set up a response using both .WithBody and .WithStatusCode, it always returns a status code of 200. For example:
```
            _mock.Given(
                Request.Create()
                    .UsingPut()
                    .WithPath("/myendpoint")
            ).RespondWith(
                Response.Create()
                    .WithStatusCode(500)
                    .WithBody(requestMessage =>
                    {
                        var returnStr = JsonConvert.SerializeObject(new
                        {
                            Message = "Test error"
                        });
                        return returnStr;
                    })
                    );
```
will return the error message but with a 200 status.

It looks like the root cause is that the response callback is creating a new response instead of using the one that was configured.

**Comment by StefH** [comment]
Do you have multiple mappings defined, or just this one?

In case you have multiple, it could be that another mapping does match better than this one.

**Comment by rickm-pra** [comment]
I tried it both ways. The number of mappings has no effect.

**Comment by rickm-pra** [comment]
My crude fix was to change ProvideResponseAsync in Response.cs:
```
             if (Callback != null)
            {
                var message = Callback(requestMessage);
                message.StatusCode = ResponseMessage.StatusCode;
                return message;
            }
```

I doubt very much this is the right fix, but it does set the code properly.

**Comment by StefH** [comment]
This is indeed a bug. Thanks for reporting. I'll investigate and fix this.

**Comment by rickm-pra** [comment]
Thanks!

**Comment by StefH** [comment]
Issue is solved, I created a PR , take a look here:
https://github.com/WireMock-Net/WireMock.Net/pull/199

You can review but probably not approve this PR?

**Comment by rickm-pra** [comment]
I can review, but it's not a binding approve. Looks good though!
