### ISSUE TITLE
Add client certificate authentication

### ISSUE THREAD

**Issue by phillee007** [WireMock-Net/WireMock.Net#20]
Is it possible to add this functionality as well? :-)

**Comment by StefH** [comment]
I don't know if this is easy. Let me think about this.

**Comment by phillee007** [comment]
No problem. We have a number of calls to services that require client certs
for auth, so I figured the stub service might need the same. l I guess we
could turn it off when talking to stub endpoints though?

**Comment by phillee007** [comment]
Have had a look & I'm not sure it's modelled quite right. Each request mapping gets its own settings for proxy url/cert filename (plus also needs password if specified), so there would be no need to specify them in the mock server general settings (or as command-line args) as they wouldn't be used.
I've cloned the repo & will try it out locally over the next week or so to see what i can do.

**Comment by billybraga** [comment]
Was this ever done?

**Comment by StefH** [comment]
Sorry.
No this is not implemented.
