### ISSUE TITLE
Issue: Incorrect port matching

### ISSUE THREAD

**Issue by alec-anikin** [WireMock-Net/WireMock.Net#200]
Hi!
Regex from PortUtil.UrlDetailsRegex  doesn't work for urls like "http://0.0.0.0:5000"
It should be `^(?<proto>\w+)://[^/]+?:(?<port>\d+)/?`

**Comment by StefH** [comment]
Hello @alec-anikin, thanks for reporting.

However, maybe updating the regex even further to `^((?<proto>\w+)://)(?<host>[^/]+?):(?<port>\d+)\/?$` is even better?

For `https://0.0.0.0:5000` , this matches like:
![afbeelding](https://user-images.githubusercontent.com/249938/45348735-b8da0400-b5af-11e8-9567-409e25e3f235.png)

And for `https://locahost:5000` , this matches like:
![afbeelding](https://user-images.githubusercontent.com/249938/45348785-d909c300-b5af-11e8-82ce-87f44c1fe9df.png)

**Comment by StefH** [comment]
Hi @alec-anikin ; what do you think?

**Comment by StefH** [comment]
Will be fixed in PR
