### ISSUE TITLE
Issue: DELETE method is proxied as lowercase

### ISSUE THREAD

**Issue by r-kolbovich** [WireMock-Net/WireMock.Net#205]
I noticed quite strange behavior of wiremock when it proxies requests to another server.
'GET', 'POST', 'PUT' methods, are proxied uppercase. But 'DELETE' method behaves different: after proxying it becomes 'delete'.

Below you can find a gif where I demonstrate this issue. 
![wiremock-delete-request-lowercase](https://user-images.githubusercontent.com/9084096/45630837-39ae6980-baa2-11e8-8e2b-389643623442.gif)

Below is my code, which just proxies everything to http://httpbin.org - simple online REST API for debugging. I've used latest version of WireMock.Net (1.0.4.16):
```
class Program
{
    static void Main(string[] args)
    {
        var server = FluentMockServer.StartWithAdminInterface(9999);
        Console.WriteLine("FluentMockServer running at {0}", server.Ports.First());

        server.Given(
            Request.Create().WithPath("*")
        )
        .RespondWith(
            Response.Create().WithProxy("http://httpbin.org")
        );

        Console.ReadKey();
    }
}
```

**Comment by StefH** [comment]
I did not catch which dotnet version you are using?

**Comment by r-kolbovich** [comment]
.NET Framework 4.6.1

**Comment by StefH** [comment]
This is indeed a bug. I'm investigating this and already have a fix ready. I keep you updated here on the progress.

**Comment by StefH** [comment]
Solved in new package (soon to be added to NuGet)
