### ISSUE TITLE
Feature: Add support for template language DotLiquid

### ISSUE THREAD

**Issue by StefH** [WireMock-Net/WireMock.Net#214]

**Comment by n1l** [comment]
Hi I wish ti help you to implement the feature.
Can you please describe the motivation. Why do you want to implement the feature. How do you want to use liquid markup language?

**Comment by StefH** [comment]
Currently I support Handlebars.Net as response templating language (https://github.com/WireMock-Net/WireMock.Net/wiki/Response-Templating).

However, It would also be a nice option to support DotLiquid as templating engine.

**Comment by n1l** [comment]
@StefH is DotLiquid critical? from my point of view it's not stable. There is another library called scriban. What do you think?

https://github.com/scriban/scriban

**Comment by StefH** [comment]
My idea to support DotLiquid was that I think that also Microsoft used this for generating (help) pages.

But I see that scriban supports both, so that would be a good solution.

However the code from WireMock.Net does not support other transformation engines yet, so that needs to be reworked first.

**Comment by n1l** [comment]
@StefH Can you please provide any links about microsoft used DotLiquid?

About other transformations engines, what do you mean exactly? And what should be reworked from your perspective?

**Comment by StefH** [comment]
1. I can't find the link / reference from Microsoft anymore.
2. The current code can only support 1 transformation engine (https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Transformers/ResponseMessageTransformer.cs)
So some changes need to be done to support also **scriban**. And remain backward compatible (so that the default transformation will be done by handlebars)

**Comment by StefH** [comment]
Scriban does only support .netstandard 2.0 and net5.0
https://www.nuget.org/packages/Scriban/

So that's difficult to use in WireMock.Net

**Comment by StefH** [comment]
@n1l 
Older version from Scriban do support older frameworks, so that's good.

I've update the code to also support Sciban

See this MyGet preview:
WireMock.1.4.1-ci-14471

**Comment by n1l** [comment]
Did you finish the code? I was going to help you, but as I can see you did it alone? :)

**Comment by StefH** [comment]
Correct, I think I've the code change in place.

However, the syntax from Sciban does differ in some parts from Handlebars.Net , so I could not get all unit tests working.

Maybe you can take a look there?

**Comment by n1l** [comment]
It would be easier to me to start from the white paper not to fix the code you have written.

**Comment by StefH** [comment]
I noticed these differences:
- DOT notation for accessing this `{{request.PathSegments.[0]}}` does not work
- WireMockList is not supported by Scriban

**Comment by StefH** [comment]
Code is merged to maaster and a new NuGet will be released.

Further fixes like 
- DOT notation for accessing this {{request.PathSegments.[0]}} does not work
- WireMockList is not supported by Scriban

Will be maybe taken up in another PR
