### ISSUE TITLE
Timeout Exception on VSTS Test Platform (Azure DevOps), with private build agent

### ISSUE THREAD

**Issue by Tieno** [WireMock-Net/WireMock.Net#234]
In release 1.4.20 I get a timeout exception everytime the test agent tries to start the FluentMockServer

Following exception is thrown right after 
`"FluentMockServer.Start()"`
```
System.TimeoutException : Service start timed out after 00:00:10
Stack trace
   at WireMock.Server.FluentMockServer..ctor(IFluentMockServerSettings settings) in /Server/FluentMockServer.cs:line 225
   at WireMock.Server.FluentMockServer.Start(Nullable`1 port, Boolean ssl) in /Server/FluentMockServer.cs:line 110

```
I don't get this when running the test locally.
I've tried turning off the windows firewall entirely, on the build machine, but it doesn't make any difference. I still get the timeout exception.
After seeing issue   #146, I reverted to version 1.3.18 and I don't experience any timeout exception anymore.

Anybody know what's causing the timeout exception?

**Comment by StefH** [comment]
Do you run on Linux or Windows build ?
(BTW : The DevOps pipeline used by WireMock itself works fine.)

**Comment by Tieno** [comment]
- Windows Build. Machine itself runs Windows 8.
- XUnit 2.2
- Visual Studio Test Platform (Installer)

**Comment by backlune** [comment]
Been having the same issue on one of our slower build servers. The reason for getting a `TimeouException` might be different as some exceptions are not observed when starting the server.

To find out why we were getting `TimeoutException` change to checking it the task had an exception before throwing timeout in FluentMockServer constructor.

```
            var startTask = _httpServer.StartAsync();

            using (var ctsStartTimeout = new CancellationTokenSource(settings.StartTimeout))
            {
                while (!_httpServer.IsStarted)
                {
                    // Throw out exception if service start fails
                    if (_httpServer.RunningException != null)
                    {
                        throw new Exception($"Service start failed with error: {_httpServer.RunningException.Message}", _httpServer.RunningException);
                    }

                    // Respect start timeout setting by throwing TimeoutException
                    if (ctsStartTimeout.IsCancellationRequested)
                    {
                        if (startTask.Exception != null) { throw startTask.Exception; }
                        throw new TimeoutException($"Service start timed out after {TimeSpan.FromMilliseconds(settings.StartTimeout)}");
                    }

                    ctsStartTimeout.Token.WaitHandle.WaitOne(ServerStartDelay);
                }
            }
```

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/235

**Comment by StefH** [comment]
version 1.0.4.21 will implement code fixes as proposed by @backlune
