### ISSUE TITLE
doc stubbing out of date

### ISSUE THREAD

**Issue by xbollart** [WireMock-Net/WireMock.Net#246]
Hi guys,

Your lib looks really great, it would be great to have you wiki up to date too! Especially on Stubbing.
I guess you did a pretty big renaming there.

Thanks!

https://github.com/WireMock-Net/WireMock.Net/wiki/Stubbing

**Comment by StefH** [comment]
Hello @xbollart can you please provide some more details what is wrong/missing?

**Comment by StefH** [comment]
@xbollart Can you please help me?
