### ISSUE TITLE
Request Path and query parameter keys are case-sensitive

### ISSUE THREAD

**Issue by simardst** [WireMock-Net/WireMock.Net#253]
In many cases, the casing of the request path and the querystring keys (not the values) is not important. It would be very usefull to:
- be able to match the request path in a case-insensitive way.
- be able to math the request querystring keys in a case insensitive way.

This could be a global settings or configurable for each request (whatever is the simplest way to implement it).

**Comment by StefH** [comment]
For **path** , you should be able to use:
``` js
"Request": {
        "Path": {
            "Matchers": [
                {
                    "Name": "WildcardMatcher",
                    "Pattern": "/param2",
                    "IgnoreCase": true
                }
            ]
        },
        "Methods": [
            "get"
        ]
    },
```

**Comment by simardst** [comment]
Thank you, but achieving the same fot he querystring keys is far more complex.  I achieve to create an extension for the path, but didn't find any way to do the same with the querystring jeys.

**Comment by StefH** [comment]
Cookies and Headers do support this logic.

But I think indeed that querystring does not support this.

I will take a look at the code to ser if I can add logic.

**Comment by StefH** [comment]
I've updated the code and new NuGet is available on MyGet (https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions)
**WireMock.Net.1.0.8-ci-11023**

Use it like:
``` js
{
    "Guid": "6dcb57d1-2571-48d8-98fd-fc1c877104d3",
    "Request": {
        "Path": {
            "Matchers": [
                {
                    "Name": "WildcardMatcher",
                    "Pattern": "/param",
                    "IgnoreCase": true
                }
            ]
        },
        "Methods": [
            "get"
        ],
        "Params": [
            {
                "Name": "KeY",
                "IgnoreCase": true,
                "Matchers": [
                    {
                        "Name": "ExactMatcher",
                        "Pattern": "test"
                    }
                ]
            }
        ]
    },
    "Response": {
        "BodyAsJson": {
            "result": "!!!"
        }
    }
}
```

Will match:
`http://{{wm_hostname}}/param?key=test`
and
`http://{{wm_hostname}}/param?kEY=test`

**Comment by StefH** [comment]
@simardst does this work for you?

**Comment by simardst** [comment]
This seems to resolve our issues, and I will test it using your preview version by the end of the day.
Thank you very much.

**Comment by StefH** [comment]
You're welcome.

If you have tested and all is working as expected, I'll merge this code to master and create a new official nuget.

**Comment by simardst** [comment]
This works perfectly!
I will update as soon as it is available.

**Comment by StefH** [comment]
So all is tested and I can merge and create a new official NuGet?

**Comment by simardst** [comment]
As far as I'm concerned, yes you can proceed.

**Comment by StefH** [comment]
A new NuGet will be released soon.
