### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by Beaverkilla** [WireMock-Net/WireMock.Net#265]
Wiremock supports file uploading/downloading/deletion through the path __admin/files/{filename}, it'd be good if there was a WireMock.Net equivalent for file operations while testing etc.

**Comment by JackCreativeCrew** [comment]
I've written some code to enable GET/PUT/DELETE for files to this endpoint, can I create a pull request?

**Comment by StefH** [comment]
@Beaverkilla good idea!
@JackCreativeCrew thanks for the initial code

I did update the code, and also added a PostFile.
Can you review PR?

**Comment by StefH** [comment]
Code is merged to master, a new NuGet will be created today....
