### ISSUE TITLE
Assembly does not have strong name

### ISSUE THREAD

**Issue by megha222** [WireMock-Net/WireMock.Net#267]
In a build environment where strong name trust checks are not bypassed for an application, this package cannot be used.
Referenced assembly 'WireMock.Net, Version=1.0.11.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.	
Can you consider posting a new version with a strong name?

**Comment by StefH** [comment]
I can strong-name these, however this will be done with a visible certificate, so not really secure.

**Comment by megha222** [comment]
That is ok.  https://blogs.msdn.microsoft.com/ericlippert/2009/09/03/whats-the-difference-part-five-certificate-signing-vs-strong-naming/
Thanks

**Comment by megha222** [comment]
@StefH any plans on doing this?

**Comment by StefH** [comment]
I can do this, I'll let you know the progress.

**Comment by codeplayer14** [comment]
@StefH Eagerly waiting for this. Would be of great help!

**Comment by StefH** [comment]
New NuGet version is uploaded.
