### ISSUE TITLE
New feature: Record and Save

### ISSUE THREAD

**Issue by StefH** [WireMock-Net/WireMock.Net#27]
http://wiremock.org/docs/record-playback/

**Comment by StefH** [comment]
Hello @phillee007 , if you have time, can you do some testing with **Proxy** and **Record and Save** ?

**Comment by phillee007** [comment]
Will have a try, although unfortunately all the real services we call require client certificates, so I'm not sure whether it will be possible. I saw a section on http://wiremock.org/docs/proxying/ about how to setup client certificate forwarding on java, but will have to do some reading to find out the .Net equivalent...

**Comment by StefH** [comment]
What kind of certificate would you be using ?
Is that a **X509Certificate2** ?

**Comment by phillee007** [comment]
Yep that's right

**Comment by StefH** [comment]
I've updated the code and added logic to provide `X509Certificate2Filename`.

I'm not sure if this works, I'm unable to test this myself.

**Comment by phillee007** [comment]
Thanks Stef. I'll give it a try and submit a PR if I need to change it :-)

**Comment by StefH** [comment]
Any luck?

**Comment by phillee007** [comment]
Not yet I'm afraid. Our testers took a while to get on board with the whole
concept of what wiremock actually does,  so i had no spare time to test the
client cert stuff. I will in the next two weeks though :-)

**Comment by StefH** [comment]
@phillee007
Closing for now, in case you have more time to investigate on this subject, please open a new issue.
