### ISSUE TITLE
No server response in Postman and Receive Failure in Fiddler

### ISSUE THREAD

**Issue by codeplayer14** [WireMock-Net/WireMock.Net#276]
I'm using the following code

``` c#
       FluentMockServer fms = FluentMockServer.Start();
            fms.Given(Request
                    .Create()
                    .WithPath("/api/evaluator/start")
                    .UsingPost())
                .RespondWith(
                    Response.Create()
                        .WithStatusCode(202));
```

On hitting this with Postman or Fiddler I get no response. The server is started as mentioned below. I also face the same issue when I start it with Admin interface and try to access one of the admin routes.
From the Immediate Window, this is the status of the fms variable
```{WireMock.Server.FluentMockServer}
    IsStarted: true
    LogEntries: Count = 0
    Mappings: {WireMock.IMapping[1]}
    Ports: Count = 1
    Scenarios: Count = 0
    Urls: {string[1]}
```

**Comment by StefH** [comment]
After your start code, can you try to add this code?
``` c#
System.Console.WriteLine("Press any key to stop the server");
System.Console.ReadKey();
fms.Stop();
```

**Comment by codeplayer14** [comment]
I tried. Same result. I was using a while(true) loop before to block the thread. Switched it with your code. But the result is still the same.

**Comment by StefH** [comment]
Note that when you start the server like this, a random port is used.
If you want to fix the port, use:
``` c#
FluentMockServer fms = FluentMockServer.Start("http://localhost:9999");
```

**Comment by codeplayer14** [comment]
Yeah.  But that's not the issue I'm facing. I've been getting the port from fms.Ports and using it in the request. However, I don't get a response.

**Comment by StefH** [comment]
You are sending a POST request ?

(Can you also export the Postman request so that I can re-play this on my machine?)

**Comment by codeplayer14** [comment]
Yes I'm using a POST request. Attaching the Postman request.

[Wiremock.net Test.postman_collection.zip](https://github.com/WireMock-Net/WireMock.Net/files/3246465/Wiremock.net.Test.postman_collection.zip)

**Comment by StefH** [comment]
I'm using this code (tested in Linqpad):
``` c#
FluentMockServer fms = FluentMockServer.Start(9999);
	fms.Given(
		Request.Create().WithPath("/api/evaluator/start").UsingPost())
		.RespondWith(Response.Create().WithBody("hello").WithStatusCode(202)
	);
				
	Thread.Sleep(1000*1000);
	fms.Stop();
``` 
![image](https://user-images.githubusercontent.com/249938/58787227-a85c3480-85e9-11e9-90eb-76403a4fde83.png)

And Postman works fine:
![image](https://user-images.githubusercontent.com/249938/58787258-bc079b00-85e9-11e9-860b-ad744638356c.png)

**Comment by codeplayer14** [comment]
Okay. Thanks. Turns out I was missing one of the dependencies! :/
