### ISSUE TITLE
Static Mapping Not work

### ISSUE THREAD

**Issue by victorherrerocazurro** [WireMock-Net/WireMock.Net#280]
Hello, my name is Victor, I am trying to put the Wiremock.net library in a project, and I am following the documentation and the examples, but I can not make the static maps work, for example I focused on the WireMock.Net example. Console.NETCoreApp2 of the github repository, I have tried to access the resource

http: // localhost: 9091 / static / mapping

what is mapped in the file

__admin / mappings / 11111110-a633-40e8-a244-5cb80bc0ab66.json

But I returned a 404 with this content in the body

{
    "Status": "No matching mapping found"
}

You could help me, thanks.

**Comment by StefH** [comment]
I've updated the example code, please get latest.
