### ISSUE TITLE
Wiremock not compatible with Newtonsoft.Json ver 11.0.2

### ISSUE THREAD

**Issue by ashby-bowles** [WireMock-Net/WireMock.Net#281]
In our project we are using Xamarin UI tests which locks us to Newtonsoft ver 11.0.2 and we are running into an error when the MockServer is started. The exception is below. We have attempted to use an explicit reference to a newer reference of Newtonsoft but this does not help. Any guidance would be greatly appreciated.

```
WireMock.Exceptions.WireMockException : Service start failed with error: One or more errors occurred. (Could not load file or assembly 'System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.)
  ----> System.AggregateException : One or more errors occurred. (Could not load file or assembly 'System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.)
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'System.IO.Pipelines, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
```

**Comment by StefH** [comment]
Can you provide an example project ?

**Comment by ashby-bowles** [comment]
@StefH here it is. let me know if you need any more info.

[BugRepro.zip](https://github.com/WireMock-Net/WireMock.Net/files/3423824/BugRepro.zip)

**Comment by StefH** [comment]
I cannot open the iOS project on my system, can you maybe also create an android version?

**Comment by ashby-bowles** [comment]
@StefH here you go
[BugReproAndroid.zip](https://github.com/WireMock-Net/WireMock.Net/files/3426820/BugReproAndroid.zip)

Here are the repro steps: 
1. Build the solution
2. Make sure you use an up to date Android emulator (ie: Pixel 2 or similar)
3. Run the unit test

**Comment by StefH** [comment]
I'm sorry.

I cannot get Xamarin + Android working in my VM
Memory is not enough it seems, and I get an error:
```
System.Exception : ApkFile or InstalledApp has not been configured.
   at Xamarin.UITest.Configuration.AndroidAppConfiguration.Verify()
   at Xamarin.UITest.Android.AndroidApp..ctor(IAndroidAppConfiguration appConfiguration, IExecutor executor)
   at Xamarin.UITest.Configuration.AndroidAppConfigurator.StartApp(AppDataMode appDataMode)
   at XamarinUIWireMockAndroidBug.UITests.Tests.BeforeEachTest()
```

Closing this issue.

**Comment by APIWT** [comment]
What operating system are you running? Would it help if we were to provide a solution created in Windows first with a video of repro steps?

**Comment by StefH** [comment]
windows 10
vs2017 with android 27 and xamarin installed
android 8.1 oreo used


A video could help.

Questions:

- When you include WireMock.Net in the test project, which framework is chosen?
- What version from json.net can you include with no issues in your projects?

**Comment by APIWT** [comment]
So it turns out that JSON.NET might have nothing to do with the issue since the test project only includes NUnit 3 and WireMock.Net

I believe that by default .NET Framework 4.7 is chosen when making UI test projects, but I'll report back when I have a project created in your environment. Fair warning: I will probably have to use Visual Studio 2019 unless there is a community version of 2017 available for download. Hope this helps. I'll be really bummed out if the problem does not appear in Windows :(

**Comment by StefH** [comment]
Closing...
