### ISSUE TITLE
Need ability to add custom ResponseMessageTransformers

### ISSUE THREAD

**Issue by muzammilkm** [WireMock-Net/WireMock.Net#285]
Version: 1.0.19.

There is no way to add custom Response Message Transforms apart from using built in HandleBars which is also limited, I am trying generate response based on current datetime and also need to do some calculation via mapping file.  

So could you please add way to extend Response Message Transforms like wiremock does [Extending WireMock](http://wiremock.org/docs/extending-wiremock/) or if HandlebarsContext is accessible so, that we could Register custom transformation that are needed [Registering Helpers](https://github.com/rexm/Handlebars.Net#registering-helpers) ?

**Comment by StefH** [comment]
1. You are correct, extending handlebars is not yet supported, I'll take a look.

2. If you just want custom C# code, this is also possible using:
``` c#
server
                .Given(Request.Create().WithPath("/myendpoint").UsingAnyMethod())
                .RespondWith(Response.Create()
                    .WithStatusCode(500)
                    .WithBody(requestMessage =>
                    {
                       // custom code here....
                        return JsonConvert.SerializeObject(new
                        {
                            Message = "Test error"
                        });
                    })
);
```

**Comment by muzammilkm** [comment]
Yes, Right now, i am using inline style along json mapping till a new version is available.

**Comment by StefH** [comment]
Settings class will be extended with:
``` xml
public Action<IHandlebars, IFileSystemHandler> HandlebarsRegistrationCallback { get; set; }
```

Is this enough?

**Comment by muzammilkm** [comment]
Thanks that work.

**Comment by StefH** [comment]
You can try the preview version:
- WireMock.Net 1.0.21-ci-11460
- WireMock.Net.StandAlone 1.0.21-ci-11460

Also, if you think your Handlebars extension is useful for common usage, please share the code.

**Comment by muzammilkm** [comment]
Thanks you quick turn around. Sure, if some thing is generic nature, will certainly share it.

**Comment by StefH** [comment]
Also closing this one.
