### ISSUE TITLE
Allow setting root folder in LocalFileSystemHandler

### ISSUE THREAD

**Issue by muzammilkm** [WireMock-Net/WireMock.Net#288]
Exapnding LocalFileSystemHandler by taking root path for admin mapping, can help reuse LocalFileSystemHandler.

A constructor taking root path & we can set overloaded to settings.FileSystemHandler
``` c#
private readonly string _rootFolder;

LocalFileSystemHandler()
{
    rootFolder = Directory.GetCurrentDirectory();
}

LocalFileSystemHandler(string rootFolder)
{
    _rootFolder = rootFolder;
}
```
Changes in GetMappingFolder
``` c#
public string GetMappingFolder()
{
   return Path.Combine(_rootFolder, AdminMappingsFolder);
}
```

**Comment by StefH** [comment]
You can try preview:
WireMock.Net.1.0.21-ci-11468

**Comment by StefH** [comment]
BTW I see that you have added a NuGet `WireMock`, this is done because of above request ?

**Comment by muzammilkm** [comment]
> BTW I see that you have added a NuGet `WireMock`, this is done because of above request ?
No, that's not mine, but one of my colleague who published without consulting me & i would ask him to drop that package and this is not an appropriate way.

**Comment by StefH** [comment]
OK, if you can ask him to unlist the package, that would be great. Else users can be confused.

Did you have time to test latest WireMock.Net.1.0.21-ci-11468 ? Is it working for you?

**Comment by muzammilkm** [comment]
Thanks, 
Verified in (1.0.21-ci-11471)

**Comment by StefH** [comment]
Ok. Thanks. Closing this one.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/286
