### ISSUE TITLE
NullRef in 1.0.21

### ISSUE THREAD

**Issue by zidad** [WireMock-Net/WireMock.Net#295]
Upgrading my tests to WireMock 1.0.21 starting giving me a NullReferenceException, I haven't figured out why exactly:

"ClassName":"System.NullReferenceException","Message":"Object reference not set to an instance of an object.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at WireMock.ResponseBuilders.Response.ProvideResponseAsync(RequestMessage requestMessage, IFluentMockServerSettings settings) in /ResponseBuilders/Response.cs:line 419
  at WireMock.Mapping.ResponseToAsync(RequestMessage requestMessage) in /Mapping.cs:line 83
  at WireMock.Owin.WireMockMiddleware.InvokeInternal(HttpContext ctx) in /Owin/WireMockMiddleware.cs:line 121","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2147467261,"Source":"WireMock.Net","WatsonBuckets":null}

**Comment by zidad** [comment]
Looks like it could be related to this commit, probably the settings or filesystemhandler is null:

https://github.com/WireMock-Net/WireMock.Net/commit/93682c9bbffa9a1e18dac6fa06c31d396eafb9bd#diff-9c7a467190fbb513b80085bfc57d18faR421

**Comment by StefH** [comment]
Can you please provide your unit test example code?

**Comment by zidad** [comment]
Something as simple as this fails with me with 1.0.21:
```
public class FluentMockServerTest
    {
        [Fact]
        public async Task ReproduceIssue()
        {
            using (var server = FluentMockServer.Start(6003))
            {

                var assetPath = AssetHelper.GetAssetPath("content.json");

                Assert.True(System.IO.File.Exists(assetPath));

                server
                    .Given(
                        Request
                            .Create()
                            .UsingGet()
                            .WithPath("/v1/content")
                    )
                    .RespondWith(
                        Response
                            .Create()
                            .WithStatusCode(HttpStatusCode.OK)
                            .WithHeader("Content-Type", "application/json")
                            .WithBodyFromFile(assetPath)
                    );

                using (var client = HttpClientFactory.Create())
                {
                    var content = await client.GetStringAsync("http://localhost:6003/v1/content");
                }
            }
        }
    }
```

System.Net.Http.HttpRequestException : Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Rtl.Watchlist.Compatibility.Api.Test.FluentMockServerTest.ReproduceIssue() in C:\Projects\rtl\bookmark\test\component\Rtl.Watchlist.Compatibility.Api.Test\MockServerTests.cs:line 43
--- End of stack trace from previous location where exception was thrown ---

**Comment by StefH** [comment]
Thanks, I'll look into this.

**Comment by StefH** [comment]
@zidad Can you try 1.0.22 preview version from MyGet ? (https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions)

`WireMock.Net.1.0.22-ci-11507`

// btw : don't use a hard-coded port in your unit-tests

**Comment by zidad** [comment]
Hi @StefH, it works, and thanks for the tip about the ports! :)
