### ISSUE TITLE
url param - how to accept either of multiple values

### ISSUE THREAD

**Issue by gregoks** [WireMock-Net/WireMock.Net#296]
Hi,

I'm trying to create mapping to accept both of the following GET requests:

http://localhost:5566/test?abc=123
http://localhost:5566/test?abc=456

I have tried several options but none of them accept them both:

1. Set 2 mappings for both of the values: 

```
requestMatcher.WithParam("abc", MatchBehaviour.AcceptOnMatch, true, "123");
requestMatcher.WithParam("abc", MatchBehaviour.AcceptOnMatch, true, "456");
```

2. Set 1 mapping with the values as array:

`requestMatcher.WithParam("abc" , "123", "456" );`

this option will only accept requests that look like this - http://localhost:5566/test?abc=123&abc=456

-----------

Setting mapping for one of the values will work but only for that one value, so this single mapping:

`requestMatcher.WithParam("abc", MatchBehaviour.AcceptOnMatch, true, "123");`

will be able to accept request http://localhost:5566/test?abc=123

Can you please assist?

Thanks,

Greg

**Comment by StefH** [comment]
Good point.

The best option would be to use a RegexMatcher (https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching#regular-expression-matching).
However this is not supported yet by `WithParam(...)`.

I'll take a look if this can be supported.

**Comment by StefH** [comment]
As temporary solution, you could use this:

https://github.com/WireMock-Net/WireMock.Net/blob/1392119f9dc7207daf56a52d23f7034d3f3e1b57/src/WireMock.Net/RequestBuilders/IParamsRequestBuilder.cs#L108

**Comment by gregoks** [comment]
Thanks I will try!
