### ISSUE TITLE
Get Mappings models instead of just IMapping interface

### ISSUE THREAD

**Issue by gregoks** [WireMock-Net/WireMock.Net#299]
Hi,

I want to be able to serialize existing mappings andd send them as an object over http. Thats why I need the mapping model information like path, request matchers, response etc as properties, IMapping isnt enough.

Thanks!

Greg

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/298

Can you check the code changes in that PR if this is what you need.

**Comment by gregoks** [comment]
Yes exactly! Thanks!

**Comment by StefH** [comment]
Version 1.0.23 will be available on NuGet in some time.
