### ISSUE TITLE
Error thrown when calling mocked endpoint second time when using file-based response body

### ISSUE THREAD

**Issue by rwwilden** [WireMock-Net/WireMock.Net#301]
When you use a setup as follows:

    server
      .Given(
          Request
              .Create()....)
      .RespondWith(
          Response
              .Create().....
              .WithBodyFromFile(fileName));

the mocked endpoint can only be called successfully the first time. Second time it will throw an error.

This is caused by the fact that the property `BodyData.BodyAsFile` is set to `null` right after the first successful response, causing an `ArgumentNullException` the second time. This happens in the [`Response`](https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/ResponseBuilders/Response.cs#L422) class.

**Comment by StefH** [comment]
Dankjewel.
