### ISSUE TITLE
Allow Custom SSL Certification?

### ISSUE THREAD

**Issue by sangwei** [WireMock-Net/WireMock.Net#305]
When we enable ssl support, it would use a hard coded certification, which causes warnings in browsers, like "Your connection is not private" in chrome.

It would be nice to support using a custom properly signed certification.

**Comment by StefH** [comment]
See https://github.com/WireMock-Net/WireMock.Net/wiki/Using-HTTPS-(SSL)

You can use it like:
https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Settings/ProxyAndRecordSettings.cs#L24
