### ISSUE TITLE
JsonPathMatcher always convert to JArray before matching

### ISSUE THREAD

**Issue by mapjaha** [WireMock-Net/WireMock.Net#307]

**Comment by mapjaha** [comment]
I have query with this body   { "x": "42" }
To check with JsonPathMatcher if x property exist i need this pattern: "$[0].x".
According to your documentation it should be "$.x".
this is my configuration for Wiremock: 
  server
                .Given(
                    Request.Create().WithPath("/jmespath_example").UsingPost()
                        .WithBody(new JsonPathMatcher("$[0].x"))
                )
                .RespondWith(Response.Create().WithBody("Hello"));

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/311

**Comment by StefH** [comment]
I think I fixed it, can you try this WireMock.Net.1.0.26-ci-11553 from MyGet , https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by mapjaha** [comment]
Maybe yes, but as far as i can see your PR is open. 
When it will be released?

**Comment by StefH** [comment]
You can try the preview version which is available at MyGet:

WireMock.Net.1.0.26-ci-11553 from MyGet , https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by StefH** [comment]
@mapjaha Did you have time to test this?

**Comment by mapjaha** [comment]
Hi Stef,
sorry i have no time to test it. But when i do i will let you know my
feedback.

Best regards,
Maryana


niedz., 1 wrz 2019 o 11:59 Stef Heyenrath <notifications@github.com>
napisał(a):

**Comment by StefH** [comment]
@mapjaha Did you have time to test?

**Comment by mapjaha** [comment]
@StefH 
Hi Steff,
sorry for no reply so long.
I have checked changes from this PR https://github.com/WireMock-Net/WireMock.Net/pull/311 and it works.
I can confirm that changes solve my issue.

**Comment by StefH** [comment]
Thank you for testing.

A new NuGet will be released in few days.
