### ISSUE TITLE
__admin/requests - "Collection was modified" exception

### ISSUE THREAD

**Issue by gregoks** [WireMock-Net/WireMock.Net#308]
Hi,

When I accesed /__admin/requests I got the following exception:

{"Status":"{\"ClassName\":\"System.InvalidOperationException\",\"Message\":\"Collection was modified; enumeration operation may not execute.\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()\\r\\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\\r\\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\\r\\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)\\r\\n   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)\\r\\n   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)\\r\\n   at WireMock.Server.FluentMockServer.ToJson[T](T result, Boolean keepNullValues)\\r\\n   at WireMock.ResponseProviders.DynamicResponseProvider.ProvideResponseAsync(RequestMessage requestMessage, IFluentMockServerSettings settings)\\r\\n   at WireMock.Mapping.ResponseToAsync(RequestMessage requestMessage)\\r\\n   at WireMock.Owin.WireMockMiddleware.InvokeInternal(HttpContext ctx)\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2146233079,\"Source\":\"System.Private.CoreLib\",\"WatsonBuckets\":null}"}

Can you please check?

Thanks,

Greg

**Comment by StefH** [comment]
I'll take a look, probably I need to deep clone this collection when it's requested, so that you get a copy and not a reference.

**Comment by gregoks** [comment]
thanks @StefH !

**Comment by StefH** [comment]
Can you try new version from MyGet?
WireMock.Net.1.0.26-ci-11549

**Comment by gregoks** [comment]
Sure, I'll run it for few days and see if it happens again since it doesnt happen always..

**Comment by gregoks** [comment]
Havent seen this error since the fix.

**Comment by StefH** [comment]
I'll merge that PR to master and create a new NuGet.

In case this happens again, please open a new issue.
