### ISSUE TITLE
RequestLogExpirationDuration - bug

### ISSUE THREAD

**Issue by gregoks** [WireMock-Net/WireMock.Net#313]
Hi,

In OwinRequestMapper (line 55) you are setting RequestMessage.DateTime to DateTime.UtcNow:

`return new RequestMessage(urldetails, method, clientIP, body, headers, cookies) { DateTime = DateTime.UtcNow };`

Then in WireMockMiddleWare (line 175) when you are checking for expiration of that time, you are using DateTime.Now instead of DateTime.UtcNow:

 `var checkTime = DateTime.Now.AddHours(-_options.RequestLogExpirationDuration.Value);`

That's causing you invalid behavior.
Please check.

Thanks,

Greg

**Comment by StefH** [comment]
Good catch, I've fixed this with PR #314 

But you are also allowed to create a PR for other issues you find.   ;-)

**Comment by gregoks** [comment]
Thanks @StefH! Perhaps check if there are any other DateTime.Now <> DateTime.UtcNow shenanigans :)

**Comment by StefH** [comment]
I could not find any other inconsistencies.
