### ISSUE TITLE
Wiki - Proxying: AtPriority() example not set on right object

### ISSUE THREAD

**Issue by Aorimn** [WireMock-Net/WireMock.Net#315]
Hi,

On the [Proxying](https://github.com/WireMock-Net/WireMock.Net/wiki/Proxying) wiki page, the example with `AtPriority()` doesn't work out-of-the-box due to this function not being on the right object.

The first configuration is a copy/paste of the example, the second one is the fixed example:
![image](https://user-images.githubusercontent.com/1292923/62849452-f2dfe880-bcdf-11e9-8d68-b38ff92b2720.png)

**Comment by StefH** [comment]
Thanks for this notice. It's fixed.
