### ISSUE TITLE
Documentation: Add valid CLI parameters

### ISSUE THREAD

**Issue by ColinM9991** [WireMock-Net/WireMock.Net#318]
I am currently looking at using the `StandAloneApp` API with command line parameters passed in, and have had to trawl through code just to find what parameters I should pass in.

There should instead be some documentation on these parameters to describe what's valid and what the expected parameters are.

**Comment by StefH** [comment]
Yes good point. I thought I did add this to https://github.com/WireMock-Net/WireMock.Net/wiki/WireMock-as-a-standalone-process but nothing is there. I will add this.

**Comment by StefH** [comment]
Some info can be found here https://github.com/WireMock-Net/WireMock.Net-docker/wiki/Commandline-arguments however als that page needs an update.

**Comment by StefH** [comment]
Updated wiki.

**Comment by ColinM9991** [comment]
Thank you,for the quick work
