### ISSUE TITLE
Index must be within the bounds of the List - Bug

### ISSUE THREAD

**Issue by gregoks** [WireMock-Net/WireMock.Net#327]
hi,

I'm getting the following error when using the MyGet version - 1.0.27-11567

I'm using it with the following properties:

MaxRequestLogCount = 100
RequestLogExpirationDuration = 6

> HttpStatusCode set to 500 System.ArgumentOutOfRangeException: Index must be within the bounds of the List. Parameter name: index at System.Collections.Generic.List`1.Insert(Int32 index, T item) at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item) at WireMock.Util.ConcurrentObservableCollection`1.InsertItem(Int32 index, T item) at WireMock.Owin.WireMockMiddleware.LogRequest(LogEntry entry, Boolean addRequest) at WireMock.Owin.WireMockMiddleware.InvokeInternal(HttpContext ctx) at WireMock.Owin.GlobalExceptionMiddleware.InvokeInternal(HttpContext ctx)

Can you please check?

Thanks :)

Greg

**Comment by StefH** [comment]
Please try `1.0.28-ci-11744`

**Comment by gregoks** [comment]
I have tried using version 1.0.28 and its still happening, 1.0.28 was deployed later than 1.0.28-ci-11744?

**Comment by StefH** [comment]
A possible fix for your problem is only present in preview version : 1.0.28-ci-11744

**Comment by gregoks** [comment]
hi @StefH , this issue still happens in version 1.0.31-ci-11865. can you please check?

**Comment by gregoks** [comment]
hi @StefH ,

I'm using version 1.0.37 and still getting the following error:

HttpStatusCode set to 500 System.ArgumentOutOfRangeException: Index must be within the bounds of the List. Parameter name: index at System.Collections.Generic.List`1.Insert(Int32 index, T item) at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item) at WireMock.Util.ConcurrentObservableCollection`1.InsertItem(Int32 index, T item) at WireMock.Owin.WireMockMiddleware.LogRequest(LogEntry entry, Boolean addRequest) at WireMock.Owin.WireMockMiddleware.InvokeInternal(HttpContext ctx) at WireMock.Owin.GlobalExceptionMiddleware.InvokeInternal(HttpContext ctx)

this is how I start the wiremock:

 var fluentMockServer = StandAloneApp.Start(new FluentMockServerSettings
                {
                    Port = port,
                    StartAdminInterface = true,
                    StartTimeout = 5000,
                    MaxRequestLogCount = 100,
                    RequestLogExpirationDuration = 6,
                    Logger = new WireMockLogger(port)
                });

WireMockLogger is my class and I assign to an open port.

**Comment by StefH** [comment]
It maybe has to do with a lot of (fast) requests. Or maybe the logic for MaxRequestLogCount and RequestLogExpirationDuration is wrongly implemented. I need to make a sample where your settings are used and where I use HttpClient to send 100+ requests.

**Comment by gregoks** [comment]
@StefH looks ok. did the error recreated when you ran your code?

**Comment by StefH** [comment]
I had no errors when running this example code, but you can try yourself and maybe use your own logger?

**Comment by StefH** [comment]
@gregoks 
Did you have any luck solving this issue yet ?

**Comment by gregoks** [comment]
Sorry, havent got around to handle it. Im not sure it still happens though

**Comment by StefH** [comment]
Hello @gregoks 

I'm closing this issue for now. It could be that this is related to https://github.com/WireMock-Net/WireMock.Net/issues/478, so please take a look at that issue + solution.

In case you encounter this again, please raise a new issue.
