### ISSUE TITLE
Case sensitive true is ignored for JsonMatcher

### ISSUE THREAD

**Issue by viktorpeacock** [WireMock-Net/WireMock.Net#332]
The JSON matcher is doing a deep compare on JSON string and it looks like it's case sensitive. When creating a matcher, I specify CaseSensitive = false, but this is not used by the matcher. Should it be possible to configure JSON matcher to be case insensitive? 

https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Matchers/JsonMatcher.cs

**Comment by StefH** [comment]
This can be implemented, however only for strings.

**Comment by viktorpeacock** [comment]
This would help a lot. Can try doing PR myself with a bit of direction on how you'd like this to be implemented.

**Comment by StefH** [comment]
I'm looking into this.

**Comment by StefH** [comment]
And would it be required to also match the property-names CaseIgnore? Or only the string-values?

**Comment by StefH** [comment]
@viktorpeacock If you want to test this. see preview NuGet : `WireMock.Net.1.0.28-ci-11761`

**Comment by viktorpeacock** [comment]
Hi, it would help if we could ignore case on both values and property names. Potentially have two properties: IgnoreCaseOnProperties and IgnoreCaseOnPropertyValues?

**Comment by StefH** [comment]
Just a single `IgnoreCase` is easier to build and use I think.

**Comment by StefH** [comment]
Please test `WireMock.Net.1.0.28-ci-11769` , this version renames the property name + value.

**Comment by viktorpeacock** [comment]
Any chance you can post a docker image please as we host wiremock in k8s? 

Agree RE: IgnoreCase :-) Thank you so much for very fast response!

**Comment by StefH** [comment]
I can merge this logic to the master and create a new Docker because (as far I see) the original logic is still the same. 
So tonight or tomorrow I will create new Docker.

**Comment by StefH** [comment]
@viktorpeacock docker is created

**Comment by viktorpeacock** [comment]
Thank you. Will try this out today!
