### ISSUE TITLE
Where is SearchLogsFor method?

### ISSUE THREAD

**Issue by mkjeff** [WireMock-Net/WireMock.Net#34]
I saw **SearchLogsFor** sample code in the Wiki page. How can I use this feature?

This project was impressed me a lot. Thank for your work.

**Comment by StefH** [comment]
I think you mean:

the `FindLogEntries` method
or
the `POST /__admin/requests/find` admininterface call

Both can be used to find requests based on a criteria. (However I need to test and check the documentation on the wiki if all is correctly working...)

**Comment by mkjeff** [comment]
I got it. thanks

Maybe you should fix these wiki as well.
https://github.com/WireMock-Net/WireMock.Net/search?q=SearchLogsFor&type=Wikis&utf8=%E2%9C%93

**Comment by mbraint** [comment]
Hi! Can you revise this section please 
https://github.com/WireMock-Net/WireMock.Net/wiki/Stubbing#verify-interactions
There is 'SearchLogsFor' method still instead 'FindLogEntries'

**Comment by StefH** [comment]
@mbraint Thank you for noticing. I've updated wiki.
