### ISSUE TITLE
DELETE request drops the body

### ISSUE THREAD

**Issue by AlexGhiondea** [WireMock-Net/WireMock.Net#352]
It looks like for a DELETE request the body is not parsed.

I looked at the history but couldn't figure out if there was a reason why for a DELETE the body is not parsed/matched? 

I am writing tests that depend on the DELETE request sending a body and this makes it tricky to test.

The fix can be as easy as flipping this to `true`, however I am not sure what the side effects could be.
https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Util/BodyParser.cs#L36

**Comment by StefH** [comment]
I see your point.
For mocking and testing purposes, it would be better to just allow all, or make this configurable with settings.

**Comment by StefH** [comment]
I've added a `AllowBodyForAllHttpMethods` property in the settings.

Please test MyGet version:
WireMock.Net.1.0.32-ci-11945.nupkg

**Comment by StefH** [comment]
@AlexGhiondea ; did you have time to test?

**Comment by StefH** [comment]
@AlexGhiondea ; did you have time to test this preview version?

**Comment by AlexGhiondea** [comment]
Hey
 I apologize for the delay.I just saw your messages.

Thanks for adding that!

I will give it a try later today!!

Thanks,
Alex

**Comment by StefH** [comment]
@AlexGhiondea Did you have time to test this?

**Comment by StefH** [comment]
@AlexGhiondea Can you please test and report your findings?

**Comment by AlexGhiondea** [comment]
@StefH I didn’t get around to test this yet. I will give it a try at lunch today!

**Comment by AlexGhiondea** [comment]
@StefH I wasn't able to get the package from the feed, so I cloned and built locally your PR. With that, the tests that require a body for a DELETE operation work if you specify that setting!

Thanks for making the change! I will update my version once you release!!

**Comment by StefH** [comment]
Thank you for testing this. I will merge this PR to master, keep a watch on the official NuGet packages.
