### ISSUE TITLE
How to implement a request body-dependent response?

### ISSUE THREAD

**Issue by Yopt** [WireMock-Net/WireMock.Net#36]
Dear @StefH,

consider request body contains complex data (xml as plain text) in a certain known format.
I have to create corresponding mock response by parsing body and transforming it using known rules.
Is it possible to implement this logic by means of WireMock?

Regards

**Comment by StefH** [comment]
You can indeed use transformation [wiki - response-templating](https://github.com/WireMock-Net/WireMock.Net/wiki/Stubbing-and-Request-Matching#response-templating) using **handlebars**.

For example see:
https://github.com/WireMock-Net/WireMock.Net/blob/4fa295edb71e6d3f391190fb37c628872358b413/test/WireMock.Net.Tests.old/ResponseTests.cs#L42

**Comment by Yopt** [comment]
Fine, thank you
