### ISSUE TITLE
WithCallback leads to empty response

### ISSUE THREAD

**Issue by Mies75** [WireMock-Net/WireMock.Net#362]
When I use `.WithBody(@"<soapenv:Envelope ` etc. I get a response that is can be handled well by our applications.

However when we use a callback, the response message is empty :
``` c#
.WithCallback(req =>
{
	return CoverApplicationResponseBuilder.CreateResponse(req);
})
```

``` c#
public class CoverApplicationResponseBuilder
{
	public static ResponseMessage CreateResponse(RequestMessage requestSoapMessage)
	{
		//get some vars from the requestSoapMessage (excerpt)
		XDocument doc = XDocument.Parse(requestSoapMessage.Body);

		//now replace some vars in the response (also an excerpt)
		var response = new StringBuilder(ResponseMessages.CoverApplicationResponse);

		return new ResponseMessage { BodyData = new WireMock.Util.BodyData { BodyAsString = response.ToString() } };
	}
}
```

Leads to:
``` js
"Response": {
"StatusCode": 200,
"Headers": {},
"BodyDestination": null,
"Body": null,
"BodyAsJson": null,
"BodyAsBytes": null,
"BodyAsFile": null,
"BodyAsFileIsCached": null,
"BodyOriginal": null,
"BodyEncoding": null,
"DetectedBodyType": 0,
"DetectedBodyTypeFromContentType": 0
},
```

Am I doing something wrong?

Regards,

Michel

**Comment by StefH** [comment]
You need to provide `DetectedBodyType = BodyType.String`

See
https://github.com/WireMock-Net/WireMock.Net/blob/master/test/WireMock.Net.Tests/ResponseBuilders/ResponseWithCallbackTests.cs#L21

**Comment by Mies75** [comment]
Great, that works!
I also had to add:
`responseMsg.Headers.Add("Content-Type", new WireMock.Util.WireMockList<string>() { "text/xml; charset=utf-8" } );`

It seems that one has to set all message properties in the callback. Would it be possible to still take the headers and status code from `.RespondWith` instead of arranging it in the callback?

**Comment by StefH** [comment]
If you only want to manipulate the body, then you can use:

`WithBody([NotNull] Func<RequestMessage, string> bodyFactory, .....`

See example line 193 in https://github.com/WireMock-Net/WireMock.Net/blob/93682c9bbffa9a1e18dac6fa06c31d396eafb9bd/test/WireMock.Net.Tests/ResponseBuilders/ResponseWithBodyTests.cs#L189-L193

**Comment by Mies75** [comment]
Cool, that works. I rather have my transform functions return strings instead of `ResponseMessages`.
Thanks!

**Comment by StefH** [comment]
OK. Good to hear.

Closing...
