### ISSUE TITLE
Question: how Wiremock.net handle concurrent requests/responses

### ISSUE THREAD

**Issue by huchong482** [WireMock-Net/WireMock.Net#364]
Thanks a lot for this awesome tool.

Just a quick question, how does Wiremock.net handle parallel requests?
For example, is there any setting regarding the threads or concurrency when starting the wiremock server?

If I deployed the Wiremock as a standalone or IIS/Azure, how many requests usually it can handle at the same time before it becomes responsiveless….

Thanks.

**Comment by StefH** [comment]
WireMock is build for functionality, not really for speed.

However, it uses normal Owin (for net framework) and WebHostBuilder (for .NET Core), so it should be able to handle some load.
