### ISSUE TITLE
Question: Is there a way to provide a corporate proxy configuration?

### ISSUE THREAD

**Issue by Benny1007** [WireMock-Net/WireMock.Net#369]
for all other requests i'd like to just forward onto someother.server.internal but i get hit by my corporate proxy, how do I provide a corporate proxy for all other requests?

``` c#
stub.Given(
  Request
    .Create()
    .WithPath("/*")
  ).AtPriority(1000)
  .RespondWith(Response.Create().WithProxy("http://someother.server.internal/api"));
```

**Comment by StefH** [comment]
Good question. This is not yet supported. I think the best place to add this is with:
`public IResponseBuilder WithProxy(IProxyAndRecordSettings settings)`

So adding a WebProxySettings property to IProxyAndRecordSettings which supports the URL, username and password would be a good start.

**Comment by StefH** [comment]
Hello @Benny1007,
Can you please try the NuGet version WireMock.Net.1.0.36-ci-12100.nupkg from MyGet ?

**Comment by Benny1007** [comment]
Hi, how do I do that from within VisualStudio? I have ticked 'pre-release' but it doesn't show up.

**Comment by StefH** [comment]
You need to add the nuget feed. 
See https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by StefH** [comment]
Can you test this?

**Comment by StefH** [comment]
@Benny1007 Can you please test ?

**Comment by Benny1007** [comment]
Hi, sorry I thought I had responded already. Unfortunately I can't connect to the repository this test package resides in. At work we use a Nexus hosted repository that we don't have administrative control over. Any package that we as developers use has to be pulled through this corporate Nexus from nuget.org or other proxies the administrators see fit to set up.

**Comment by StefH** [comment]
OK. I've uploaded that package also to the normal nuget.org, please get this one.

**Comment by StefH** [comment]
@Benny1007 Can you test that package?

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/370
