### ISSUE TITLE
Wrong Request Match result is returning

### ISSUE THREAD

**Issue by kailashravuri** [WireMock-Net/WireMock.Net#37]
Hi - I downloaded the code and while running the ConsoleApplication Project inthe sulution with some changes i am getting some bizarre results.

In the attached sample code file - when i try to run the run application and accessing the URL from browser - like http://localhost:9091/search/query i am getting the result of path match for url "/testmatch". 

 If i register the  url "/search/query" above "/testmatch" and try to browse http://localhost:9091/search/query i am  getting the result of "/search/query" but if try "/testmatch" still getting the result of "search/query"

If i move the code up and down for registering urls, It is always returning the first one irrespective of path i am accessing from browser.

[MainApp.txt](https://github.com/WireMock-Net/WireMock.Net/files/1088825/MainApp.txt)

**Comment by phillee007** [comment]
Try removing the EnablePartialMapping line and see if that fixes it.

**Comment by StefH** [comment]
There are some errors:

1. Remove this line : `server.SetBasicAuthentication("a", "b");` // this line means that you want to protect the server with basic authemtication

2. Use `WithPath` instead of `WithUrl`


And `WithBodyAsJson` can be used more easily like:
`WithBodyAsJson(new { value = "test" }`

**Comment by kailashravuri** [comment]
Hi @StefH 
I need the authentication and i am passing user ID and password using postman. As you mentioned i removed `AllowPartialMapping` then i am getting result for "/search/query" but "No matching mapping found" for '/testpath'

**Comment by StefH** [comment]
Did you change your code to use `WithPath` ?

**Comment by kailashravuri** [comment]
@StefH yaa it looks like `WithPath` is working fine. Sorry for missing that last time. Thanks for helping me out.

**Comment by StefH** [comment]
Ok. If you have more questions or ideas, please ask.

**Comment by StefH** [comment]
Ok. If you have more questions or ideas, please ask.
