### ISSUE TITLE
Unable to build against .NET 4.5.1 because of Handlebars

### ISSUE THREAD

**Issue by thewholuver94** [WireMock-Net/WireMock.Net#377]
Hi,

I'm unable to build against 4.5.1 with the following errors:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3275: The primary reference "WireMock.Net, Version=1.0.37.0, Culture=neutral, PublicKeyToken=c8d65537854e1f03, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Handlebars, Version=1.10.1.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661" which was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.1".`

Maybe you want to update the Developer Info?

**Comment by StefH** [comment]
What happens if you use Handlebars 1.9.0 ?
