### ISSUE TITLE
StatusCode is defined as integer (string is not possible)

### ISSUE THREAD

**Issue by hsnsalhi** [WireMock-Net/WireMock.Net#380]
Hello,
I want to extract the status code from url but the mapping json is skipped because StatusCode can't be as string.
This is an example of what I want to do:

``` js
{
    "Request": {
      "Path": {
        "Matchers": [
          {
            "Name": "RegexMatcher",
            "Pattern": "/test/(\\d+)"
          }
        ]
      },
      "Methods": [
        "post"
      ]
    },
    "Response": {
      "StatusCode": "{{Regex.Match request.url \"\\d+\"}}",
      "BodyAsJson": {
        "path": "{{request.path}}"
      },
      "UseTransformer": true
    }
  }
```

**Comment by StefH** [comment]
According to HTTP specification, I think it's only allowed to use a number between 100 and 599 as status code.

**Comment by hsnsalhi** [comment]
Yes, in fact my use case respects this spec (the example was just to show what I need)
But the problem is in the string to number conversion. the Response object does not accept StatusCode to be string, neither the method WithStatusCode in C# code.

**Comment by StefH** [comment]
Correct. The reason that you cannot use a string because it should always be an integer. So what issue do you have with this?

**Comment by hsnsalhi** [comment]
In this case, is there a way to extract the status code from the url ?
example:
I send http://localhost/test/statuscode401
And the response should be with status code 401

**Comment by StefH** [comment]
If you send something like `http://localhost/test/statuscode/401`, then you can get the 401 using:
`request.PathSegments.[2]`.

However, at this moment, you cannot set this to the StatusCode because only integer is allowed.

This could be implemented with a new cast extension on Handlebars. I can investigate this.
Also allowing a the code to be converted from string to integer could be an option.
(BTW I need to check if the StatusCode is actually processed by Handlebars...)

**Comment by StefH** [comment]
BTW just posting a new mapping to the __admin is possible with a string as StatusCode:
``` js
{
    "Request": {
      "Path": {
        "Matchers": [
          {
            "Name": "RegexMatcher",
            "Pattern": "/statuscode/(\\d+)"
          }
        ]
      },
      "Methods": [
        "post"
      ]
    },
    "Response": {
      "StatusCode": "401",
      "BodyAsJson": {
        "path": "{{request.path}}"
      },
      "UseTransformer": true
    }
}
```

**Comment by hsnsalhi** [comment]
Actually it's the workaround I'm working with.
I create a mapping for every possible status code returned by the mocked API
Thank you for your help

**Comment by StefH** [comment]
@hsnsalhi 
Can you try `WireMock.Net.1.0.37-ci-12253.nupkg` from MyGet ? (https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions)

**Comment by StefH** [comment]
@hsnsalhi Can you try if this version solves your issue?

**Comment by StefH** [comment]
@hsnsalhi Can you please test if that version solves your problem?

**Comment by StefH** [comment]
@hsnsalhi Can you please test if that version solves your problem?

**Comment by StefH** [comment]
@hsnsalhi Can you please test?
