### ISSUE TITLE
Return same request body

### ISSUE THREAD

**Issue by hsnsalhi** [WireMock-Net/WireMock.Net#382]
Hello, 
In the response.body I want to return the same request.body
For that I use the transformer but it transforms quotes too.
Here is an example:

``` js
{
  "Request": {
    "Path": {
      "Matchers": [
        {
          "Name": "WildcardMatcher",
          "Pattern": "/test"
        }
      ]
    },
    "Methods": [
      "post"
    ]
  },
  "Response": {
    "StatusCode": 300,
    
    "Body": "{{request.body}}",
    "UseTransformer": true
  }
}
```

When I test with 
```
{
  "key":"value"
}
```

I get 

```
{
  &quot;key&quot;:&quot;value&quot;
}
```

**Comment by StefH** [comment]
Can you try BodyAsJson?

**Comment by hsnsalhi** [comment]
I get an exception

> Providing a Response for Mapping 'fe1a2e88-e7a2-4404-a8c9-5186b42ec731' failed. HttpStatusCode set to 500. Exception: System.ArgumentException: Object serialized to String. JObject instance expected.

**Comment by StefH** [comment]
1]
Use the triple-stash syntax: `{{{request.body}}}`   --> https://github.com/rexm/Handlebars.Net/issues/55

2]
Try new preview NuGet: `WireMock.Net.1.0.38-ci-12259.nupkg`

**Comment by StefH** [comment]
@hsnsalhi Can you try if this version solves your issue?

**Comment by StefH** [comment]
@hsnsalhi Did you time to test this one?

**Comment by StefH** [comment]
@hsnsalhi Can you please test?

**Comment by StefH** [comment]
@hsnsalhi Can you please test?

**Comment by StefH** [comment]
PR merged to master.
