### ISSUE TITLE
ExactMatcher does not accept ISO8601 DateTime?

### ISSUE THREAD

**Issue by yankeepenky** [WireMock-Net/WireMock.Net#383]
Hi, I am trying to respond to the following sample request:

[GET] http://localhost/api/update?since=2019-12-01T22:10:25.000Z

using this mapping in a json file:
``` js
{
  "Headers": { "Content-Type": "application/json" },
  "Request": {
    "Path": {
      "Matchers": [
        {
          "Name": "ExactMatcher",
          "Pattern": "/api/update"
        }
      ]
    },
    "Params": [
      {
        "Name": "since",
        "Matchers": [
          {
            "Name": "ExactMatcher",
            "Pattern": "2019-12-01T22:10:25.000Z"
          }
        ]
      }
    ],
    "Methods": [ "get" ]
  },
  "Response": {
    "StatusCode": 200,
    "Headers": { "Content-Type": "application/json" },
    "BodyAsJson": { "result": [] }
  }
}
```

I am receiving a 404 response.
The mapping does not even get registered. The otuput log says:
> [Error]: Static MappingFile : 'REST\mappings\update_1.json' could not be read. This file will be skipped.

Have you got any ideas why this won't work as expected??
thank you! (ps: great project I love it!)

**Comment by StefH** [comment]
The error message `REST\mappings\update_1.json` is a different one, not related to ExactMatcher.

When I post your mapping and test it using a GET, it works fine:
![image](https://user-images.githubusercontent.com/249938/69936200-626c2480-14d7-11ea-9045-2567b0a3963d.png)

**Comment by StefH** [comment]
@yankeepenky Do you still need support on this issue?

**Comment by yankeepenky** [comment]
sorry for my late reply!
first, the strange issue occured when using `"Matchers": [ {"Name": "...", "Pattern": "..."}]`. As soon as I changed that to "Patterns": [ "..." ] the file was read in successfully.

Now the _value of the matcher was still empty...
![matcher](https://user-images.githubusercontent.com/35534941/69963867-69b02400-1511-11ea-8c42-4c41933b6cd3.png)

---------------------------------------
Next I changed from VS2015 to VS2017 in order to check the issue there. I now receive the following exception when trying to call any path with any http method:

> xxx.Core.Exceptions.WebRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host

Environment: VS2017, targeting .NET 4.7.2 (full framework)
As soon as I fixed that issue (which does not seem to be connected to wiremock) I'll report back.

**Comment by StefH** [comment]
Just using `Pattern` should also work fine.

**Comment by yankeepenky** [comment]
@StefH I checked the issue again, now while debugging your code:

This is the json file:
`"Request": {
    "Path": {
      "Matchers": [
        {
          "Name": "ExactMatcher",
          "Pattern": "/api/update"
        }
      ]
    },
    "Params": [
      {
        "Name": "since",
        "Matchers": [
          {
            "Name": "ExactMatcher",
            "Pattern": "2019-12-01T22:10:25.000Z"
          }
        ]
      }
    ],
    "Methods": [ "get" ]
  },`

The issue is the pattern being cast to a DateTime:
Serialization\MatcherMapper.cs line 39:
`string[] stringPatterns = matcher.Patterns != null ? matcher.Patterns.OfType<string>().ToArray() : new[] { matcher.Pattern as string };`

here matcher.Pattern is a DateTime and `matcher.Pattern as string` returns null.


Serialization occurs here: Server\FluentMockServer.Admin.cs Line 232
`var mappingModels = DeserializeObjectToArray<MappingModel>(JsonConvert.DeserializeObject(value));`

**Comment by StefH** [comment]
@yankeepenky I understand your issue.
I fixed it, can you try version `WireMock.Net.1.0.40-ci-12334` from MyGet?

**Comment by yankeepenky** [comment]
@StefH Great news! all my tests succeeded! thank you for your fix...
I am waiting now for the next release - this issue was solved.
