### ISSUE TITLE
json from open api yaml

### ISSUE THREAD

**Issue by hsnsalhi** [WireMock-Net/WireMock.Net#384]
Hello,
Is there a way to create json mapping from existing yaml OpenApi ?
Thank you

**Comment by StefH** [comment]
No sorry, this is not yet possible. I had this idea before, but not yet implemented.

Maybe you can also think about this?

What needs to be done is just parsing the YML and generating an JSON with mappings.

**Comment by StefH** [comment]
A possible option could be to use https://github.com/microsoft/OpenAPI.NET to deserialize the yml to an object (OpenApiDocument) and convert that to a MappingModel object

**Comment by hsnsalhi** [comment]
How can I convert a OpenApiDocument to a MappingModel object ? is this possible with a WireMock helper or should I do it myself ?

**Comment by StefH** [comment]
I'm working on some proto type code, I keep you informed.

**Comment by hsnsalhi** [comment]
Ok thank you

**Comment by StefH** [comment]
Should this code be added to WireMock?
Or a separate commandline application, or just a NuGet with a library?

**Comment by hsnsalhi** [comment]
I think the best way is to add it as a feature in WireMock
I've started a try but this needs to be improved
````
public List<MappingModel> ConvertOpenApiDoc(OpenApiDocument document)
{
	var mappinModels = document.Paths.SelectMany(path => 
						   path.Value.Operations.SelectMany(operation => 
						   {
							   var example = operation.Value.RequestBody.Content.SelectMany(content => content.Value.Examples.Select(example => example.Value)).FirstOrDefault();
							   return operation.Value.Responses.Select(response => 
								   new MappingModel
								   {
									   Guid = Guid.NewGuid(),
									   Title = path.Key,
									   Request = new RequestModel { Methods = new[] { operation.Key.ToString() }, Path = path.Key, Body = new BodyModel { Matcher = new MatcherModel { Pattern = example.Value } } },
									   Response = new ResponseModel { StatusCode = int.Parse(response.Key), Body = null }
								   });
						   }));

	return mappinModels.ToList();
}
```

**Comment by StefH** [comment]
See this project:
https://github.com/WireMock-Net/WireMock.Net.OpenApiParser/tree/master/example/YamlDotNetConsoleApp/YamlDotNetConsoleApp

It currently supports reading a schema and creating dummy data. Or it also supports examples.

Some improvements need to be made like better dummy data for objects and more support for other types. 

But it's a start.

**Comment by StefH** [comment]
@hsnsalhi 

I started a new project : https://github.com/WireMock-Net/WireMock.Net/tree/master/src/WireMock.Net.OpenApiParser

And you can try the console-app: https://github.com/WireMock-Net/WireMock.Net/tree/master/examples/WireMock.Net.OpenApiParser.ConsoleApp

In case you need more functionality, just create an issue.
