### ISSUE TITLE
API to record stub while proxying

### ISSUE THREAD

**Issue by RajnishChhn** [WireMock-Net/WireMock.Net#394]
I have been searching for long as to how to record stubs while proxying. I understand that there is one method in which we can pass ProxyAndRecordSettings and tell the server which url needs to be proxied and recorded while starting the FluentMockServer.
Is there any admin api or any other method using which i can give a url to be proxied and recorded?
Something like (from wireMock):
POST /__admin/recordings/start
{
  "targetBaseUrl": "http://example.mocklab.io"
}
 I have looked through the wiki and couldn't find one. Please forgive me if i have overlooked  anything.

**Comment by StefH** [comment]
It's only possible to enable proxing for all requests via ProxyAndRecordSettings when starting.

Or via a single mapping:
``` js
{
    "Request": {
      "Path": {
        "Matchers": [
          {
            "Name": "WildcardMatcher",
            "Pattern": "/google"
          }
        ]
      },
      "Methods": [
        "get"
      ]
    },
    "Response": {
      "UseTransformer": false,
      "ProxyUrl": "http://www.google.com"
    }
}
```

It's not possible to enable/configure the global proxy - mode via the admin interface.

**Comment by RajnishChhn** [comment]
I have trying the mapping approach, but somehow it's not recording anything, neither is it creating a mapping file. The first approach however works fine for me.

**Comment by LevYas** [comment]
> I am trying to create a webpage where the user can give the url he/she needs to proxy and record. Any suggestion would help.

I would try to make a very simple asp net core API, which receives the URL and dynamically forms proxy settings and starts the WireMock instance.

**Comment by StefH** [comment]
@LevYas 
Solution would be like :
- make sure wiremock is running somewhere
- create a simple web-api
- this simple api takes a url and uses the WireMock.Net.RestClient (https://github.com/WireMock-Net/WireMock.Net/wiki/Admin-API-Reference) to change some mappings on the running wiremock server
