### ISSUE TITLE
WireMock Server does not appear to function correctly with Microsoft.Extensions v3.1

### ISSUE THREAD

**Issue by dalmuti509** [WireMock-Net/WireMock.Net#396]
If project nuget packages are updated to include Microsoft.Extensions v3.1 nuget libraries, the WireMock server seems to stop correctly responding to requests as all responses result in an invalid format status code 0 when responses are received from HttpClient.

Simple repro which returns 0 after an extended timeout:  
``` 
            Server.Given(
               Request.Create()
                   .WithPath($"*")
                   .UsingGet()
             )
             .RespondWith(
               Response.Create()
                 .WithStatusCode(HttpStatusCode.OK)
                 .WithBody("{}")
             );

            HttpClient client = new HttpClient();
            var result = client.GetAsync(Server.Urls.First()).Result;
            result.StatusCode.Should().Be(HttpStatusCode.OK);  //Use FluentAssertions
```
This can be run on line 14 at: WireMock.Net/examples/WireMock.Net.StandAlone.Net461/Program.cs 

Update the project to the latest nugets to see the failure.

**Comment by jlobec** [comment]
Should an "await" be used instead of ."Result" when getting the HttpClient response on this snippet? AFAIK the .Result is only correct if you're absolutely sure that the task is already completed (which I'm afraid is not the case) and could cause deadlocks
Maybe not directly related with the issue topic but will save time in the future :)

**Comment by StefH** [comment]
Could be.
Better code should be '.GetAwaiter().GetResult()' I think.

**Comment by thewholuver94** [comment]
> Could be.
> Better code should be '.GetAwaiter().GetResult()' I think.

Looks to me like best practice is using `async await` as apposed to `GetAwaiter`. Microsoft documentation indicates that `GetAwaiter` is not intended to be used in application code.

**Comment by StefH** [comment]
closing..
