### ISSUE TITLE
Question/Feature: Add support for selecting XPath in response template

### ISSUE THREAD

**Issue by kashifsoofi** [WireMock-Net/WireMock.Net#397]
Hi,
I am looking to transform soap response. And it would be good if i can use the XPath to select values from request. I believe it can be done using regex but XPath would be a natural fit for this use case.

Question: Is it already supported?

If not happy to do a PR. It would be similar to how json template work.
"{{XPath.Select request.body \"/todo-list/todo-item[1]/text()\"}}") to return text of 1st element in response.

**Comment by StefH** [comment]
This is not yet supported, this could be a valuable addition.
Suggested 2 methods:
- `XPath.SelectSingleNode`
- `XPath.SelectNodes`

I'll take a look at the code how to implement this.

**Comment by kashifsoofi** [comment]
I am happy to do a PR for this if okay.

**Comment by StefH** [comment]
You can make a PR. For reference see the https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Transformers/HandleBarsJsonPath.cs file.

Also make sure to add unit-tests for this new transformer. For reference, see https://github.com/WireMock-Net/WireMock.Net/blob/master/test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsJsonPathTests.cs
