### ISSUE TITLE
StatusCode not built correctly when loaded from mapping file.

### ISSUE THREAD

**Issue by MikeZuber** [WireMock-Net/WireMock.Net#400]
**Scenario:**
Using WireMock.Net v1.1.0.0 

All requests that match the attached mapping ([Returns500Response.txt](https://github.com/WireMock-Net/WireMock.Net/files/4041996/Returns500Response.txt)) get a response whose StatusCode is 200.

**Expectation:**
The response should have the StatusCode that is specified in the mapping file. (500)

**Analysis:**
The problem appears to be here: (WireMockServer.Admin.cs, line 811)

```
switch (responseModel.StatusCode)
{
    case int statusCodeAsInteger:
        responseBuilder = responseBuilder.WithStatusCode(statusCodeAsInteger);
        break;

    case string statusCodeAsString:
        responseBuilder = responseBuilder.WithStatusCode(statusCodeAsString);
        break;
}
```

When stepping through the code, `responseModel.StatusCode` is 500. (Which is correct.) However, according to the debugger it has been deserialized as a _long_. Because of that, it skips over the switch statement entirely and responseBuilder.ResponseMessage.StatusCode ends up being set to 200.

**Comment by StefH** [comment]
Thanks a lot for finding this issue!

**Comment by StefH** [comment]
PR was already created, merged to master.
