### ISSUE TITLE
Authentication for url called via proxy

### ISSUE THREAD

**Issue by BosNetDeveloper** [WireMock-Net/WireMock.Net#401]
This might be already answered but I couldn't find any documentation or examples

The url I call via proxy requires authentication. I have the token from auth server for this. Is there any way I can pass the token with the request header?

**Comment by StefH** [comment]
Do you have a Bearer token? You can just add this to the headers as normally.

If you really need username/password, see this article: https://github.com/WireMock-Net/WireMock.Net/wiki/Settings#proxyandrecordsettings

**Comment by BosNetDeveloper** [comment]
Thanks. I was trying to access the mock server via the browser. That wasn't working but making a rest call from my code worked just fine
