### ISSUE TITLE
Some request attributes not documented in wiki

### ISSUE THREAD

**Issue by dirvo** [WireMock-Net/WireMock.Net#410]
I noticed that some request attributes that are available for response templating (https://github.com/WireMock-Net/WireMock.Net/wiki/Response-Templating) are not documented.

The following attributes work for me (basically all the properties of the `RequestMessage` class):

- `request.method` - The HTTP method such as GET or POST.
- `request.protocol` - The scheme such as http or https.
- `request.host` - The name of the host in the URL.
- `request.origin` - The base URL of the request which is equivalent to `{Protocol}://{Host}:{Port}`.

I think it would be useful to have this added to the documentation (I couldn't find a way to create a PR for the wiki, so I created this issue instead.

**Comment by StefH** [comment]
@dirvo Thank you. I've updated WIKI.

If you find more errors or missing things, please raise an issue.
