### ISSUE TITLE
WireMock Standalone - null reference exception since settings.Logger

### ISSUE THREAD

**Issue by larsbrekken** [WireMock-Net/WireMock.Net#412]
Two observations about the documentation at 
https://github.com/WireMock-Net/WireMock.Net/wiki/WireMock-as-a-standalone-process

1. The page lists the argument `--WireMockConsoleLogger`, however the correct name is `WireMockLogger`. See https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Settings/WireMockServerSettingsParser.cs#L46-L49

2. The page also says that the default logger is `WireMockNullLogger`, however if you try not to supply a logger you get a null reference exception since `settings.Logger` remains null and a line in StandAloneApp tries to use it:
https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net.StandAlone/StandAloneApp.cs#L43

**Comment by StefH** [comment]
1. OK: updated

2. This is indeed a bug. If there is no logger, you cannot log.
What would be solution?
- only log that debug statement when a logger is present
- else  use console.writeline ?

**Comment by larsbrekken** [comment]
Thanks Stef.

For 2, if the default is `WireMockNullLogger` it seems ok not to log at all if the consumer has not specified a logger, at least that would be my expectation. So my vote would be to only log that statement when a logger is present.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/414
