### ISSUE TITLE
Is it possible to have mappings stored somewhere else?

### ISSUE THREAD

**Issue by BosNetDeveloper** [WireMock-Net/WireMock.Net#415]
Say on a network drive as opposed to mapping folder under '__admin'?

**Comment by StefH** [comment]
This is possible with custom code: create a class like https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Handlers/LocalFileSystemHandler.cs

**Comment by StefH** [comment]
@BosNetDeveloper Does this answer your question?

**Comment by StefH** [comment]
@BosNetDeveloper Closing this issue now. In case you still have a question, just reply here or open a new issue.
