### ISSUE TITLE
How to determine non-existent field(s) in cookies and headers?

### ISSUE THREAD

**Issue by qq362220083** [WireMock-Net/WireMock.Net#416]
I want to judge non-existent fields in cookie (header, param), such as "Authentication".

I found mapping files cannot implement this logic.

How to solve this problem?

thanks!

**Comment by qq362220083** [comment]
I tried to solve this problem by creating attributes on the cookie model (header & param model) object, but I found that the change exceeded my expectations, so I hope the author can help me!

**Comment by StefH** [comment]
What do you mean by **judge** ?

Do you want to match a mapping when a cookie is absent?

**Comment by qq362220083** [comment]
Yes, you're right!

i want to match a mapping when a cookie(header or param) is absent.

**Comment by StefH** [comment]
Take a look at :
https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching#reversing-the-match-behaviour-with-matchbehaviourrejectonmatch

**Comment by qq362220083** [comment]
I have seen it, but I want to use mapping files to solve it.

**Comment by StefH** [comment]
This is possible using mappings. See the updated WIKI page.

**Comment by qq362220083** [comment]
Sorry, I tested it according to the wiki and found that it still doesn't work.

take a look at:
[https://github.com/WireMock-Net/WireMock.Net/blob/83866f57192fa54125595592cc09210fbc5bbfdd/src/WireMock.Net/Matchers/Request/RequestMessageHeaderMatcher.cs#L122-L125](https://github.com/WireMock-Net/WireMock.Net/blob/83866f57192fa54125595592cc09210fbc5bbfdd/src/WireMock.Net/Matchers/Request/RequestMessageHeaderMatcher.cs#L122-L125)

**Comment by StefH** [comment]
Can you try MyGet version:
`WireMock.Net.1.1.7-ci-12734.nupkg`?

It should be used like:
``` jspn
  {
    "Guid": "f4f0be0c-089d-407c-95a2-5a90375b9382",
    "Request": {
      "Path": {
        "Matchers": [
          {
            "Name": "WildcardMatcher",
            "Pattern": "/needs-a-key",
            "IgnoreCase": true
          }
        ]
      },
      "Headers": [
        {
          "Name": "api-key",
          "Matchers": [
            {
              "Name": "WildcardMatcher",
              "Pattern": "*",
              "IgnoreCase": true
            }
          ],
          "RejectOnMatch": true
        }
      ]
    },
    "Response": {
      "StatusCode": 401,
      "BodyDestination": "SameAsSource",
      "Body": "{ \"result\": \"api-key missing\"}"
    }
  }
```

**Comment by qq362220083** [comment]
Wow, this code is great!

i want to pull request #423 to master branche

**Comment by StefH** [comment]
I will merge this code in 2days and also create new NuGet
