### ISSUE TITLE
Allow 64 bit numbers in JSON

### ISSUE THREAD

**Issue by ezarko** [WireMock-Net/WireMock.Net#425]
I noticed in testing that if I add a key to a JSON body with an integer value greater than the maxint for a 32 bit integer, then a LinqMarcher on the body will fail, even if it is not checking that field. I would guess that it is no longer parsing the body correctly.

**Comment by StefH** [comment]
Thank you for reporting. I will take a look.

**Comment by StefH** [comment]
@ezarko Can you please test `WireMock.Net.1.1.8-ci-12754.nupkg` version from MyGet (https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions)

**Comment by ezarko** [comment]
Would it be possible for you to provide a test docker image for https://github.com/WireMock-Net/WireMock.Net-docker?  Or at least a Dockerfile I could use to build the same?  I tried to spin one up myself, but it is taking me longer than I have to devote to this today.

**Comment by StefH** [comment]
I will just merge this fix into master and make a new Docker. Keep a watch on dockerhub

**Comment by ezarko** [comment]
I have verified this in 1.1.10.  Works great.  Thanks!

**Comment by StefH** [comment]
Thanks for checking.
