### ISSUE TITLE
Can't update the wiki

### ISSUE THREAD

**Issue by thewholuver94** [WireMock-Net/WireMock.Net#428]
Hey Stef, I can't seem to update the wiki anymore. Just wanted to make a couple corrections regarding the `DELETE` with body feature that we added several weeks ago.

**Comment by thewholuver94** [comment]
Hm strange. Even though I'm part of the WireMock.Net organization & have collaborator access, I still don't have the Edit / New Page buttons described [here](https://help.github.com/en/github/building-a-strong-community/adding-or-editing-wiki-pages). 

I guess you do see these buttons?

**Comment by StefH** [comment]
I've given you write permissions. Please be careful.

**Comment by thewholuver94** [comment]
Thanks that did it. I finished updating the docs so if you want to remove write permissions you can.

Nevertheless I will be careful.
