### ISSUE TITLE
Question: Random port number

### ISSUE THREAD

**Issue by raghu-romp** [WireMock-Net/WireMock.Net#432]
The MockServer for unit test says...

>let WireMock choose dynamicaly ports. It might seem common sens, avoid hard coded ports in your tests!

How does my underlying HTTP caller know which port number to connect to?

**Comment by StefH** [comment]
You can get the ports with `server.Ports` or you can get the urls `server.Urls`, example:
https://github.com/WireMock-Net/WireMock.Net/blob/master/test/WireMock.Net.Tests/WireMockServerTests.cs#L50
