### ISSUE TITLE
Handlebars helpers are not registered

### ISSUE THREAD

**Issue by LevYas** [WireMock-Net/WireMock.Net#441]
Hi! 
Thank you for the very useful project!

I tried to use a helper from the example on the wiki https://github.com/WireMock-Net/WireMock.Net/wiki/Response-Templating#handlebars-helpers :
{{capitalize request.body}}
but this gives me an error:

> Message: Template references a helper that is not registered. Could not find helper 'capitalize'

Am I missing something?

**Comment by StefH** [comment]
Sorry, these default string helpers are not available for the .NET Handlebars implementation. I've asked a question here about that: https://github.com/rexm/Handlebars.Net/issues/343

For now I did update my wiki.

**Comment by StefH** [comment]
@LevYas 
I'm building a new library which has some string and math helpers, see this project:
https://github.com/StefH/Handlebars.Net.Helpers
It's not yet integrated in WireMock.Net, but I plan to do that.

Please review and tell me if you need more helpers.

**Comment by StefH** [comment]
@LevYas Can you please review https://github.com/StefH/Handlebars.Net.Helpers and read the Wiki and tell me if you are missing some helpers?

**Comment by LevYas** [comment]
@StefH I think it would be great to have these helpers integrated into WireMock.Net! They'll give a lot of power to response templating. I think already existing there helpers will fully cover my needs and 90% of response templating needs. I would suggest you integrate it here so people could start to use it, test it, and give you feedback.

**Comment by StefH** [comment]
I've uploaded version 1.0.0 from Handlebars.Net.Helpers which is included in the this preview version from WireMock.Net : `WireMock.Net.1.2.4-ci-13218.nupkg`

**Comment by LevYas** [comment]
Works well now, thanks!
