### ISSUE TITLE
Port where WireMockServer listens to - v1.2x

### ISSUE THREAD

**Issue by paolopiaggio** [WireMock-Net/WireMock.Net#445]
Hello, since version 1.2.0 it looks like the WireMockServer starts listening on a random port instead of the one specified in the settings.

it seems the issue happens with all the different .Start overload methods.

**Comment by StefH** [comment]
Do you use .NET Framework version ? Or .NET Core ?

And can you provide the start command you use?

**Comment by StefH** [comment]
This seems a bug, I've to investigate more.

As a workaround you can provide the `url`, that works.

**Comment by paolopiaggio** [comment]
I am using .NET Core 2.2

I tried these 2 methods:

```
 WireMockServer.Start(port: {portNumber})

WireMockServer.Start(new WireMockServerSettings
{
    Port = {portNumber}
}
```

**Comment by StefH** [comment]
You can try preview NuGet : WireMock.Net.1.2.1-ci-13017

**Comment by paolopiaggio** [comment]
Hi @StefH , thanks for the prompt replies : )

I still don't see the WireMock.Net.1.2.1-ci-13017 prerelease package available.

I confirm that specifying the URL including the port does work.

**Comment by StefH** [comment]
It's on MyGet ; https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by paolopiaggio** [comment]
uh sorry...I missed that.

Yup, the issue looks fixed in here: WireMock.Net.1.2.1-ci-13017 👍

**Comment by StefH** [comment]
OK. Closing issue, a new 1.2.2 version will be uploaded to normal NuGet in some time...
