### ISSUE TITLE
Add support for .NET Standard 2.1 / .NET Core 3.1

### ISSUE THREAD

**Issue by mc0re** [WireMock-Net/WireMock.Net#447]
The biggest problem integrating WireMock with the new .NET is JSON parsers and ASP.NET - in particular, CodeAnalysis.CSharp package.

**Comment by StefH** [comment]
I can make a specific .NET Standard 2.1 package, a .NET Core 3.x is not needed in that case.

Will this solve your issue?

About JSON : I currently use NewtonSoft and I think moving to new .NET Core JSON has too many code changes.

**Comment by mc0re** [comment]
Yes it will, I suppose 😊

As a side note, people often switch to a newer .NET version starting from a certain release and never go back.

**Comment by StefH** [comment]
A preview version has been created (`WireMock.Net.1.2.2-ci-13032`) which targets netstandard2.1 , can you test?

See also https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by mc0re** [comment]
On Monday...

________________________________

**Comment by StefH** [comment]
https://github.com/oleg-shilo/cs-script.core/issues/7

**Comment by StefH** [comment]
@mc0re & @igorquintaes
Can you please try new version from MyGet : `WireMock.Net.1.2.2-ci-13091` ?

Maybe you still have to reference some library manually in your main project, I did not have time to test.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/wiki/Conflict-on-Microsoft.CodeAnalysis.CSharp

**Comment by mc0re** [comment]
Great, thanks!
