### ISSUE TITLE
Response BodyAsString loses BodyData.Encoding when UseTransformer = true

### ISSUE THREAD

**Issue by coxstl** [WireMock-Net/WireMock.Net#458]
I am mocking WCF soap messages with WireMock. I am also using Unicode encoding. When I set UseTransformer to true, I get "The encoding in the declaration 'utf-16' does not match the encoding of the document 'utf-8'." When I set the  Encoding = original.BodyData.Encoding in the ResponseMessageTransformer.TransformBodyAsString, the error goes away. Can you add that line to that file? It would help other people who still have to work with WCF projects.

**Comment by StefH** [comment]
Can you try MyGet version WireMock.Net.1.2.5-ci-13242.nupkg?

**Comment by coxstl** [comment]
That worked like a charm. Thank you.

**Comment by StefH** [comment]
Official version 1.2.6 is released
