### ISSUE TITLE
RestClient Admin API Metadata Base Path Duplication

### ISSUE THREAD

**Issue by DuncanKennedy** [WireMock-Net/WireMock.Net#464]
https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net.RestClient/IWireMockAdminApi.cs

ResetMappingsAsync method contains the base path (__admin) in its metadata attribute unlike the other methods in this interface. This causes the incorrect path to get used for example when using the interface definition with RestEase. Ex. _mockServerAdminApi = RestClient.For<IWireMockAdminApi>("http://localhost:9292/");

![image](https://user-images.githubusercontent.com/16522975/81865948-83cc4480-953c-11ea-9a57-62957570d176.png)

**Comment by StefH** [comment]
New NuGet will be released shortly

**Comment by DuncanKennedy** [comment]
Thank you

**Comment by StefH** [comment]
@DuncanKennedy Thank you for finding this, the bug has been there for some time!

And if you have more issues or ideas, please share.
