### ISSUE TITLE
Proxy mode: Unhandled exception when target is not working

### ISSUE THREAD

**Issue by LevYas** [WireMock-Net/WireMock.Net#467]
WireMock returns stack trace instead of a meaningful message, it is very misleading.
Repro: https://github.com/LevYas/WireMockNetRepro 
![2020-05-17 17_08_29-WireMockRepro (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/36070899/82152309-e6894d00-9868-11ea-85d3-52774ce1eb77.png)

It would be very nice to return a message, saying that the target is not available.

**Comment by StefH** [comment]
Preview version `WireMock.Net.1.2.10-ci-13352` on MyGet should fix this 500 error, please test.

**Comment by LevYas** [comment]
Tested. For me, it doesn't return "No such host is known.", but "No connection could be made because the target machine actively refused it.":

```
< HTTP/1.1 100 Continue
< HTTP/1.1 500 Internal Server Error
...
* HTTP error before end of send, stop sending
<
{"Status":"No connection could be made because the target machine actively refused it."}* Closing connection 0
```

Anyway, it's much better than a stack trace :D 
But I think the test in your PR might not be stable.

**Comment by StefH** [comment]
I run the tests for netcore 3.1 and I noticed a difference there, so I just check on `known`.

**Comment by LevYas** [comment]
I also used netcore 3.1, but on Windows, maybe that's the reason

**Comment by StefH** [comment]
OK, the difference is maybe that I try to connect to a non-existing hostname.
And you try to connect to localhost (which exists) but nothing listens at port 5000.

**Comment by LevYas** [comment]
Ah, sure, you are right.

**Comment by StefH** [comment]
I'll merge to master. New NuGet will be released soon.
