### ISSUE TITLE
Proxy mode: Incorrect handling of multipart requests

### ISSUE THREAD

**Issue by LevYas** [WireMock-Net/WireMock.Net#468]
I have an ASP.Net Core API method with the following signature
```
[HttpPut("pic")]
public ActionResult UpdatePicture(IFormFile file)
```
I call this method from Postman or curl or from my front-end with a small picture file. It's ok without proxy, but with proxy file is always null.

It looks like WireMock.Net treats multipart requests as a single part request with raw data, but I can be wrong. I added reading the `Form` field and it contains the right content:
![2020-05-17 14_34_07-WireMock Net Solution (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/36070899/82152438-ce65fd80-9869-11ea-9d01-d424a876d2f5.png)

I created a repro here https://github.com/LevYas/WireMockNetRepro

**Comment by StefH** [comment]
Bug is confirmed, thanks for analyzing.

However fixing will take some time...

**Comment by LevYas** [comment]
You are welcome. Yeah, fix will not be trivial, especially bearing in mind different target frameworks.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/473

**Comment by StefH** [comment]
@LevYas Can you try version `WireMock.Net.1.2.11-ci-13392` ?

**Comment by LevYas** [comment]
@StefH  - you are incredibly fast. I've just tested - it works!

**Comment by StefH** [comment]
You are a very good tester!

I will make new official version today.
