### ISSUE TITLE
Stateful support

### ISSUE THREAD

**Issue by deeptowncitizen** [WireMock-Net/WireMock.Net#48]
Is there a plan to support [stateful behavior](http://wiremock.org/docs/stateful-behaviour/) functionality?

**Comment by StefH** [comment]
No plans, until your question ;-)

I'll take a look at the idea and check if this can be implemented in WireMock.net

**Comment by deeptowncitizen** [comment]
I have implemented this functionality for in-process solution. but I can't create PR as have no permissions.
Could you give me permissions to push a new branch?

**Comment by deeptowncitizen** [comment]
Mostly the idea is simply to add such syntax:

> _server
>                 .Given(Request.Create()
>                     .WithPath("/foo")
>                     .UsingGet())
>                 .WillSetStateTo("Test state")
>                 .RespondWith(Response.Create()
>                     .WithStatusCode(200)
>                     .WithBody(@"No state msg"));

>             _server
>                 .Given(Request.Create()
>                     .WithPath("/foo")
>                     .UsingGet())
>                 .WhenStateIs("Test state")
>                 .RespondWith(Response.Create()
>                     .WithStatusCode(200)
>                     .WithBody(@"Test state msg"));

**Comment by StefH** [comment]
What you can do is fork this project, and then build your changes there and then make a PR to this project. Or what you also can do, is zip your changes and provide this code to me.

**Comment by deeptowncitizen** [comment]
Created a PR #49

**Comment by StefH** [comment]
I see, currently reviewing and testing.

**Comment by deeptowncitizen** [comment]
had to add 1 update: in case the next state is not specified - the current will not be changed (will not be set to NULL)

**Comment by StefH** [comment]
I will look, however I'm also looking to build in support for multiple states or scenarios.

**Comment by deeptowncitizen** [comment]
> multiple states
what do you mean by multiple states? do you have any examples?

> scenarios
are you talking about something similar to `inScenario("To do list")`?
Do you  want to keep backward compatibility?

**Comment by StefH** [comment]
Multiple states : Be able to define multiple states which will behave.

Scenarios : I think I like the original idea from wiremock.org I'm building the code based on your PR.

**Comment by deeptowncitizen** [comment]
> Multiple states : Be able to define multiple states which will behave.

I see. something like `WhenState(params object[] states)`?

>  I think I like the original idea from wiremock.org
do you plan to keep backward compatibility?

**Comment by deeptowncitizen** [comment]
in case you decided what is the expected semantic and contract I can update PR

**Comment by StefH** [comment]
Thanks for the offer, but currently I'm trying to build it according to my idea, I'll let you know if I need help.

Multiple states means ; multiple parallel states should be supported, like unit-test as defined below should be fine:

```c#
        [Fact]
        public async Task Should_process_request_if_equals_state_and_multiple_state_defined()
        {
            // given
            _server = FluentMockServer.Start();

            _server
                .Given(Request.Create()
                    .WithPath("/state1")
                    .UsingGet())
                .InScenario("s1")
                .WillSetStateTo("Test state 1")
                .RespondWith(Response.Create()
                    .WithBody("No state msg 1"));

            _server
                .Given(Request.Create()
                    .WithPath("/foo")
                    .UsingGet())
                .InScenario("s1")
                .WhenStateIs("Test state 1")
                .RespondWith(Response.Create()
                    .WithBody("Test state msg 1"));

            _server
                .Given(Request.Create()
                    .WithPath("/state2")
                    .UsingGet())
                .InScenario("s2")
                .WillSetStateTo("Test state 2")
                .RespondWith(Response.Create()
                    .WithBody("No state msg 2"));

            _server
                .Given(Request.Create()
                    .WithPath("/foo")
                    .UsingGet())
                .InScenario("s2")
                .WhenStateIs("Test state 2")
                .RespondWith(Response.Create()
                    .WithBody("Test state msg 2"));

            // when
            string url = "http://localhost:" + _server.Ports[0];
            var responseNoState1 = await new HttpClient().GetStringAsync(url + "/state1");
            var responseNoState2 = await new HttpClient().GetStringAsync(url + "/state2");

            var responseWithState1 = await new HttpClient().GetStringAsync(url + "/foo");
            var responseWithState2 = await new HttpClient().GetStringAsync(url + "/foo");

            // then
            Check.That(responseNoState1).Equals("No state msg 1");
            Check.That(responseWithState1).Equals("Test state msg 1");

            Check.That(responseNoState2).Equals("No state msg 2");
            Check.That(responseWithState2).Equals("Test state msg 2");
        }
```

**Comment by deeptowncitizen** [comment]
looks good. will use this syntax meanwhile.
thank you

**Comment by StefH** [comment]
See my code at https://github.com/WireMock-Net/WireMock.Net/tree/stateful-behavior

I'll extend this code to also support the JSON for this...

**Comment by StefH** [comment]
Code merged to master, still need to add some text to wiki...

**Comment by StefH** [comment]
WIKI --> https://github.com/WireMock-Net/WireMock.Net/wiki/Scenarios-and-States

**Comment by deeptowncitizen** [comment]
looks great!
do you have any plans to update the package on nuget.org?

**Comment by StefH** [comment]
Yes, I think I can release version **1.0.2.4** on NuGet. I keep you informed here when.

**Comment by StefH** [comment]
Done

**Comment by deeptowncitizen** [comment]
thanks a lot!
