### ISSUE TITLE
Fail after half of the body has been sent

### ISSUE THREAD

**Issue by drauch** [WireMock-Net/WireMock.Net#480]
Hi!

We want to simulate in a test that sending the response fails after half of the body has already been sent to the client. The best we could come up with has been:

_server.Given(Request.Create().UsingGet())
  .RespondWith(Response.Create().WithStatusCode(HttpStatusCode.OK).WithBody(rm => throw new Exception()));
However, this already returns InternalServerError instead of OK to the client. That's not what we want.

How to properly return OK and then fail after a few bytes of the body have been sent?

Best regards,

D.R.

**Comment by StefH** [comment]
It's not really possible yet to read half of data and return an error.

What you can do is use Faults?
https://github.com/WireMock-Net/WireMock.Net/wiki/Faults

**Comment by drauch** [comment]
Thanks, that should hopefully work for me. Will report back if I run into troubles.
