### ISSUE TITLE
Unexpected behavior on multiple params matching

### ISSUE THREAD

**Issue by aslezak** [WireMock-Net/WireMock.Net#488]
What is the expected purpose of 
```csharp
MockService
  .Given(Request.Create()
    .UsingGet()
    .WithPath($"/path*")
    .WithParam("limit", "1", "0", "2"))
  .RespondWith(Response.Create().WithCallback(request => GetData(limit)));
```

I expected that this setup would match on any of the provided values, but it rejects all of the requests with any of those values?
I know I can get this to match by providing linq or c# matcher as alternative, but just wanted to clarify purpose of the params?
Cheers

**Comment by StefH** [comment]
Hello @aslezak,

The current intended behaviour from this logic is that you define that the `limit` parameter should be defined 3 times and have the values `0`, `1` and `2`. So it's basically an **AND**.

See this unit test which should explain it:
https://github.com/WireMock-Net/WireMock.Net/blob/d971144426bbf1761dcc4c24da5e3d9870267dd5/test/WireMock.Net.Tests/RequestTests.cs#L126

If you want to match on `0` or `1` or`2`, the best solution is to use a RegexMatcher.
So
``` c#
.WithParam("limit", new RegexMatcher("^[012]$")
```

**Comment by StefH** [comment]
A structural change could be to add another parameter which defines if the match result should be calculated using an *AND* or an *OR*. I'll think about this....

**Comment by aslezak** [comment]
Thanks for the unit test and regex idea.
One thing I am curious about is in what cases does one want in url to have query param multiple times with different values. I know that some languages process multiple query string  keys differently. PHP takes only the first one unless it is array, c# does array and so on.

ps. if match operator option is something that can be done, happy to make a PR for it.
Cheers

**Comment by StefH** [comment]
Multiple times the same param or single param with multiple values is the same.

So
?limit=1,2

Is same as
?limit=1&limit=2


You can try to make PR however this involves a lot if API changes and internal changes.

**Comment by aslezak** [comment]
Thanks for the head up, haven't looked much into internals yet.

**Comment by StefH** [comment]
I'll keep this open for now and see if I can add this somewhere in the documentation.
And I'll check the changes needed.
