### ISSUE TITLE
System.TypeLoadException: Could not load type 'RandomDataGenerator.FieldOptions.FieldOptionsBytes

### ISSUE THREAD

**Issue by rangerranger** [WireMock-Net/WireMock.Net#502]
Trying to integrate Wiremock into a larger project. I have tackled most of the needed packages / dependencies. But I'm currently blocked on this error: 
```
WireMock.Exceptions.WireMockException: Service start failed with error: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.TypeLoadException: Could not load type 'RandomDataGenerator.FieldOptions.FieldOptionsBytes' from assembly 'RandomDataGenerator, Version=1.0.9.0, Culture=neutral, PublicKeyToken=ae5c571d29a3b8d9'.
```
I have the RandomDataGenerator.Net package installed and reference it in the csproj. I have the Fare package installled and also reference in csproj (not sure if this is necessary, but read on the RandomDataGenerator.Net wiki that Fare is one of the dependencies).

Any help would be great!

**Comment by StefH** [comment]
Hello @rangerranger ,

Can you please provide some more details on the .NET version you use, and if it's possible also post the mapping or the c# code you use?

**Comment by StefH** [comment]
Hello @rangerranger, can you please answer my question and provide some more details?

**Comment by StefH** [comment]
Hello @rangerranger, can you please answer my question and provide some more details?

**Comment by rangerranger** [comment]
Apologies, couldn't get back to it due to both work and personal reasons. I
will retry the work in that repo - they are planning to update to NetCore
3.x.

**Comment by StefH** [comment]
Hello @rangerranger , did you have time to verify?

**Comment by StefH** [comment]
Hello @rangerranger , did you have time to verify?

Else I'll close this issue within some days.
