### ISSUE TITLE
WireMock WebApplication example doesn't run on Net Core 3.1

### ISSUE THREAD

**Issue by tomatualus** [WireMock-Net/WireMock.Net#511]
### Describe the bug
When i change the Net Core versions in the [https://github.com/WireMock-Net/WireMock.Net/tree/master/examples/WireMock.Net.WebApplication](WebApplication example), i a Service Unavailable error message on the website and that's all.

### Expected behavior:
Changing to Net Core 3.1 version should not produce any errors, or if it does, please make a working example.

**Comment by tomatualus** [comment]
Well, somehow i got it going. I have no idea what did i do, but the last thing i did was in web.config change hostingModel value to "outofprocess"

**Comment by StefH** [comment]
Hello @tomatualus,
I did add a new Net Core 3.1 project (https://github.com/WireMock-Net/WireMock.Net/tree/master/examples/WireMock.Net.WebApplication.NETCore3) which seems to run fine, except that I cannot get the logging to work. Maybe you have an idea?

**Comment by tomatualus** [comment]
Logger in `WireMockService` must be a `ILogger<WireMockService>`

And in ConfigureServices you must call `serviceCollection.AddLogging(x => x.AddConsole());` for it to be added to DI setup. Hope that works.
