### ISSUE TITLE
Static mapping break from 1.2.17 to 1.2.18 and higher

### ISSUE THREAD

**Issue by henriquemotaesteves** [WireMock-Net/WireMock.Net#513]
### Describe the bug
A static mapping that works fine in version 1.2.17 stops working if the version is upgraded to version 1.2.18 or higher.

### Expected behavior:
A success status is expected but we got a not found.

### Test to reproduce
https://github.com/henriquemotaesteves/playground/tree/csharp/wiremock/1.2.17
https://github.com/henriquemotaesteves/playground/tree/csharp/wiremock/1.2.18

**Comment by StefH** [comment]
@henriquemotaesteves, thank you very much for researching this bug. I'll take a look why this fails.

**Comment by StefH** [comment]
@henriquemotaesteves 
I think this issue is being fixed in PR https://github.com/WireMock-Net/WireMock.Net/pull/505

If you have time, can you please use `WireMock.Net.1.2.18-ci-13754.nupkg`?

**Comment by henriquemotaesteves** [comment]
@StefH, this version fixed the problem.

https://github.com/henriquemotaesteves/playground/tree/csharp/wiremock/1.2.18-ci-13754

**Comment by StefH** [comment]
@henriquemotaesteves Thanks for testing. I'll release a new version tonight.
