### ISSUE TITLE
HTTP 431 when header size over 32KB

### ISSUE THREAD

**Issue by eduherminio** [WireMock-Net/WireMock.Net#519]
I'm getting HTTP 431 status codes when making requests to a `sheyenrath/wiremock.net` image with headers over 32KB.

I assumed that the issue was [KestrelServerLimits.MaxRequestHeadersTotalSize](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.maxrequestheaderstotalsize?view=aspnetcore-3.1#Microsoft_AspNetCore_Server_Kestrel_Core_KestrelServerLimits_MaxRequestHeadersTotalSize), but I'm failing to prove it.

I've created a local `wiremock.net` image with `StandAlone.NETCoreApp` using a local `WireMock.Net`  package where I'm setting `options.Limits.MaxRequestHeadersTotalSize  = 150_000;` in both [.NET Standard1.3](https://github.com/WireMock-Net/WireMock.Net/blob/432fb54abae42b0257a3ee5b5c46e8ac6f62e481/src/WireMock.Net/Owin/AspNetCoreSelfHost.NETStandard13.cs#L18) and [.NET Standard > 1.3](https://github.com/WireMock-Net/WireMock.Net/blob/432fb54abae42b0257a3ee5b5c46e8ac6f62e481/src/WireMock.Net/Owin/AspNetCoreSelfHost.NETStandard.cs#L17), but I'm still getting those 431s.

Am I missing something? Any other idea of what could be causing those 431s?

**Comment by StefH** [comment]
Hello @eduherminio, does the same issue occur when you just run the StandAlone.NETCoreApp locally, so without docker?

**Comment by eduherminio** [comment]
Yes it does @StefH.

**Comment by StefH** [comment]
And you use a .NET Core 3.1 ?

**Comment by eduherminio** [comment]
My bad, I messed up the package versions. Modifying `MaxRequestHeadersTotalSize` does seem to fix the issue. Thanks!
I'll follow up with a separated issue/feature request to discuss the possibility of having it modified or allowing its modification, if that's OK with you.
