### ISSUE TITLE
Make Kestrel limits configurable

### ISSUE THREAD

**Issue by eduherminio** [WireMock-Net/WireMock.Net#521]
**Is your feature request related to a problem? Please describe.**
Increase `KestrelServerLimits.MaxRequestHeadersTotalSize` (and potentially other limits, i.e. `KestrelServerLimits.Http2.MaxRequestHeaderFieldSize`). See #519 

**Describe the solution you'd like**
Make Kestrel limits configurable.
See this draft PR of a possible implementation for `USE_ASPNETCORE &&  .NET Standard > 1.3`
https://github.com/WireMock-Net/WireMock.Net/pull/520

**Describe alternatives you've considered**
Ask for a manual increase of `KestrelServerLimits.MaxRequestHeadersTotalSize` (to `int.MaxValue`? to something else?)

**Comment by StefH** [comment]
PR is merged.
