### ISSUE TITLE
How to make Request mapping match only when it is a perfect match?

### ISSUE THREAD

**Issue by tomatualus** [WireMock-Net/WireMock.Net#526]
Hello.

Lets say i have two request mappings. The `XPathMatchers` are simplified.

Request 1 has body **matchers** `XPathMatcher` for Value1 = 1 **AND** `XPathMatcher` for Value2 = 2.
Request 2 has a body **matcher** `XPathMatcher` for Value1 = 1.

How do i return the Request 1's response, when its matchers are a perfect fit, but return Request 2, when Value2 != 2?

Thanks in advance.

**Comment by StefH** [comment]
Hello @tomatualus,

1. The current logic from WireMock.Net is that in case two mappings are a perfect fit, the one with the most matches is preferred.

2. Your second scenario _return Request 2, when Value2 != 2_ , I'm not completely sure that can be done right now. But I would would expect it to work correct, that is : return Request 2 because Request 1 does only only match for 50%.

**Comment by tomatualus** [comment]
I will post my class setup down below. You can see that it doesn't work as expected, even though online XPath tools show that one of XPathMatchers should fail. Both of them return `Failed but no delay`

    private static WireMockServer stub;
    private static string baseUrl;

    [ClassInitialize]
    public static void PrepareClass(TestContext context)
    {
        if (context is null) { throw new ArgumentNullException(nameof(context)); }

        var config = new ConfigReader();
        var port = 5069;
        baseUrl = "http://localhost:" + port;

        stub = WireMockServer.Start(new WireMockServerSettings
        {
            Urls = new[] { "http://+:" + port },
            ReadStaticMappings = true,
            FileSystemHandler = new CustomFileSystemHandler(config.WireMockMappingPath),
            WatchStaticMappings = true,
            WatchStaticMappingsInSubdirectories = true,
        });
    }

    [ClassCleanup]
    public static void TearDown()
    {
        stub.Stop();
    }

    [TestMethod]
    public void Tesat123123()

    {

        stub.Given(
            Request.Create()
                .WithPath("/test1")
                .WithBody(new IMatcher[]
                {
                    new XPathMatcher("string(//*[name()='IndividualName']/*[name()='FirstForename']) = 'Failed'"),
                    new XPathMatcher("string(//*[name()='IndividualName']/*[name()='Surname']) != 'Delay'"),
                }))
            .RespondWith(
                Response.Create()
                .WithStatusCode(200)
                .WithBody("Failed but no delay")
            );

        stub.Given(
            Request.Create()
                .WithPath("/test1")
                .UsingPost()
                .WithBody(new List<XPathMatcher>
                {
                    new XPathMatcher("string(//*[name()='IndividualName']/*[name()='FirstForename']) = 'Failed'"),
                    new XPathMatcher("string(//*[name()='IndividualName']/*[name()='Surname']) = 'Delay'"),
                }))
            .RespondWith(
                Response.Create()
                .WithStatusCode(200)
                .WithBody("Failed and delay")
            );

        var client = new RestSharp.RestClient($"{baseUrl}/test1");
        var request1 = new RestRequest(Method.POST);
        request1.AddParameter(
            "text/xml",
            "<IndividualName><FirstForename>Failed</FirstForename><Surname>Delay</Surname></IndividualName>",
            ParameterType.RequestBody);

        var request2 = new RestRequest(Method.POST);
        request2.AddParameter(
            "text/xml",
            "<IndividualName><FirstForename>Failed</FirstForename><Surname>NotDelay</Surname></IndividualName>",
            ParameterType.RequestBody);

        var response1 = client.Execute(request1).Content;
        var response2 = client.Execute(request2).Content;
    }

**Comment by tomatualus** [comment]
Just discovered the fix......

It seems like i can pass many strings into `XPathMatcher`.. So when consolidated both XPathMatchers into one, it now works.

But the question remains - why does the upper test not work?

And how can define a single `XPathMatcher` in a JSON mapping, where it checks for two or more conditions to match?

**Comment by StefH** [comment]
Maybe you need to use `not` instead of `!=` for strings?

https://stackoverflow.com/questions/3418470/using-not-in-xpath
