### ISSUE TITLE
Fluent API for RequestMessagePathMatcher with IgnoreCase flag

### ISSUE THREAD

**Issue by aslezak** [WireMock-Net/WireMock.Net#527]
While writing tests with out of bounds client libraries I ran into an issue of the requests not matching due to being case sensitive. I know it is possible to configure this via JSON for the server. But I have not found a way to do that in fluent api:
Example:
```csharp
MockService.Given(Request.Create().WithPath("/somePath").UsingGet()).RespondWith(Response.Create().WithStatusCode(HttpStatusCode.OK));
```
This will not match a request  to `.../somepath`

Current workaround for this involves using a bit more code:
```csharp
MockService.Given(Request.Create()
                         .WithPath(path => path.Equals($"/somePath", StringComparison.InvariantCultureIgnoreCase))
                         .UsingGet())
           .RespondWith(Response.Create().WithStatusCode(HttpStatusCode.OK));
```

Solution would be to add behavior modification flag in the `IRequestBuilder WithPath([NotNull] params string[] paths);` as `bool` parameter `IgnoreCase` or alternatively `StringComparison` enum parameter.

If this would be an acceptable solution I can provide a PR for this feature.
Thanks!

**Comment by StefH** [comment]
Hello @aslezak,

As workaround you can use:
``` c#
.WithPath(new WildcardMatcher("/somePath", true))
```

Would that be good enough for you?

**Comment by aslezak** [comment]
Ah, yes, didn't spot that overload, 
That'll do, thanks!
