### ISSUE TITLE
Can I use this library to make integration tests with an external soap service? 

### ISSUE THREAD

**Issue by jfbenavid** [WireMock-Net/WireMock.Net#532]
I want to build a test to use the reference of a soap service using Wiremock to get the response of that.

Is it possible?

Thanks in advance.

**Comment by StefH** [comment]
Hello @jfbenavid, this is not yet possible. There is functionality for parsing an OpenApi spec (https://github.com/WireMock-Net/WireMock.Net/tree/master/src/WireMock.Net.OpenApiParser).

Maybe a WCF/Soap parser would be usefull.

For now the best solution for you is to run WireMock.Net in proxy mode and just capture the requests/response or manually add the mappings.
