### ISSUE TITLE
Stubbed response with only callback returns unexpected status code.

### ISSUE THREAD

**Issue by rudi-brunner** [WireMock-Net/WireMock.Net#533]
### Describe the bug
When setting up a stubbed response with only a callback I would expect that the status code which I set on the returned `ResponseMessage` would be the status code which the request will receive. But you always get `HttpStatusCode.OK` anyway.

### Expected behavior:
If I only specify `.WithCallback()` and not `.WithStatusCode()` I would expect that the status code of the returned `ResponseMessage` object is returned.

### Test to reproduce
This test is currently failing with WireMock.Net 1.3.5
``` c#
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using NUnit.Framework;
using WireMock;
using WireMock.RequestBuilders;
using WireMock.ResponseBuilders;
using WireMock.Server;

namespace WireMockIssue
{
    [TestFixture]
    public class StatusCodeStubIssue
    {
        private WireMockServer _mockServer;

        [SetUp]
        public void Setup()
        {
            _mockServer = WireMockServer.Start(8088);
            _mockServer
                .Given(Request.Create().WithPath("/foo"))
                .RespondWith(Response.Create()
                    .WithCallback(request => new ResponseMessage {StatusCode = HttpStatusCode.Conflict}));
        }

        [TearDown]
        public void TearDown()
        {
            _mockServer.Dispose();
        }

        [Test]
        public async Task TestToGetHttpConflictStatus()
        {
            using var httpClient = new HttpClient();
            var response = await httpClient.PostAsync("http://localhost:8088/foo", new StringContent("dummy"));
            Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Conflict));
        }
    }
}
```

It fails with:
```
WireMockIssue.StatusCodeStubIssue.TestToGetHttpConflictStatus

  Expected: Conflict
  But was:  OK
```

### Other related info
I checked in the debugger that the callback was triggered. It was triggered.

**Comment by StefH** [comment]
Hello @rudi-brunner, thank you for finding this bug. I'll take a look.

**Comment by StefH** [comment]
The issue is that you use an Enum, if you use `new ResponseMessage {StatusCode = (int) HttpStatusCode.Conflict}));` it should work.

However, I'll make a fix in the code.

**Comment by StefH** [comment]
@rudi-brunner can you try preview version `WireMock.Net.1.3.5-ci-13952.nupkg` (from MyGet)?

**Comment by rudi-brunner** [comment]
Thanks for the quick response :)
I'm not familiar with MyGet. Is it myget.org? Created an account now. But how do I access your feed? Any URL I can use?

**Comment by StefH** [comment]
See https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by rudi-brunner** [comment]
Works like a charm 🥇 
Verified that it works both in the minimum test case which I posted here and in my full-blown test setup.
Good to go 👌
