### ISSUE TITLE
Proxy for AWS: Error unmarshalling response back from AWS

### ISSUE THREAD

**Issue by deeptowncitizen** [WireMock-Net/WireMock.Net#54]
Proxying requests to AWS DynamoDb with no specific configuration (for any request proxy to DynamoDb).
Getting an error `Error unmarshalling response back from AWS`

Tried the same with original Wiremock proxy - works correctly.

**Comment by StefH** [comment]
Hello @deeptowncitizen,

Can you please provide the mapping (in code or in JSON) that you are defining?

And if possible also the request / client code.

**Comment by deeptowncitizen** [comment]
#55 contains the fix the problem.
PR contains steps to reproduce the problem.
There is no mapping (it is proxy all requests)

```
var dynamoDb = new DynamoDb(8081);
var mock = FluentMockServer.Start(8082);
mock
    .Given(Request.Create()
        .UsingAnyVerb())
    .RespondWith(Response.Create()
        .WithProxy("http://localhost:8081/"));
```
And then simply create any Dynamodb request to the proxy

**Comment by StefH** [comment]
1] Thanks for fixing.

2] Do you also need a new NuGet?

**Comment by deeptowncitizen** [comment]
do you have any plans when you will release a new version?

**Comment by StefH** [comment]
Within a few hours. I keep you updated.

**Comment by StefH** [comment]
NuGets updated.

**Comment by deeptowncitizen** [comment]
thank you
