### ISSUE TITLE
Question about couple server methods.

### ISSUE THREAD

**Issue by tomatualus** [WireMock-Net/WireMock.Net#540]
Hey. I would love to know what do some of the `WireMockServer` methods do. Also would be nice to add this info to the wiki. :)

AddCatchAllMapping
ReadStaticMappings - Does this force the server to read all the mappings? When does the server read the mappings otherwise, if not called?
ReadStaticMappingAndAddOrUpdate - Add or update what? Mappings?
WithMapping (string mappings overload) - JObject serialized or what is this supposed to be?
WithMapping (params MappingModel[] mapings overload) - I guess i can register new mappings with this?

Thanks in advance, really love your work.

**Comment by StefH** [comment]
Hello @tomatualus 
I did add some more comments in https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net.Abstractions/Server/IWireMockServer.cs

Please take a look.

**Comment by tomatualus** [comment]
Thanks for the reply, @StefH !
All of the things got a lot clearer now. Is AddCatchAllMapping called by default? Because that's the thing i always see, but don't remember every calling .AddCatchAllMapping.

**Comment by StefH** [comment]
The `AddCatchAllMapping` is a method which you can use (however actually I forgot why I added this method)

The 404 you see, is created in a different part --> that's the default error when a mapping is not found.
