### ISSUE TITLE
Should there be a .NET 5.0 target now?

### ISSUE THREAD

**Issue by gitfool** [WireMock-Net/WireMock.Net#541]
After porting projects to .NET 5.0, unit and integration tests using WireMock.Net seem to work fine, apart from logging "WireMock.Net server using .NET Core 3.1". Not sure when it's needed but I noticed there are a lot of target frameworks for some reason:
* [WireMock.Net](https://github.com/WireMock-Net/WireMock.Net/blob/4fb455a1b14a01272230eb53a1b263b56a1513f8/src/WireMock.Net/WireMock.Net.csproj#L6)
* [WireMock.Net.StandAlone](https://github.com/WireMock-Net/WireMock.Net/blob/4fb455a1b14a01272230eb53a1b263b56a1513f8/src/WireMock.Net.StandAlone/WireMock.Net.StandAlone.csproj#L6)

Specify:
```xml
<TargetFrameworks>net451;net452;net46;net461;netstandard1.3;netstandard2.0;netstandard2.1;netcoreapp3.1</TargetFrameworks>
```
Also, some of those are now well out of support and so could possibly be dropped?

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/543

**Comment by StefH** [comment]
Hello @gitfool,

- Can you explain this: `WireMock.Net seem to work fine, apart from logging` ?
- Some frameworks are indeed out of support, however for now I keep these. Probably next year I will remove some.

**Comment by gitfool** [comment]
@StefH the logging comes from the hard wired log message determined by target framework at compile time ([AspNetCoreSelfHost .RunHost](https://github.com/WireMock-Net/WireMock.Net/blob/d1afba5058a54507a74895b92698322d5156d324/src/WireMock.Net/Owin/AspNetCoreSelfHost.cs#L124)), which you address in [PR 543](https://github.com/WireMock-Net/WireMock.Net/pull/543/files#diff-4f9c8c8a5529247bfcc3890887411b2e5f33f0f8bd2710cad741c0b52abb53a7R126) along with a few other tweaks that make me think a new release with `net5.0` target framework is advisable.

**Comment by StefH** [comment]
OK.
PR is merged
