### ISSUE TITLE
WireMock Setting 'SaveMappingToFile' raising cast object to type error

### ISSUE THREAD

**Issue by jmontalto01** [WireMock-Net/WireMock.Net#559]
### Describe the bug
I am using wiremock docker compose example with ProxyAndRecordSettings (command "--ProxyURL" ) and setting "--SaveMappingToFile", "true". It raises the following error when browsing to http://localhost:9091/__admin/mappings
 
{"Status":"Unable to cast object of type 'WireMock.ResponseProviders.DynamicResponseProvider' to type 'WireMock.ResponseBuilders.Response'."}

### Expected behavior:
Load mapping files

### Test to reproduce
Docker Compose file:

version: "3.8"

services:
  wiremock:
    image: sheyenrath/wiremock.net
    ports:
       - "9091:80"
    volumes:
      - ./wiremock/mappings:/app/__admin/mappings
    command: ["dotnet", "wiremock-net.dll", "--Urls", "http://*:80", "--ReadStaticMappings", "true", "--AllowPartialMapping", "true", "--WireMockLogger", "WireMockConsoleLogger", "--ProxyURL", "https://api.hub24.com.au/epi/epiportfolio.asmx", "--SaveMapping", "true", "--SaveMappingToFile", "true"]

### Other related info
Provide additional information if any.

**Comment by StefH** [comment]
@jmontalto01 Can you provide your (static) mapping json file(s)?

**Comment by jmontalto01** [comment]
Hi,
There was not static mapping files. Folder was empty so I would expect an empty list to return when browsing to http://localhost:9091/__admin/mappings. At the time the error is raised it does then create a mapping json file on my drive which I have supplied below together with the wiremock log which gives more details of the error.

Wiremock Log:
[wiremock log.txt](https://github.com/WireMock-Net/WireMock.Net/files/5727053/wiremock.log.txt)

mapping file at the time of error returned in browser:
[2a1dd2a5-46dc-42a0-91a7-2f94797db1a2.txt](https://github.com/WireMock-Net/WireMock.Net/files/5727057/2a1dd2a5-46dc-42a0-91a7-2f94797db1a2.txt)

**Comment by StefH** [comment]
@jmontalto01 I think I found the issue, a new version from the NuGet + Docker will be released shortly.

This will be version 1.3.10

I'll close this now, in case it is not solved. just comment to this issue.
