### ISSUE TITLE
WithBodyFromFile Support

### ISSUE THREAD

**Issue by jrestall** [WireMock-Net/WireMock.Net#56]
WireMock has support for reading the body content for a stubbed request from a file on disk.

http://wiremock.org/docs/stubbing/#specifying-the-response-body

This is very useful when body content can be very large. 

I couldn't find a way to do this in WireMock.Net, I wonder if others would also like to see this support added?

**Comment by StefH** [comment]
Sounds ok.

Methods will be like:
```c#
IResponseBuilder WithBodyFromFile([NotNull] string filename, bool cache, [CanBeNull] string destination = BodyDestinationFormat.SameAsSource, [CanBeNull] Encoding encoding = null);
```

and

```c#
IResponseBuilder WithBodyFromFile([NotNull] string filename, [CanBeNull] string destination = BodyDestinationFormat.SameAsSource, [CanBeNull] Encoding encoding = null);
```

**Comment by StefH** [comment]
@jrestall I've added some code, can you maybe do a quick review before I create a new NuGet ?

Changed code found at https://github.com/WireMock-Net/WireMock.Net/commit/cbe6a0a2b411a50db30338321f730baf11f2a8ff

**Comment by jrestall** [comment]
Thanks for the amazingly quick turn around @StefH.

I have two questions,

1.  Can we also support relative paths where it defaults to a files directory as in WireMock. So passing path/to/myfile.xml could resolve to {some dir path}__admin/files/path/to/myfile.xml or similar?

2.  Would the following JSON configuration work that uses a BodyAsFile property?
`{
  "Guid": "791a3f31-6946-4ce7-8e6f-0237c7443275",
  ...
  "Response": {
    "StatusCode": 404,
    "BodyAsFile ": "path/to/myfile.xml" 
  }
}`

**Comment by StefH** [comment]
1] This is possible I think.

2] JSONs could be:
```js
{
        "Guid": "5c5b769a-7cfe-44bd-9801-a4e5fcf9bfc5",
        "Priority": 0,
        "Request": {
            "Path": {
                "Matchers": [
                    {
                        "Name": "WildcardMatcher",
                        "Pattern": "/file"
                    }
                ]
            },
            "Methods": [
                "get"
            ]
        },
        "Response": {
            "StatusCode": 200,
            "BodyAsFile": "c:\\temp\\x.json",
            "BodyAsFileIsCached": false,
            "UseTransformer": false,
            "Headers": {}
        }
    }
```
OR
```js
    {
        "Guid": "55631924-791a-419e-928f-b735e312ab99",
        "Priority": 0,
        "Request": {
            "Path": {
                "Matchers": [
                    {
                        "Name": "WildcardMatcher",
                        "Pattern": "/filecache"
                    }
                ]
            },
            "Methods": [
                "get"
            ]
        },
        "Response": {
            "StatusCode": 200,
            "BodyAsBytes": "ew0KICAiaGkiOiAidGVzdCINCn0=",
            "BodyAsFileIsCached": true,
            "UseTransformer": false,
            "Headers": {}
        }
    }
```

3] I'll take a look....

**Comment by StefH** [comment]
3]
My idea is that you would cache small files or files which need to be served very fast.

Other files (big files) could increase the memory from a running WireMock too much, so for these files I would use the non-cached version.

**Comment by jrestall** [comment]
Thanks @StefH, that makes sense. Again thank you so much for the quick turn-around on these enhancements.

**Comment by StefH** [comment]
@jrestall ; the NuGet updated at https://www.nuget.org/packages/WireMock.Net/
