### ISSUE TITLE
WireMock.Net fails during startup with a System.Net.Sockets.SocketException 

### ISSUE THREAD

**Issue by SimonA84** [WireMock-Net/WireMock.Net#560]
I use the nuget package of WireMock.Net for unit tests with xunit. I want to use a port like 19999 to be outside of the range of well known ports.

How to Reproduce it:
- Create a WireMockServerSettings object with the specific port
- Start the server with the settings object
- Add some "endpoints"

`var settings = new WireMockServerSettings{Port = 19999};
var server = WireMockServer _server = WireMockServer.Start(settings);`

What happens:
The server throws in the line with WireMockServer.Start an Wiremock.Exceptions.WireMockException with "Service start failed with error: At least one error occoured"
The inner exceptions are
- System.AccreateException: At least one error occoured
- System.Net.Sockets.SocketException: The Access to a socket was forbidden because the permissions are not correct
(Sorry if you don't have the exact same message. My system is set to german)

What I tried:
- I tried to run the test as an Administrator and as a normal windows user >> In both cases the same error
- I checked if the port is used by a different application >> The Port is free
- I changed my firewall settings >> Still the same error
- I used an URL instead of the port (http://localhost:19999) >> The same error

What I want:
I want to understand why this happens and how to solve and prevent this problem.

**Comment by StefH** [comment]
`Add some "endpoints" ` --> you mean add some mappings ?

**Comment by StefH** [comment]
- What OS do you use ?
- Do you start WireMock.Net consoleapp as admin ?

**Comment by SimonA84** [comment]
Yes. I mean with endpoints some mappings. The extended URL is by my collegues an endpoint.
I'm using a Win10 x64 Enterprise. 
I don't start WireMock.net as a dedicated app. I start it in the tests that I'm running. Like in the following snippet.

``[Fact, Trait("Category", "WireMock")]
public void GetPluginVersionTest()
{
	var settings = new WireMockServerSettings()
	{
		Urls = new[] { mockurl }
	};

	_mockServer = WireMockServer.Start(settings);

	_mockServer
		.Given(
			Request
				.Create()
				.WithPath("/cadresources/buildVersion")
				.UsingGet()
		)
		.RespondWith(
			Response
				.Create()
				.WithStatusCode(HttpStatusCode.OK)
				.WithHeader("Content-Type", "application/octet-stream")
				.WithBodyFromFile(getWireMockFilePath("buildVersion"))
		);
	string version = Utils.GetPluginVersion(mockurl);
	Assert.NotNull(version);

	Assert.True(version.Split('-').Length == 2 || version.Split('-').Length == 3);
}``

As I told at the beginning. I use it in xunit tests.

**Comment by StefH** [comment]
Hello @SimonA84,
It is advised to use random ports in unit tests.
https://github.com/WireMock-Net/WireMock.Net/wiki/Using-WireMock-in-UnitTests

**Comment by SimonA84** [comment]
I changed it to use different ports. It works, but I prefere using a fix port. An external server does not change the port

**Comment by StefH** [comment]
In that case, a possible solution would be to start the server once in the constructor/setup from the unit-test.

Can you try that?

**Comment by SimonA84** [comment]
I got a working solution with one single port and it "recreates" the server for each test as before (with stoping it afterwards).
But what I don't understand is why this port works and the other one has the permission problem, while the isn't used on my system. 
When I take a look at the list of standardized ports in wikipedia (I know the list is not well maintained), then I see that both ports (working: 5001 and not working: 9999) are used by some things which I don't have on my system.

**Comment by SimonA84** [comment]
Thanks for your support.
