### ISSUE TITLE
WireMock not working as expected

### ISSUE THREAD

**Issue by redgoose** [WireMock-Net/WireMock.Net#563]
I'm trying to write some integration tests using Microsoft.AspNetCore.TestHost.TestServer and WireMock and not able to get things working as expected.

This is my [test](https://github.com/redgoose/dotnet-learning/blob/master/Tests/UnitTest1.cs#L56) and here is the [HTTP call](https://github.com/redgoose/dotnet-learning/blob/master/TodoAPI/Integrations/IpifyClient.cs#L20) I'm trying to mock.

Despite following [this guide](https://github.com/WireMock-Net/WireMock.Net/wiki/Using-WireMock-in-UnitTests), my test fails and makes an outbound HTTP call.

Am I matching incorrectly? Is WireMock not meant to be used with TestServer?

Thanks in advance!

**Comment by redgoose** [comment]
hmm... added an additional test [here](https://github.com/redgoose/dotnet-learning/blob/master/Tests/UnitTest1.cs#L84) that doesn't use TestServer and uses the IpifyClient directly and that also fails. Any ideas?

**Comment by StefH** [comment]
@redgoose
The WithPath is used like `"/pathabc"`

Did you try `WithParam(...)` ?

See
https://github.com/WireMock-Net/WireMock.Net/blob/477f3b5cd346a1805a6281fd62bf1e61e791065a/test/WireMock.Net.Tests/RequestTests.cs#L129

**Comment by redgoose** [comment]
yep i tried with `Request.Create().WithParam("format", "json")` as well.

**Comment by StefH** [comment]
@redgoose 

I think that the http-client is not connecting to the WireMock.Net server.

(You need to send the request to `server.Urls[0]`)

I've updated the wiki:
https://github.com/WireMock-Net/WireMock.Net/wiki/Using-WireMock-in-UnitTests

And here is an example:
https://github.com/WireMock-Net/WireMock.Net/blob/92923a12ae70aa5dc7bc228e49499d2ed7e911d8/test/WireMock.Net.Tests/WireMockServerTests.cs#L268

**Comment by redgoose** [comment]
That example doesn't make sense to me. Why are we POSTing to that url? The example in the previous revision made sense since the SUT would do something to trigger an HTTP request. `var response = _sut.DoSomething();`

Are you able to checkout my test app (https://github.com/redgoose/dotnet-learning) and see if you can get test `TestAPIBaz` to work?

Also, you've introduced an undeclared variable `stringContent` into your example.

**Comment by StefH** [comment]
Example is updated to use Get and the URL is changed to `_server.Urls[0]}/foo`.
This does make more sense in the example.

I'll checkout your example and see if I can fix it.

**Comment by StefH** [comment]
See PR : https://github.com/redgoose/dotnet-learning/pull/1

**Comment by redgoose** [comment]
Thanks for your help so far. I looked at the PR and have a question. Why on this [line ](https://github.com/redgoose/dotnet-learning/pull/1/files#diff-0b8b7c4df4e7f9ee16e33c4850d60761449510462bf44c29b63cd80c76607f87L66-R66) are we matching on `/api/learning/baz` when I'm trying to stub out the HTTP call to `https://api.ipify.org?format=json` ?

The logic is, GET `/api/learning/baz` makes an HTTP GET to `https://api.ipify.org?format=json`. It's that latter request I'm trying to stub out.

**Comment by StefH** [comment]
For this example it does not really matter.

If you setup a stub , and then call wiremock using the same path or query parameters ; that will match.

Also view this to get a general understanding on usage:
https://www.youtube.com/watch?v=IJa6DyJOxzk

**Comment by redgoose** [comment]
Okay, what about this [test](https://github.com/redgoose/dotnet-learning/blob/master/Tests/UnitTest1.cs#L84). I'm unable to get the matching to work, do you know what the problem is?

**Comment by StefH** [comment]
1. The IpyfyClient needs to be updated in such a way that it's possible to provide the real base-address and also the mocked base address from WireMock
2. For a match, you need to use `WithParam(...)` 



See my updated PR
https://github.com/redgoose/dotnet-learning/pull/1

**Comment by redgoose** [comment]
thanks so much for your assistance!
