### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by CoderNate** [WireMock-Net/WireMock.Net#565]
https://github.com/WireMock-Net/WireMock.Net/blob/e8181e9d53622bc3f1faa564332f4e87a0a18314/src/WireMock.Net/Server/WireMockServer.Admin.cs#L264

I get a NullReferenceException here when a request fails due to ``mapping`` being null.  It looks like calling proxyHelper.SendAsync returns null for a mapping if the status code was not successful.  The next if statement right below this also has the same issue.

**Comment by StefH** [comment]
Hello @CoderNate ,

Thanks for the information.

However I think you mean that these line can fail:
``` c#
 _options.Mappings.TryAdd(mapping.Guid, mapping);

// and

 _mappingToFileSaver.SaveMappingToFile(mapping);
```

Correct?

**Comment by CoderNate** [comment]
Yes, that's right; my mistake.  Thanks.
And hey cool project!  Nice work!
