### ISSUE TITLE
[Question] Dates in response templates

### ISSUE THREAD

**Issue by Narcalen** [WireMock-Net/WireMock.Net#568]
Is it possible to add formatted dates to response templates? e.g. I would like to do smth like this:

``` json
"Response": {
    "StatusCode": 200,
    "Headers": { "Content-Type": "application/json; charset=utf-8" },
    "BodyAsJson": {
      "data": {
            "id": "{{Random Type=\"Integer\" Min=100 Max=999999}}",
            "status": "draft",
            "createdAt": "{{now format='yyyy-MM-dd'}}",
            "updatedAt": "{{now}}",
      }
    },
    "UseTransformer": true
  }
```
Where now is current datetime, not data extracted from request

**Comment by StefH** [comment]
Hello @Narcalen

This is not yet supported in WireMock.Net but this could be added to Handlebars.Net.Helpers

I will take a look if it can be added there.

**Comment by StefH** [comment]
@Narcalen 

I'm looking at the code from Handlebars.Net/Helpers and in this case, the string to use would be like:
``` c#
"{{Format (Now) \"yyyy-MM-dd\"}}"
```

Would be work for you?

**Comment by StefH** [comment]
Or another possible solution will be: 
``` json
"{{Now \"yyyy-MM-dd\"}}"
```

**Comment by Narcalen** [comment]
Thank you for the response! I gave tried the second option and I am getting the following response: Template references a helper that is not registered. Could not find helper 'Now'

Is it possible to register additional handlebar helpers?

**Comment by StefH** [comment]
Sorry for the confusion I caused.

This new functionality is now present in Handlebars.Net.Helpers however not yet used by WireMock.Net

I'm working in that and I keep you informed.

**Comment by StefH** [comment]
@Narcalen 
I've added functionality to Handlebars.Net.Helpers and these are used in WireMock.Net


Please try preview version `WireMock.Net.1.4.3-ci-14593` from MyGet.

**Comment by Narcalen** [comment]
@StefH 
Thank you for the update
I have updated to WireMock.Net.1.4.3-ci-14593 and tried the following options:
`"{{Format (Now) \"yyyy-MM-dd\"}}"`
`"{{Now \"yyyy-MM-dd\"}}"`

For both options, I received the following error: 
`{
    "Status": "Template references a helper that cannot be resolved. Helper 'Format'"
}`

Moreover, I have received the same errors for other helpers, e.g.:
`{
    "Status": "Template references a helper that cannot be resolved. Helper 'Random'"
}`

Could you please suggest if I am missing anything?

**Comment by StefH** [comment]
Can you share your example project?

**Comment by Narcalen** [comment]
https://github.com/Narcalen/example-wiremock-net

This mapping works fine with version 1.4.3 and returns `Template references a helper that cannot be resolved` error with 1.4.3-ci-14626

**Comment by StefH** [comment]
This should work:

``` c#
"{{Random Type=\"Integer\" Min=100 Max=999999}} {{DateTime.Now}} {{DateTime.Now \"yyyy-MMM\"}} {{String.Format (DateTime.Now) \"MMM-dd\"}}"
```

Use exact version dotnet-WireMock.1.4.3-ci-14635

**Comment by Narcalen** [comment]
@StefH this version works fine for me. Thanks!

**Comment by StefH** [comment]
great!

You can expect a new 1.4.4 in some time
