### ISSUE TITLE
Dynamic webhook setup.

### ISSUE THREAD

**Issue by ShaunJahn** [WireMock-Net/WireMock.Net#578]
Tyring to create a .Net mock server application, that reads a swagger JSON file. Once an endpoint is mocked and return that response is then sent to a webhook. Not sure how to configure the endpoint for swagger to trigger a webhook call back.

**Comment by StefH** [comment]
I think that want to investigate "WireMock.Net.OpenApiParser".

See this example
https://github.com/WireMock-Net/WireMock.Net/tree/master/examples/WireMock.Net.OpenApiParser.ConsoleApp

**Comment by ShaunJahn** [comment]
Thank you for the reply. I manage to integrate the JSON file from swagger as per this link. 
I'm trying to create a callback on every mocked call to trigger a function that sends a payload to a webhook.

For example, when creating a mock instance manually I'm able to use this:
`.WithCallback(callbackHandler)`

I'm trying to set this up for each swagger endpoint that gets read from the JSON file. As this is read dynamically I'm not sure how to assign the callback.

**Comment by StefH** [comment]
I see.

What you want to to loop all automatic generated mappings and then assign .WithCallback

I'm not sure if that's possible. I'll think about it.

**Comment by StefH** [comment]
Also another option would be that you `hook` on the logging? Because the logging also shows the request/response?

**Comment by ShaunJahn** [comment]
Sadly I have tried doing this but still need the webhook to trigger. If you have any ideas on how to achieve this still ill be open to suggestions.

**Comment by StefH** [comment]
Did you try making an own version from the logger?
https://github.com/WireMock-Net/WireMock.Net/blob/master/examples/WireMock.Net.WebApplication.NETCore3/WireMockService.cs#L18

**Comment by ShaunJahn** [comment]
@StefH Thank you, that really helped and I manage to sort this question out.

Thanks again for your help.
