### ISSUE TITLE
Multiple headers with same name

### ISSUE THREAD

**Issue by Dreamescaper** [WireMock-Net/WireMock.Net#58]
Do I understand correct that currently it's not possible to set multiple headers with same name to ResponseMessage? 
In particular, I'm interested in providing multiple Set-Cookie headers.
Is it possible to add such functionality? I could submit PR with changing Headers property from 'IDictionary<string, string>' to something like 'IDictionary<string, string[]>', but not sure how great is that, considering that it is public member.

**Comment by StefH** [comment]
First change will be:

```c#
IResponseBuilder WithHeader([NotNull] string name, params string[] values);
```

Also your idea is possible:

```c#
IResponseBuilder WithHeaders([NotNull] IDictionary<string,string[]> headers);
```

However, also the json parsing should be updated. I will take a look.

**Comment by Dreamescaper** [comment]
Added PR with simple implementation for that.

**Comment by StefH** [comment]
Thanks.

I added the JSON part to your code. Please review.

And if it's ok, I can create a NuGet.

**Comment by Dreamescaper** [comment]
Great, thanks!
