### ISSUE TITLE
[Question] What is the correct configuration for wiremock running in  proxy mode

### ISSUE THREAD

**Issue by genesispvtltd** [WireMock-Net/WireMock.Net#580]
Hi I am new to wiremock but I need to know the answers to the following questions. I have a automation test suite running against an api. Sometimes this api is not available then I need automation test to be run against wiremock server and this should happen automatically I mean wiremock should be intelligent enough to understand the live url is down and it will call the stubs allready created. I tried wiremock standalone version and this is not happening. I started the wiremock on proxy mode and the live url is up and running I sent a request and it does hit live url, and then next I block the live url using the windows host file. I restareted wiremock and I again sent the request to wiremock server running in proxy mode but it fails and send me "No connection could be made because the target machine actively refused it." please help me to understand why I am facing this issue.Basically when the live url is down then i need 12345 to be return. Also the live url endpoint is nothing but it will create a new random number and will return that number. Below is my code also please understand I am using csharp code to write my stubs and i want them to be added as static mappings as well so I am doing it in the code like below

``` c#
using Microsoft.Extensions.Configuration;
using System;
using System.Diagnostics;
using System.IO;
using WireMock.Logging;
using WireMock.Matchers;
using WireMock.Net.StandAlone;
using WireMock.RequestBuilders;
using WireMock.ResponseBuilders;
using WireMock.Settings;

namespace ConsoleApp6
{
    class Program
    {
        static void Main(string[] args)
        {
           
            var mode = "Proxying";
            var url = "http://localhost:7777";
            var proxyUrl = "https://secureApi.com";

            WireMockServerSettings settings = null;
            
                     settings = new WireMockServerSettings
                    {
                        Urls = new[] { url },
                        StartAdminInterface = true,
                        
                        AllowPartialMapping =true,
                        Logger = new WireMockConsoleLogger(),
                         ProxyAndRecordSettings = new ProxyAndRecordSettings
                         {
                             Url = proxyUrl,
                            // SaveMapping = false,
                            // SaveMappingToFile = false,
                            // SaveMappingForStatusCodePattern = "2xx"
                         }
                     };
                    
            

            var wiremockServer = StandAloneApp.Start(settings);

            wiremockServer            
              .Given(              
              Request.Create().WithPath("/Accounts/api/securityhelper/getauthtoken")
              .UsingGet()                          
              .WithCookie("paycorAuth", new RegexMatcher(".*"))
            
              )
              //.AtPriority(100)
              .RespondWith(
                Response.Create()
                 .WithProxy(proxyUrl)
                 .WithBody("12345")
              );

            wiremockServer.SaveStaticMappings();

         
            Console.WriteLine("Press any key to stop the server");
            Console.ReadKey();

        }
    }
}

```

**Comment by genesispvtltd** [comment]
Basically i need to know the setting for java wiremock setting to be implemented in my .net can you please tell me the correct setting for the below in .net version. This serves my purpose because when the live url is down wiremock knows to call its mappings and return them


java -jar wiremock-standalone-2.27.2.jar --proxy-all="https://hcm-quarterly.paycor.com" --https-port 7777 --verbose

**Comment by StefH** [comment]
What you mean is that you actually want a "smart" proxy mode:

**Scenario 1**
In case the real endpoint is up (we need to determine the criteria for _up_), proxy the request + response to the real endpoint.

**Scenario 2**
In case the real endpoint is down, try to find a configured mapping:

If the mapping is found, return that mapping.
If the mapping is not found, just return default 404 'mapping not found'.

---

About the Record-Mode for proxy : I'm not sure yet if this fits in this solution....

**Comment by genesispvtltd** [comment]
@StefH since I am new I am asking just want to know this thing clearly. When we try out the wiremock java version we found that it is actually calls live url and will return response from that. Plus it is intelligent enough to know that the live url is down and then return the stubs already created. even the request is returning status code 500 when  the live url is down wiremock will return the success stub belonging to that path. All this is done by running the java wiremock version with following command

java -jar wiremock-standalone-2.27.2.jar --proxy-all="proxy url" --https-port 7777 --verbose

So I am asking does .net version support this do you have a example of that. That is all

**Comment by StefH** [comment]
Hello @genesispvtltd,

Short answer: WireMock.Net does not yet support a "Smart Proxy" functionality as you describe.

Long answer: This can probably be implemented as defined here:
Scenario 1
In case the real endpoint is up (we need to determine the criteria for up, like != 200 OK), proxy the request + response to the real endpoint.

Scenario 2
In case the real endpoint is down, try to find a configured mapping:

If the mapping is found, return that mapping.
If the mapping is not found, just return default 404 'mapping not found'.

**Comment by genesispvtltd** [comment]
@StefH thanks for the response I am good.cool

**Comment by StefH** [comment]
Can this question be closed for now?

**Comment by genesispvtltd** [comment]
yeah sure

**Comment by walidhaidarii** [comment]
Hi @StefH 

> Short answer: WireMock.Net does not yet support a "Smart Proxy" functionality as you describe.

Any hope WireMock.Net _would_ support the "**Smart Proxy**" functionality

In my case, I needed it to only fall over to the proxy if no mapping is found, which will happen for the first request only, which will save the mapping to disk, so the next call the wire mock server will just read the mapping

I think this case is complex in which the wire mock server needs to keep watching the static files, not to update them - as currently happening - but to load them for new requests

Now only workaround solution is to run a proxied wire mock server to save all the mappings to disk, then upload the mappings to another non-proxied wire mock server (__admin folder) which serves them for our e2e testing framework
Any comments or ideas are welcome!
