### ISSUE TITLE
Response Templating_Method not found error

### ISSUE THREAD

**Issue by jthomas2021** [WireMock-Net/WireMock.Net#583]
I am trying to create a wiremock service where if a request comes in matching say an account number, it will respond with a response of say Success and if another account number, it will respond with a response of Bad request. Unfortunately there are json tag elements in the response that will change depending on the request, e.g in my below example RequestId needs to be the same as that of the request, for the downstream system to accept it,else it will be a duplicate transaction , if I hard code the value
Request:
``` json
{
"RequestId" : "a43d1856",
....
"Accountnumber": "7654322"
}
```

Response:
``` json
{
"RequestId" : "a43d1856",
"ReasonCode" : "Success"
}
```

I used JsonPathMatcher to match the account number for the request, but I am finding it difficult to figure out how to substitute the dynamic request id from the incoming request to the response.

I tried: 
``` json
"Response": {
"StatusCode": 200,
"BodyAsJson": {
"RequestId": "{{JsonPath.SelectToken request.body \"$.RequestId\"}}",
"ReasonCode" : "Success"
},
"UseTransformer": true,
"headers": {
"Content-Type": "application/json"
}
}
```
When I send a request through soapui matching the request, I get response : Method not found

Can you help me with what I am doing wrong?

**Comment by StefH** [comment]
@jthomas2021 
You could use something like this:
``` json
{
    "Request": {
        "Methods": [
            "post"
        ],
        "Body": {
            "Matcher": {
            "Name": "JsonPathMatcher",
            "Pattern": "$..[?(@.Accountnumber == 7654322)]"
          }
        }
    },
    "Response": {
    	"StatusCode": 200,
        "Body": "Success"
    }
}
```

And 
`"Pattern": "$..[?(@.Accountnumber != 7654322)]"` --> return body with "NotFound/Error/..."

**Comment by jthomas2021** [comment]
@StefH 
I understood the Request matcher piece of it and it works , thank you. But my question was how do I substitute the value for RequestId in the response, based on what request comes in.  

For example if this is the request, that comes in at a particular time

{
"RequestId" : "a43d1856",
....
"Accountnumber": "7654322"
}

then in my json stubbing, I want to get the RequestId from the request( "a43d1856") and use that as my request id in my response.

"Response": {
"StatusCode": 200,
"BodyAsJson": {
"RequestId": "{{JsonPath.SelectToken request.body \"$.RequestId\"}}",
"ReasonCode" : "Success"
},
"UseTransformer": true,
"headers": {
"Content-Type": "application/json"
}
}

I was hoping that JsonPath.SelectToken would get the request body, look at the request id and get the value . But it does not work. It is throwing the Method not found error.

Please let me know what I am doing wrong.

Thank you.

**Comment by StefH** [comment]
I see.
In that case:

# Step 1
You need to match the request using the code I provided in my comment.
JsonPath is only used for _Request Matching_ --> https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching

# Step 2
You want to use the transformer to return the RequestId, in this case use this code:
``` json
"Response": {
  "StatusCode": 200,
  "BodyAsJson": {
    "RequestId": "{{request.BodyAsJson.RequestId}}",
    "ReasonCode" : "Success"
  },
  "UseTransformer": true,
  "Headers": {
    "Content-Type": "application/json"
   }
}
```
For the response you need to use this: https://github.com/WireMock-Net/WireMock.Net/wiki/Response-Templating

**Comment by StefH** [comment]
Hello @jthomas2021, is the answer clear to you?

**Comment by jthomas2021** [comment]
Hi @StefH , 

Sorry for the delay. I added "RequestId": "{{request.BodyAsJson.RequestId}}" 

with the   

 "Headers": {
    "Content-Type": "application/json"
   }

in the response, and now  when I sent the request through soap ui to the mock service url, I do not get the method not found error. I get the response as stated in the mock service response, however the RequestId value is empty.

My request in the mockservice looks something like this

{
    "Request": {
        "Methods": [
            "post"
        ],
        "Body": {
            "Matcher": {
            "Name": "JsonPathMatcher",
            "Pattern": "$..[?(@.Accountnumber == 7654322)]"
          }
        }
    },

The request that I actually send to the mock url using soap ui looks like below

{
"RequestId" : "a43d1856",
....
"Accountnumber": "7654322"
}

I am wondering if the mockservice should have RequestId in the request body inorder for the value to be caught in request.BodyAsJson.RequestId in the response. If yes, how would I add that to the body when I already have a JsonPathMatcher for the Accountnumber in the body of the mockservice request?

**Comment by jthomas2021** [comment]
Thanks @StefH  it worked! Thank you for your help!
