### ISSUE TITLE
How to validate request headers and cookies

### ISSUE THREAD

**Issue by genesispvtltd** [WireMock-Net/WireMock.Net#584]
Hi , I just want to know how  can I show unauthorized when the cookie is not passed in the request. I wrote the stub like below but it did not work.pls help to correct it thanks

``` c#
wireMockServer                 
            .Given(
         Request.Create().WithPath("/PayrollReportService/v1/clients/208944/payrollreports*")  
         .UsingGet()
         .WithCookie("pay",  "*", MatchBehaviour.RejectOnMatch)   
         ).AtPriority(1)
         .RespondWith(
           Response.Create()
            .WithProxy(proxyUrl)
            .WithStatusCode(HttpStatusCode.Unauthorized)
         );
```
Also second question is if someone passed wrong cookie say like the cookie name is pay but someone passed cookie name as paid and that time I want to display unauthorized how can i code that stub thanks.

**Comment by genesispvtltd** [comment]
Hello, is there a way we can do this thanks.

**Comment by StefH** [comment]
The easiest would be to:

### 1]
Add a mapping which uses path `"/PayrollReportService/v1/clients/208944/payrollreports*"`, checks the valid cookie and returns http 200.

### 2]
Add another mapping which uses the same path, but has no check on the cookie and returns Unauthorized

**Comment by genesispvtltd** [comment]
Thanks this worked
