### ISSUE TITLE
Json Parse Exception error

### ISSUE THREAD

**Issue by ShaunJahn** [WireMock-Net/WireMock.Net#586]
On loading an OpenApiFile with `WithMappingFromOpenApiFile` im getting an exception:

`Newtonsoft.Json.JsonReaderException: 'Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 1963.'`

I think this might be due to `MapOpenApiAnyToJToken` using `JObject.Parse` instead of `JToken.Parse`

Could this be the case? Then open API document is valid and from swagger

**Comment by StefH** [comment]
Can you please provide the document?

**Comment by ShaunJahn** [comment]
My apologies, my swagger document was not correct as it was bringing nulls where it needed strings.
