### ISSUE TITLE
Proxy all requests - even a repeated one

### ISSUE THREAD

**Issue by DarthXerox** [WireMock-Net/WireMock.Net#592]
Hey,
hopefully I didn't miss some hidden feature or a different way to solve this problem:

**Repeated request problem**
I'm sending a sequence of requests from a client to my webapi, some of these requests repeat.
The problem occurs when the same request is received the second time - it is NOT sent to the `Url`, only the previously saved response is sent back. 
I do not need to record the request again, only that the `Url` receives the request again, without it the rest of the requests are invalid.

**Possible solution**
Adding a `ProxyAll = true` option in `ProxyAndRecordSettings` which would tell the server to proxy ALL requests to the `Url`

**Is your feature request supported by [WireMock (java version)](https://www.wiremock.org)? Please provide details.**
Yes, by `--proxy-all` command line option in http://wiremock.org/docs/running-standalone/

Thanks for help

**Comment by StefH** [comment]
Hello @DarthXerox,
So you want to save only the **first** proxied mapping to the internal mapping + file?

**Comment by marspox** [comment]
Hello,

> Hello @DarthXerox, So you want to save only the **first** proxied mapping to the internal mapping + file?
Is it possible to have that functionality or maybe it has been already added?

BR
