### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by Korporal** [WireMock-Net/WireMock.Net#598]
Hi,

I went to the suggested example repo for basic unit test examples but the demo tests timeout, I did some basic looking around at network settings etc. and updated the demo to use latest version of WireMock but it still times out,

I put an [issue for the author here](https://github.com/bredah/csharp-wiremock/issues/1) but this slow going so can anyone suggest anything?

Thx

**Comment by StefH** [comment]
@Korporal , see my answer at the original issue.
