### ISSUE TITLE
Cause Delay in server responding

### ISSUE THREAD

**Issue by jthomas2021** [WireMock-Net/WireMock.Net#599]
How can I make the server delay in responding so that the application calling my mockservice will timeout.

**Comment by StefH** [comment]
Hello @jthomas2021,

Does this help?
https://github.com/WireMock-Net/WireMock.Net/wiki/Stubbing#simulating-delays

**Comment by jthomas2021** [comment]
Hi @StefH ,

Is it possible to add the delay in the json stubs?

**Comment by StefH** [comment]
Sure.

See example: https://github.com/WireMock-Net/WireMock.Net/wiki/Admin-API-Reference#get----__adminmappings

**Comment by StefH** [comment]
See also Swagger : https://app.swaggerhub.com/apis/StefHeyenrath/WireMock/1.4.7

``` json
 Delay:
        type: integer
        description: Gets or sets the delay in milliseconds.
        format: int32
````

**Comment by jthomas2021** [comment]
Thank you @StefH .This worked.
