### ISSUE TITLE
Partial mapping

### ISSUE THREAD

**Issue by alastairtree** [WireMock-Net/WireMock.Net#61]
Great library, thanks! I cant see any docs/explanation on the "AllowPartialMapping" option? Have I missed them? What does it do?

**Comment by alastairtree** [comment]
From the looks of the code partail mapping enabled changes the behavior when a request is received. By default only the first exactly matching request matcher with the highest priority is selected to respond to the request. With partial mapping enabled then a matcher that does not exactly match can still pick up the request based on a 'closest match' type algorithm. Is that the gist of it? If so an update to the docs would be appreciated.
Thanks

**Comment by StefH** [comment]
See https://github.com/WireMock-Net/WireMock.Net/wiki/Settings

Is this clear?

**Comment by alastairtree** [comment]
Perfect thanks.
