### ISSUE TITLE
How to mock a download limit when downloading a file?

### ISSUE THREAD

**Issue by JasonLandbridge** [WireMock-Net/WireMock.Net#613]
Given the following code:
``` c#
var _server = WireMockServer.Start();      
_server
    .Given(Request.Create().WithPath("media/file.avi").UsingGet())
    .RespondWith(
        Response.Create()
            .WithStatusCode(206)
            .WithBodyFromFile("media/file.avi")
    );
```
File downloads fine but It goes extremely fast as it is read from SSD into a memory stream. How can I make the download go slower as to mimic real life scenario?

Thanks in advance!

**Comment by StefH** [comment]
Hello @JasonLandbridge,

As workaround, you can implement your own version from `IFileSystemHandler`.

See https://github.com/WireMock-Net/WireMock.Net/wiki/Settings#filesystemhandler for details.

**Comment by JasonLandbridge** [comment]
@StefH, thanks for the answer!

I went a different route, I implemented a download limiter stream as explained here: [stackoverflow](https://stackoverflow.com/questions/32723561/bandwidth-throttling/32724000#32724000)

And now I can use that in my unit tests, which works perfectly with WireMock!

Also, thank you very much for all your work on WireMock.Net!

(Lekker bezig pik 💯 )
