### ISSUE TITLE
Is it possible to some how send multiple webhooks?

### ISSUE THREAD

**Issue by ShaunJahn** [WireMock-Net/WireMock.Net#614]
When setting up a mock endpoint and using:
`WithWebhook` for single works perfectly.

Would be possible to use the same logic but provide a list of `Webhook` and send multiple webhooks at a time?

**Comment by StefH** [comment]
@ShaunJahn Do you mean multiple webhooks? Or sending the same webhook to multiple urls?

**Comment by ShaunJahn** [comment]
Trigger multiple webhooks on the same request.

**Comment by StefH** [comment]
Can you try MyGet preview version:
1.4.14-ci-15092

**Comment by ShaunJahn** [comment]
Do you mean update `WireMock.Net` to that version? I tried but can't be found.

**Comment by StefH** [comment]
@ShaunJahn 
Correct, I mean updating the NuGet to that version. But this version is not defined on nuget.org, but on myget.

See this wiki link for details:
https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by ShaunJahn** [comment]
Thank you for this,
I changed the code and both webhooks went through,
![image](https://user-images.githubusercontent.com/35134264/118799093-a35c2280-b89e-11eb-9794-73279d7a4452.png)

but the body seems to come back as null
![image](https://user-images.githubusercontent.com/35134264/118798939-7c055580-b89e-11eb-8b76-20ae596eb0f6.png)

**Comment by StefH** [comment]
I think in your case you need `DetectedBodyType = BodyType.String`

See also:
https://github.com/WireMock-Net/WireMock.Net/wiki/Webhook#c

**Comment by ShaunJahn** [comment]
Can confirm that it's working perfectly after that change.
Thank you @StefH

**Comment by StefH** [comment]
OK. Thank you for verifying.

I'll merge this PR and release a official new NuGet shorty.

**Comment by ShaunJahn** [comment]
Awesome, thank you so much for this and the great work.
