### ISSUE TITLE
Trying to use attribute of the request object while creating response while mocking a soap service

### ISSUE THREAD

**Issue by msutar021** [WireMock-Net/WireMock.Net#618]
I want to create a mock response for SOAP service which accepts XML request . I'm using XPathMatcher for request matching. Request is matching is done successfully. I need to read one attribute of request.body and create the response using that.
My XML request is like this. I need the token id to create the response body.

[Request.txt](https://github.com/WireMock-Net/WireMock.Net/files/6788936/Request.txt)
``` xml
<?xml version='1.0' standalone='no'?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.Test.nl/XMLHeader/10" xmlns:req="http://www.Test.nl/Betalen/COU/Services/RdplDbTknLystByOvkLyst/8/Req">
   <soapenv:Header>
      <ns:TestHeader>
         <ns:HeaderVersion>10</ns:HeaderVersion>
         <ns:MessageId>MsgId10</ns:MessageId>
         <ns:ServiceRequestorDomain>Betalen</ns:ServiceRequestorDomain>
         <ns:ServiceRequestorId>CRM</ns:ServiceRequestorId>
         <ns:ServiceProviderDomain>COU</ns:ServiceProviderDomain>
         <ns:ServiceId>RdplDbTknLystByOvkLyst</ns:ServiceId>
         <ns:ServiceVersion>8</ns:ServiceVersion>
         <ns:FaultIndication>N</ns:FaultIndication>
         <ns:MessageTimestamp>?</ns:MessageTimestamp>
      </ns:TestHeader>
   </soapenv:Header>
   <soapenv:Body>
      <req:RdplDbTknLystByOvkLyst_REQ>
         <req:AanleveraarCode>CRM</req:AanleveraarCode>
         <!--Optional:-->
         <req:AanleveraarDetail>CRMi</req:AanleveraarDetail>
         <req:BerichtId>BerId</req:BerichtId>
         <req:BerichtType>RdplDbTknLystByOvkLyst</req:BerichtType>
         <!--Optional:-->
         <req:OpgenomenBedragenGewenstIndicatie>N</req:OpgenomenBedragenGewenstIndicatie>
         <req:TokenIdLijst>
            <!--1 to 10 repetitions:-->
            <req:TokenId>0000083256</req:TokenId>
            <req:TokenId>0000083259</req:TokenId>
         </req:TokenIdLijst>
      </req:RdplDbTknLystByOvkLyst_REQ>
   </soapenv:Body>
</soapenv:Envelope>
```

I am using the below matcher models while creating mapping for the request.
``` c#
  var matcherModel = new MatcherModel
            {
                Name = "WildcardMatcher",
                Pattern = "/xpathsoap",
                RejectOnMatch = false,
                IgnoreCase = true
            };

            var bodymatcherModel = new MatcherModel
            {
                Name = "XPathMatcher",
                Pattern = "//*[local-name() = 'RdplDbTknLystByOvkLyst_REQ']",
                IgnoreCase = true
            }; 
           
            var matcherModels = new[] { matcherModel };
            var pathModel = new PathModel { Matchers = matcherModels };

            var bodymatcherModels = new[] { bodymatcherModel };
            var BodyModel = new BodyModel { Matchers = bodymatcherModels };

            var requestModel = new RequestModel { Path = pathModel,  Body = BodyModel };
            return requestModel;
```
And response model in mapping
``` c#
 IDictionary<string, object> header = new Dictionary<string, object>();
 header.Add("Content-Type", "Application/xml");

return new ResponseModel()
            {
                StatusCode = 201,
                Headers = header,
                Body = "{{ XPath.SelectNodes request.body \"//TokenIdLijst\"}}",
                UseTransformer = true
            };
```

The above code returns response as blank. I get whole request in the response.body if i use the below code without xpath
``` c#
var response =  new ResponseModel()
            {
                StatusCode = 201,
                Headers = header,
                Body = "{{ request.body }}",
                UseTransformer = true
            };
```
I tried different examples of using xpath but nothing works.  Where is the mistake, i could not find.

Please suggest..

**Comment by StefH** [comment]
@msutar021 

Take a look at:
https://stackoverflow.com/questions/56933756/how-to-create-xpath-for-soap-header-and-body

In your case, I think you can use:
``` xml
//*[local-name()='TokenIdLijst']
```

**Comment by msutar021** [comment]
I have tried this, it is not working; Response is null.

**Comment by StefH** [comment]
The issue was related to `<?xml version='1.0' standalone='no'?>`

A new version will be released shorty.

See also
https://github.com/WireMock-Net/WireMock.Net/blob/master/test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsXPathTests.cs#L124

**Comment by msutar021** [comment]
Thank you so much for the reply. Please keep posted on the new version.

**Comment by StefH** [comment]
It was released as version 1.4.18
https://github.com/WireMock-Net/WireMock.Net/blob/master/CHANGELOG.md

**Comment by msutar021** [comment]
Thank you. Its working now.

**Comment by msutar021** [comment]
I have one more question. I am getting the request attribute. I have to generate soap response based on the number of tokenids.  for each tokenid , i need to create node with few attributes for which i have to create random numbers using regex.
for example 

<TokenGegevens>
				<TokenId>0000083259</TokenId>
				<Test1>1</Test1>
				<Test2>123234324</Test2>
				<Test3>1</Test4>
				<Test4>ACC07072021123456</Test4>	
</TokenGegevens>

So my requirement is to extend the responsetemplate to customize it. 
I have posted here as its the next step for me.  
Please suggest how can i achieve this.
