### ISSUE TITLE
BodyParser Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by Glen-Moonpig** [WireMock-Net/WireMock.Net#629]
### Describe the bug

I keep getting a JsonReaderException when Wiremock is trying to parse a request body.
It works on my build server (linux dotnet image), not on my local machine (Windows 10, .NET Core 3.1).
I managed to get it working temporarily by deleting the bin folder and rebuilding, but that is no longer working.

![image](https://user-images.githubusercontent.com/45943914/130240305-588c7ea0-23ad-436b-bb07-029c2504c4c2.png)

![image](https://user-images.githubusercontent.com/45943914/130246365-b53de0c5-09aa-4cf3-9987-595d6a9e31a3.png)

I am using xUnit with Microsoft Visual Studio Professional 2019 Version 16.9.3

### Expected behavior:

Wiremock should read the incoming request and serve the JSON response.

### Test to reproduce

The failure is on a GET request

```csharp
                .Given(Request.Create()
                    .WithPath($"/SomeProjectKey/carts/{cartId}")
                    .UsingGet())
                .RespondWith(
                    Response.Create()
                        .WithStatusCode(200)
                        .WithBodyFromFile("./TestData/GetCart.json")
                );
```

### Other related info
Provide additional information if any.

**Comment by Glen-Moonpig** [comment]
I have changed my code to read the JSON file using System.IO.File and still getting the same error...

```csharp
var body = File.ReadAllText("./TestData/CommercetoolsGetCart.json");

...
                .RespondWith(
                    Response.Create()
                        .WithStatusCode(200)
                        .WithBody(body)
                );
```

![image](https://user-images.githubusercontent.com/45943914/130243338-3e1c4c63-3a00-4dfe-bce9-c9839a9b00c7.png)

**Comment by StefH** [comment]
Can you also post the file?

**Comment by Glen-Moonpig** [comment]
> Can you also post the file?

Hello @StefH I have updated the issue description since I first created it. I think the exception is happening when Wiremock is trying to parse the body of the incoming request rather than the response body JSON. Is that what `BodyParser.Parse` is doing?

**Comment by StefH** [comment]
In that case, can you post the complete request message you send?

**Comment by Glen-Moonpig** [comment]
> In that case, can you post the complete request message you send?

It is a GET request, there is no body to parse. The config for the request is

```csharp
.Given(Request.Create()
    .WithPath($"api/carts/{cartId}")
    .UsingGet())
```

I expect `BodyParser.ShouldParseBody` is returning true when it should be returning false.

**Comment by Glen-Moonpig** [comment]
```csharp
if (request.Body != null
```

Should probably be

```csharp
if (string.IsNullOrWhitespace(request.Body)
```

See [here](https://github.com/WireMock-Net/WireMock.Net/blob/dc078b57ea463e2c9c7da7f6579af34000596446/src/WireMock.Net/Owin/Mappers/OwinRequestMapper.cs#L57)

**Comment by StefH** [comment]
Do you have only 1 mapping defined? That "GET" mapping?

And what kind of request do you send to WireMock.Net ?
(It looks like you send a POST request with an empty body, but with content-type json?)
So can you provide the request you send (maybe you send it via postman?)

**Comment by Glen-Moonpig** [comment]
> Do you have only 1 mapping defined? That "GET" mapping?
> 
> And what kind of request do you send to WireMock.Net ?
> (It looks like you send a POST request with an empty body, but with content-type json?)
> So can you provide the request you send (maybe you send it via postman?)

Only the one mapping for that path. I have other mapping on different paths.

The request is sent using [commercetools-dotnet-core-sdk-v2](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2).
It has HttpClient logging and I can see in the logs

```
Start processing HTTP request "GET" http://localhost:46871/api/carts/Cart123
```

**Comment by Glen-Moonpig** [comment]
Here is the HttpRequestMessage that is sent

![image](https://user-images.githubusercontent.com/45943914/130258957-64c09ac7-c6f9-4251-b8f9-6f99b4dc0cce.png)

**Comment by StefH** [comment]
And WireMock is running at http://localhost:46871 ?

And what happens if you remove all other mappings, and just keep this 1 GET mapping?

**Comment by Glen-Moonpig** [comment]
> And WireMock is running at http://localhost:46871 ?
> 
> And what happens if you remove all other mappings, and just keep this 1 GET mapping?

Yes that is the correct base URL for wiremock.
I have removed all other mappings and it still errors on that request.

The fact that this works on my linux build server but fails on my Windows machine makes me suspect that there is some difference in how .NET or Wiremock is behaving.
I'm wondering if it is to do with the `USE_ASPNETCORE` preprocessor directives in Wiremock, but that only seems to change when the target framework changes and target framework is the same. Both are running in Debug mode, it fails for me in Release too...

**Comment by StefH** [comment]
Interesting.
Are you able to create a console-app which uses that  commercetools-dotnet-core-sdk-v2 to send the request ? Then I can debug WireMock.

**Comment by Glen-Moonpig** [comment]
I have managed to debug by Visual Studio decompiling the source. I can see that within the SDK I am using it is first sending a request to a token endpoint to fetch an auth token. The body it is sending is not JSON. The content type is `application/x-www-form-urlencoded` and the body is:

```
grant_type=client_credentials&scope=some_scope
```

![image](https://user-images.githubusercontent.com/45943914/130263041-0eeb09a1-d531-441e-a734-6237238d9347.png)

Sorry to have wasted time talking about the GET request, but as far as I could see that is what was happening...

Are there any known issues with Wiremock handling application/x-www-form-urlencoded bodies?

**Comment by Glen-Moonpig** [comment]
I think the problem may be that the content type matcher does not include a wildcard at the end

```csharp
new WildcardMatcher("application/x-www-form-urlencoded", true)
```

and my content type header has charset included

`Content-Type: application/x-www-form-urlencoded; charset=utf-8`

**Comment by Glen-Moonpig** [comment]
Actually, it looks like `MediaTypeHeaderValue.TryParse` should have extracted only the media type. I am not sure why it is using the JSON parser here.

**Comment by Glen-Moonpig** [comment]
...I think this may have all been a waste of time. Wiremock attempts to deserialize as JSON and catch the JsonReaderException and ignore it. Because I am debugging and have CLR exceptions on it appeared to be a failure, but is actually expected.

Thanks for your time and patience.

**Comment by StefH** [comment]
No worries.
I am glad your issue is solved.
