### ISSUE TITLE
Provide exact type values for the response when using OpenApi parser.

### ISSUE THREAD

**Issue by tvytrykush** [WireMock-Net/WireMock.Net#638]
I'm using `WithMappingFromOpenApiFile(path, settings, out var diag);` and it adds mapping from my file just fine, but I'm stuck with generic type values (42 for int, "example-string" for string) when getting a response. In what way can I adjust these values?

**Comment by StefH** [comment]
You can provide your own example values to the settings object:
``` c#
var settings = new WireMockOpenApiParserSettings();
settings.ExampleValues.Integer = 12345;
```

**Comment by tvytrykush** [comment]
@StefH, is it also possible to specify this values per mapping path?

**Comment by StefH** [comment]
@tvytrykush 
No sorry that's not possible.

However. maybe when you add an example in the openapi file, these values are used.
