### ISSUE TITLE
Conditionals for templating

### ISSUE THREAD

**Issue by devmariodiaz** [WireMock-Net/WireMock.Net#640]
Mr Stef, 

I hope that everything is doing well.

I have a question: Is there any way to use conditional in templating response?

**Comment by StefH** [comment]
Hello Mario.

WireMock.Net uses Handlebars.Net which follows the same logic as handlebars.js

See this page on how to use `if` : https://handlebarsjs.com/guide/builtin-helpers.html#if

**Comment by devmariodiaz** [comment]
Hello Mr. Stef,  That's great, big thanks for your valuable help.
