### ISSUE TITLE
How to using WireMock.NET with Appium to mock mobile app response

### ISSUE THREAD

**Issue by vfongmala-willowinc** [WireMock-Net/WireMock.Net#645]
I have a mobile app which is pointing to real URL (with HTTPS).
I run an automation test on the app by using Appium framework.

I want to intercept the response from real URL with the mock data without changing the URL on the app.
What would be the correct configuration to start the server?

What I've tried.
1) I set Android emulator proxy to my local machine IP address with port 7777
2) I setup the WireMock server like this
```
_server = WireMockServer.Start(new WireMockServerSettings()
{
    Urls = new[] { "https://<real url>:443"},
    Port = 7777,
    Logger = new WireMockConsoleLogger(),
});
```
3) I didn't have any specific certificate setup for HTTPS. Do I need one?

However, it doesn't seems to work as I expect. Emulator couldn't connect to WireMock server and couldn't connect to the real server either.

**Comment by StefH** [comment]
I'm closing this issue for now.

If there are any Appium specific steps to take, I can create a new WIKI page, but I think that the general idea on how to use WireMock.Net is the same for all integrations.

Else, please create a new issue with a wiki-page proposal on this topic.
