### ISSUE TITLE
Package download

### ISSUE THREAD

**Issue by The-Futurist** [WireMock-Net/WireMock.Net#647]
I just cloned the repo and attempted to build the solution. However I see a huge number of nuget timeout errors, e.g.

![image](https://user-images.githubusercontent.com/12262952/136664114-a1964816-0fe3-4160-ab4f-319a0e59e1f2.png)

I am restricted to a DSL internet connection but have never seen this before, I can see that this solution does seem to consume a very large number of packages though.

I suspect that the system (nuget? visual studio?) has issued a large number of async requests and in fact has issued too many because the volume of the traffic is so high that individual requests exceed 100 seconds and timeout. it's as if the system has no upper limit on the number of outstanding package requests it will allow.

So this isn't a wiremock issue but because there are so many packages I wanted to ask if others have seen this?

**Comment by Korporal** [comment]
Hi, I retried and think it has restored everything, I ran the build in VS 2022.

I think all packages are now eventually installed, but this puzzles me, I can't tell if this is a problem in the solution itself or a side-effect of my problematic restores:

![image](https://user-images.githubusercontent.com/12262952/136665452-c288e36e-fcd1-4856-bd2c-73ac1cd2d006.png)

I'm assuming that package is pulled in by some other package and the messed up timeouts have confused everything, there is no mention of that package in the two projects' packages.config files.

Thanks

**Comment by Korporal** [comment]
@StefH  - Thanks, I pulled the changes and the solution builds, now for another question - about my problem and how WireMock can help...
