### ISSUE TITLE
Temporary cache data using POST method

### ISSUE THREAD

**Issue by devmariodiaz** [WireMock-Net/WireMock.Net#652]
Hello Stef,

Hoping that everything is doing well.

I have a question: WireMock is able to store temporary cache when we are using POST or any operation?

**Comment by StefH** [comment]
Hello Mario,
I'm not sure I fully understand your request.

Can you provide an example / use-case scenario?

**Comment by devmariodiaz** [comment]
Hello Stef, Thanks for always your quick answers.

For example, I will send some data using POST/PUT or another HTTP method, I want that this data can be stored in a kind of cache for a determined time inside a based WireMock solution.

i. e:

I will send the data as follows:
{
    "firstName": "Mario",
    "birthDate": "01-01-2000",
   .
   .
   .
   "insertedAt": "01-01-2020"
}

To for example this endpoint:
POST /someEndpoint/customer

I want to store this data temporarily, for one day, to be found after.

**Comment by StefH** [comment]
Hello Mario,

In that case, there should be an option to provide the start-time, end-time or expiration-time.

Proposal:
In the Mapping you can provide the start-time and end-time when this mapping should be used

``` js
{
    "Guid": "dae02a0d-8a33-46ed-aab0-afbecc8643e3",
    "Start": "2021-10-20T05:25:40",
    "End": "2022-01-01T01:01:01",
    ...
```

- If "Start" is omitted, the current DateTime is used
- If "End" is omitted, there is no end-time


And you can also only provide the TTL / TimeToLive

``` js
{
    "Guid": "dae02a0d-8a33-46ed-aab0-afbecc8643e3",
    "TTL": 3600,
    ...
```

Would this work for you?

**Comment by StefH** [comment]
@devmariodiaz 
To make sure you have the correct version, there is a new vetrsion : `1.4.24-ci-15516`. Please try that.

In your example, when you add that mapping and send a POST request, WireMock.Net will return a 404 because now (2021 21 oktober) does not fall in the Start and End range.
