### ISSUE TITLE
WireMock published in a VM not working with SOAP (Timeout)

### ISSUE THREAD

**Issue by devmariodiaz** [WireMock-Net/WireMock.Net#653]
Hello Stef,

Good afternoon Stef,

I hope you are doing well;

I am trying to send the xml-soap body request as a pattern, when I am running in localhost:8080 its working perfectly, after deploying in azure devOps pipeline URL:8080 when the pattern in body request contains "<soap:envelope>" it is not working, and keep processing (Timeout), could you please let me know if you have any recommendation for this problem, I am publishing in http without SSL

You can see the body pattern as follows:

SOAP request body:

```
"Body": {
"Matcher": {
"Name": "ExactMatcher",
"Pattern": "<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:xsi=\"http://someurlthatnotexist/XMLSchema-instance\" xmlns:xsd=\"http://someurlthatdosntexist/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"> xmlns=\"https://www.someurlthatdoesntexist.com/xml/\">13"
}
}
},
```

And this is the body request:

```
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://someurlthatdosntexist/XMLSchema" xmlns:xsi="http://someurlthatnotexist/XMLSchema-instance">
   <soap:Body>
      <CtoF xmlns="https://www.someurlthatdoesntexist.com/xml/">
         <C>13</C>
      </CtoF>
   </soap:Body>
</soap:Envelope>
```

**Comment by StefH** [comment]
Hello @devmariodiaz 

Did you find a solution for this?

**Comment by StefH** [comment]
Hello @devmariodiaz, is this still a problem for you? Else I'll close this issue.

**Comment by devmariodiaz** [comment]
Hello Stef, I'll close this issue because this is already solved.

Thanks for all 💯
