### ISSUE TITLE
Using --WireMockLogger in command line

### ISSUE THREAD

**Issue by devmariodiaz** [WireMock-Net/WireMock.Net#656]
Hello Stef,

I hope that you are doing well.

As you know, I'm using the standalone way to build a based WireMock solution

I want you to ask about the option --WireMockLogger. What are the possible values that this option could be taken?

**Comment by StefH** [comment]
I think that two values are supported.

Described here:
https://github.com/WireMock-Net/WireMock.Net/wiki/WireMock-commandline-parameters
