### ISSUE TITLE
How to filter in BodyAsFile JsonPath.SelectToken

### ISSUE THREAD

**Issue by andresendava** [WireMock-Net/WireMock.Net#658]
Similar as Body As Json:

```
      "BodyAsJson": {
        "method": "{{request.method}}",
        "response": "{{JsonPath.SelectToken request.body \"$.person[?(@.id == 1)]\"}}"
      },
```

How to use in Body As File ??

```
      "BodyAsFile": {
        "method": "{{request.method}}",
        "response": "{{JsonPath.SelectToken {{Path/to/Json_file}}\"$.person[?(@.id == 1)]\"}}"
      },
```

This feature is supported?

Thanks in Advance

**Comment by StefH** [comment]
Hello @andresendava,

For your scenario, you need to set UseTransformer to true to also transform the filename.

More details how to use it are found herE:
- https://github.com/WireMock-Net/WireMock.Net/blob/dc078b57ea463e2c9c7da7f6579af34000596446/test/WireMock.Net.Tests/ResponseBuilders/ResponseWithTransformerTests.cs#L417
- https://github.com/WireMock-Net/WireMock.Net/blob/dc078b57ea463e2c9c7da7f6579af34000596446/test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsJsonPathTests.cs#L352
