### ISSUE TITLE
How to pass attributes in JsonPath

### ISSUE THREAD

**Issue by AndresGMD** [WireMock-Net/WireMock.Net#659]
Hello.

In this example I would like to get ID using Cleaning Path

I've defined my path like /path/* And I use the attribute request.PathSegments.1 to get the (*) value

How to pass this attribute in JsonPAth like this?
``` json
      "BodyAsJson": {
        "method": "{{request.method}}",
        "response": "{{JsonPath.SelectToken request.body \"$.person[?(@.id == {{request.PathSegments.1 }} )]\"}}"
      },
```
Thanks in Advance!

**Comment by StefH** [comment]
Hello @andresendava ,

Did you try `request.PathSegments.2` ?

**Comment by andresendava** [comment]
I know that is attribute splitting path and I would like to use a clean path to pass parameters.

**Comment by StefH** [comment]
Sorry, I don't understand what you want. Can you please provide a full example what you're trying to achieve?
