### ISSUE TITLE
Session Tracking

### ISSUE THREAD

**Issue by devmariodiaz** [WireMock-Net/WireMock.Net#665]
Hello Stef,

Greetings.

I have a quick question.

In WireMock is there any way to manage session tracking?

Ref: https://stackoverflow.com/questions/1740860/http-session-tracking/1740900

**Comment by devmariodiaz** [comment]
Thanks a lot for all @StefH,

I would like to ask you if you could provide me with any examples, how to use Scenarios and States to simulate a session tracking with WireMock.NET? I cannot to find any way doing that using Scenarios and States :(

**Comment by StefH** [comment]
Related to https://github.com/WireMock-Net/WireMock.Net/issues/671 it seems....

Your approach is currently the only one.

I need some time to think of something else..

**Comment by StefH** [comment]
Closing for now.
