### ISSUE TITLE
Example is not working as expected

### ISSUE THREAD

**Issue by devmariodiaz** [WireMock-Net/WireMock.Net#666]
Hello Stef,

Thanks for all your help.

I want to report to you, that this example that you provide me some days ago is not working, is not taking the launchsettings.json parameters, is taking default parameters.

https://github.com/WireMock-Net/WireMock.Net/tree/dc078b57ea463e2c9c7da7f6579af34000596446/examples/WireMock.Net.StandAlone.NETCoreApp

![Screen Shot 2021-10-25 at 4 25 47 PM](https://user-images.githubusercontent.com/54611419/138774319-344c096a-4721-4d42-a3fc-0df4212f0839.png)

Could you please to take a look at this?

**Comment by StefH** [comment]
Closing...
