### ISSUE TITLE
Performance issues working with App Center

### ISSUE THREAD

**Issue by emygg84** [WireMock-Net/WireMock.Net#674]
In my company we are using WireMock.Net + SpecFlow to do automated E2E tests for Android & iOS devices, everything works fine with a small quantity of configuration files (wiremock) and when the tests are executed from the PC of the developers individually but... When AppCenter executes the tests then sometime the server fails to upload some configuration files that are sets dynamically for each scenario. We currently have a lot of configuration files that are uploaded to the server dynamically on each test.

The logs files of the SpecFlow shows that a Post request to upload some configuration files fails and that occurs in a random way only when the tests are executed by the app center.

The wiremock server is running on a docker container and I wan to know is there is a way to do some load balancing to resolve this problem adding more images that share the same dns and also the same disk to store the configuration files?

Or another good idea that can help us to address this problem!.

**Comment by StefH** [comment]
How many mappings do you have when WireMock.Net throws errors?

**Comment by StefH** [comment]
@emygg84 Did you have time yet to get some more details on this?

**Comment by StefH** [comment]
Dear @emygg84, is this issue still valid?

**Comment by StefH** [comment]
Hello @emygg84.

I'll close this issue for now, in case you still need support, reply to this comment, or create a new issue with some more details.
