### ISSUE TITLE
Obsolete documentation (FluentMockServer used in examples is not available any more)

### ISSUE THREAD

**Issue by grzegorz-wolszczak** [WireMock-Net/WireMock.Net#677]
Page https://github.com/WireMock-Net/WireMock.Net/wiki/WireMock-as-a-standalone-process#option-3--coding-yourself uses FluentMockServer in examples, but as far as I understand , it is not available from version 1.3.0, when current version is 1.4.26

Please update code examples with WireMockServer class and related classes

**Comment by StefH** [comment]
Thanks.

It's fixed.

**Comment by grzegorz-wolszczak** [comment]
Thanks for fast response
