### ISSUE TITLE
TTL of Posting request

### ISSUE THREAD

**Issue by andresendava** [WireMock-Net/WireMock.Net#682]
Hi @StefH 

I have the following question.

How long time remains the posting request in WireMock server? ¿Is this time configurable?

Thanks in advance.

**Comment by StefH** [comment]
You mean the mapping ?

Or the request itself (logging) ?

**Comment by andresendava** [comment]
Thanks @StefH Stef for your quick answer again

I talking about the post request the is fetching with the next pattern __admin/request

I my review I found the next command line parameter

MaxRequestLogCount 
RequestLogExpirationDuration

[WireMock-commandline-parameters](https://github.com/WireMock-Net/WireMock.Net/wiki/WireMock-commandline-parameters)

Thanks in advance.

**Comment by andresendava** [comment]
This Issue could be close. Thanks in advance
