### ISSUE TITLE
Trying to compile WireMock.NET in VS for Windows issue

### ISSUE THREAD

**Issue by devmariodiaz** [WireMock-Net/WireMock.Net#687]
Hello Stef,
Hoping that you are doing well.

I'm trying to compile WireMock.NET on Windows, but, I'm getting an error related to FluentBuilder [FluentBuilder.AutoGenerateBuilder] in the BodyModel.cs cs
![Screenshot_217](https://user-images.githubusercontent.com/54611419/142496985-e8a79d62-2a96-42de-8b7a-ee8b90a162f7.png)

dotnet --version
5.0.402

Any idea about this?

**Comment by StefH** [comment]
This is Fluentbuilder is using source generation.

Did you try restarting VS2022/ VS2019 and reloading the project.

**Comment by StefH** [comment]
Hello @devmariodiaz, did you fix this issue on your system?

**Comment by StefH** [comment]
@devmariodiaz I'm closing this issue.
Please reply if you still have issues.
