### ISSUE TITLE
PostWireMockMiddlewareInit not invoked

### ISSUE THREAD

**Issue by jantanis** [WireMock-Net/WireMock.Net#698]
### Describe the bug
PostWireMockMiddlewareInit in registered, but not invoked.

### Expected behavior:
app.Run from PostWireMockMiddlewareInit is triggered AFTER WireMock has processed.

### Test to reproduce
See sample solution: Run and go to http://localhost/test.
[WM.Middleware.zip](https://github.com/WireMock-Net/WireMock.Net/files/7676933/WM.Middleware.zip)

**Comment by StefH** [comment]
Hello @jantanis

The callbacks are **executed**, the breakpoint is triggered.

![image](https://user-images.githubusercontent.com/249938/147974334-6cdcd396-504c-43b2-84dc-82d50590952d.png)

However, I normally use code like this:
![image](https://user-images.githubusercontent.com/249938/147974581-1c757aaf-c69d-4a52-9937-502ec05cdd0c.png)

**Comment by StefH** [comment]
Dear @jantanis, I'm closing this now.
Please reply if you still need help.
