### ISSUE TITLE
wiremock as dotnet tool no ssl possible

### ISSUE THREAD

**Issue by dschmittwilken** [WireMock-Net/WireMock.Net#705]
From the Wiki I could not find out how to enable SSL when using wiremock as .net tool.

I already tried.

dotnet tool run dotnet-wiremock arguments=" --Port 9091 --UseSSL true --ReadStaticMappings true"
and
dotnet tool run dotnet-wiremock arguments=" --Port 9091 --ssl true --ReadStaticMappings true"

**Comment by StefH** [comment]
Hello @dschmittwilken 

The `--UseSSL` does not exists.

You can just provide the url(s) as https:
```
dotnet-wiremock --Urls https://localhost:9091 --ReadStaticMappings true
```

See https://github.com/WireMock-Net/WireMock.Net/wiki/WireMock-commandline-parameters

**Comment by dschmittwilken** [comment]
Works like a charm with SSL using "dotnet tool run dotnet-wiremock arguments=" --Urls https://localhost:9091 --ReadStaticMappings true", thank you very much!
