### ISSUE TITLE
Unable to mock requests to specified url

### ISSUE THREAD

**Issue by Yedidyah27** [WireMock-Net/WireMock.Net#708]
### Describe the bug
I am trying to set up wiremock for substituting responses for http requests made during testing. When I start the wiremock server I initialize it with a specific url it should intercept. I can see in debug that the wiremock server ignores the url I provided and connects to a random localhost port.

Very simple code snippet:
``` c#
var url = "https://test." + env + ".com";
_server = WireMockServer.Start(url);
```
 
I am expecting the wiremock server to intercept requests made to the url I specified but it doesnt.

Am I missing anything?

(project is using .net5)

**Comment by StefH** [comment]
Hello @Yedidyah27,

WireMock.Net cannot just listen to that URL.

You need to start WireMock.Net on https://localhost:80443 for example.

And then you need to make sure that you connect from your client application to that https://localhost:80443 url.

**Comment by Yedidyah27** [comment]
Got it thanks
