### ISSUE TITLE
CORS error trying to consume __admin/mappings

### ISSUE THREAD

**Issue by devmariodiaz** [WireMock-Net/WireMock.Net#711]
Hello Stef,

Happy new year and hoping that you are doing well.

I'm trying to consume __admin/mappings to create new mappings using the method/verb POST and an application developed on React, but I'm getting an error when I send any request. CORS error.

![Screen Shot 2022-01-05 at 3 34 44 PM](https://user-images.githubusercontent.com/54611419/148286539-8ea7daa0-d9b6-4740-8a65-d68cc995fa0f.png)

Any clue what I can do to resolve that?

**Comment by StefH** [comment]
Hello @devmariodiaz,

CORS support is not enabled by default, you can enable it yourself when configuring WireMock Server, like:
``` c#
/* https://stackoverflow.com/questions/31942037/how-to-enable-cors-in-asp-net-core */
            /* Enable Cors */
            settings.AdditionalServiceRegistration = services =>
            {
                services.AddCors(corsOptions =>
                    corsOptions.AddPolicy("MyPolicy",
                        corsPolicyBuilder =>
                        {
                            corsPolicyBuilder
                                .AllowAnyHeader()
                                .AllowAnyMethod()
                                .AllowAnyOrigin();
                        }));

                settings.Logger.Debug("Enable Cors");
            };

            /* Use Cors */
            settings.PreWireMockMiddlewareInit = app =>
            {
                var appBuilder = (IApplicationBuilder)app;
                appBuilder.UseCors();

                settings.Logger.Debug("Use Cors");
            };

            _server = WireMockServer.Start(settings);
```

See also https://github.com/WireMock-Net/WireMock.Net/blob/cors/examples/WireMock.Net.StandAlone.NETCoreApp/Program.cs#L38

**Comment by devmariodiaz** [comment]
Thank you, Stef for your quick answer.

I tried to apply this configuration that you provided, but, it's still sending me the same error related to the CORS error.

We are using our app as a Standalone and as a Service, may be this be the problem?

<img width="825" alt="Screen Shot 2022-01-06 at 7 05 41 AM" src="https://user-images.githubusercontent.com/54611419/148380816-e940662d-e29b-4597-a944-e39987d4ad25.png">

**Comment by StefH** [comment]
I forgot some code.

You need to use the same policy-name:

``` c#
/* https://stackoverflow.com/questions/31942037/how-to-enable-cors-in-asp-net-core */
            /* Enable Cors */
            var policyName = "MyPolicy";
            settings.AdditionalServiceRegistration = services =>
            {
                services.AddCors(corsOptions =>
                    corsOptions.AddPolicy(policyName,
                        corsPolicyBuilder =>
                        {
                            corsPolicyBuilder
                                .AllowAnyHeader()
                                .AllowAnyMethod()
                                .AllowAnyOrigin();
                        }));

                settings.Logger.Debug("Enable Cors");
            };

            /* Use Cors */
            settings.PreWireMockMiddlewareInit = app =>
            {
                var appBuilder = (IApplicationBuilder)app;
                appBuilder.UseCors(policyName);

                settings.Logger.Debug("Use Cors");
            };
```

This works for me:
https://www.w3schools.com/xml/tryit.asp?filename=tryajax_get2
![image](https://user-images.githubusercontent.com/249938/148388805-99a22094-2fd5-4e8f-9399-431eec039ece.png)


-->

![image](https://user-images.githubusercontent.com/249938/148388833-8b93ad1c-d638-482e-a019-fe32be78552a.png)



calling `__amdin/mappings` also works fine:
![image](https://user-images.githubusercontent.com/249938/148389059-632b582c-6a44-4627-9965-b704cb5fb0a6.png)

**Comment by devmariodiaz** [comment]
Thanks a lot for your help, Stef,

Now is working fine for me.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/wiki/Cors

**Comment by StefH** [comment]
@devmariodiaz 
I decided to add Cors support in WireMock.Net server by using a setting `CorsPolicyOptions`.

Can you try preview (1.4.31-ci-15770) ?

``` c#
var settings = new WireMockServerSettings
{
   CorsPolicyOptions = CorsPolicyOptions.AllowAll
};

```

**Comment by devmariodiaz** [comment]
Thanks a lot Stef,

I will test this preview ASAP, I believe this is a great decision.

**Comment by StefH** [comment]
@devmariodiaz 
Did you have time to verify?

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/714
