### ISSUE TITLE
Wiki JsonPartialWildcardMatcher is wrong spelled

### ISSUE THREAD

**Issue by matgenois** [WireMock-Net/WireMock.Net#717]
### Describe the bug
In the wiki, JsonPartialWildcardMatcher is badly spelled and leads to error. Wiki refer to JsonPartialWilcardMatcher (missing a d in Wildcard)

### Expected behavior:
Wiki should refer to JsonPartialWildcardMatcher as stated in code

### Test to reproduce
- 1 Try to use a json with JsonPartialWilcardMatcher and it won't work

Thanks

**Comment by StefH** [comment]
Fixed

**Comment by matgenois** [comment]
Thank you!
