### ISSUE TITLE
Matching WithParam on OData End Points

### ISSUE THREAD

**Issue by christamlyn-bridge** [WireMock-Net/WireMock.Net#72]
Our test is making an HTTP call to an OData end point:

`http://localhost:5021/navision/OData/Company('My Company')/School()?$filter=(substringof(Code, 'WA')`

To match to this I have mocked:
```
 navServer
                    .Given(Request
                    .Create()
                    .WithPath(new WildcardMatcher($"/navision/OData/Company('My Company')/School*", ignoreCase: true))
                    .WithParam("$filter")
                    .UsingGet())
                    .ResponedWithSchoolData();
```

In the tests this is matching on the client request, however if I try and specify the parameter value it fails to match:

```
 navServer
                    .Given(Request
                    .Create()
                    .WithPath(new WildcardMatcher($"/navision/OData/Company('My Company')/School*", ignoreCase: true))
                    .WithParam("$filter", "(substringof(Code, 'WA')")
                    .UsingGet())
                    .ResponedWithSchoolData();
```

Is there any reason why using the value in the WithParam method would cause a mismatch?

Thanks

**Comment by StefH** [comment]
Problem was related to url-encoding.

See new NuGet : https://www.nuget.org/packages/WireMock.Net/1.0.2.10

**Comment by christamlyn-bridge** [comment]
interestingly after upgrading to 1.0.2.10, none of my requests are matching now

**Comment by StefH** [comment]
Can you checkout the example code?

I tried this:
```
server
                .Given(Request
                    .Create()
                    .WithPath(new WildcardMatcher("/navision/OData/Company('My Company')/School*", true))
                    .WithParam("$filter", "(substringof(Code, 'WA')")
                    .UsingGet())
                .RespondWith(Response.Create()
                    .WithBody(@"{ ""result"": ""odata""}"));
```

**Comment by christamlyn-bridge** [comment]
ah I see the difference, on the previous version I found I had to escape the spaces manually in my WilcardMatcher:

`.WithPath(new WildcardMatcher("/navision/OData/Company('My%20Company')/School*", true))`

But with the new module, you can use:

`.WithPath(new WildcardMatcher("/navision/OData/Company('My Company')/School*", true))`

Definite improvement! Thanks

**Comment by StefH** [comment]
Yes indeed. Escaping in your strings is not needed.

If all is fine, you can close this issue ?

**Comment by StefH** [comment]
Thanks for testing. If you have more questions, just ask!
