### ISSUE TITLE
Response Header Content-Length not available when call HEAD Method

### ISSUE THREAD

**Issue by bangush** [WireMock-Net/WireMock.Net#720]
Refer to the Previous Bug #136 and Bug #137. When call HEAD Method the Cotent-Length is not available. 

``` c#
const string responseBody = @"<?xml version=""1.0""?><empty/>";

wireMockServer
.Given
(Request
.Create()
.WithPath("/api")
.UsingPost()
)
.RespondWith(Response
.Create()
.WithStatusCode(HttpStatusCode.OK)
.WithHeader("content-type", "text/xml")
.WithHeader("content-length", responseBody.Length.ToString()) // this line not show during test.
.WithBody(responseBody)
);
```

**Comment by bangush** [comment]
Hint: I randomly check multiple versions, and up-to WireMock.Net Ver 1.0.4.19 work with header contents and return the values as expected. but after that the process is broken.

{
var headers = new Dictionary<string, string>
        {
            { "Accept", "text/html" }, // OK
            { "Connection", "keep-alive" }, // OK
            { "Content-Length", responseBody.Length.ToString() }, // OK
            { "Content-Type", "text/html; charset=utf-8" }, // OK
            { "Date", "Fri, 06 Mar 2019 17:36:11 GMT" }, // OK
            { "Expect", "100-continue" }, // OK
            { "Host", "developer.mozilla.org" }, // OK
            { "If-Modified-Since", "Wed, 21 Oct 2015 07:28:00 GMT" }, // OK
            { "Keep-Alive", "timeout=5, max=1000" }, // OK
            { "Range", "bytes=0-499, -500" }, // OK
            { "Referer", "developer.mozilla.org/en-US/docs/Web/JavaScript" }, // OK 
        **//  { "Transfer-Encoding", "compress" },  // 500 Internal Server Error** 
          { "User-Agent", "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0" }, // OK
            { "Proxy-Connection", "keep-alive" }, // OK
            { "WWW-Authenticate", "Basic YWxhZGRpbjpvcGVuc2VzYW1l" } // OK 
        };
...
...
 .WithHeaders(headers)
...
...
}

**Comment by StefH** [comment]
@bangush 
According to the specs, Head does not have a body.
So also not a content-length.


https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

![image](https://user-images.githubusercontent.com/249938/152831601-b6d17260-6346-42a5-a0f0-e268642265d0.png)

**Comment by textbook** [comment]
As is visible in the quote:

> For example, if a URL might produce a large download, a HEAD request could read its [Content-Length](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length) header to check the filesize without actually downloading the file.

Per [RFC9110](https://www.rfc-editor.org/rfc/rfc9110.html#HEAD), although:

> ...the server **MUST NOT** send content in the response. ... The server **SHOULD** send the same header fields in response to a HEAD request as it would have sent if the request method had been GET.

So although a HEAD response is not _required_  to have a `Content-Length`, it certainly (and despite the lack of actual content) _can_ if that length is known.

**Comment by maoso** [comment]
Hi @StefH,

Is this issue going to be fixed? A head response returns the content-length of the file but WireMock not.

**Comment by dianast31** [comment]
Hi @StefH,

Is this issue going to be fixed? I have the same problem as @maoso. Is there a workaround for this bug?

**Comment by StefH** [comment]
I will have a look if it's possible to support content-lenght for head.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1158

**Comment by dianast31** [comment]
> #1158

Hi @StefH,

Thank you so much; we really need this feature ASAP. Could you please provide an ETA for the next release that will include this fix?

**Comment by StefH** [comment]
Today
