### ISSUE TITLE
Response BodyAsJson with array does not work

### ISSUE THREAD

**Issue by MarwaAloui** [WireMock-Net/WireMock.Net#721]
Hello, i want to configure the response of WirMock as BodyAsJson and inside i have an array of object 
``` json
"Response": {
      "StatusCode": 200,
      "BodyAsJson": [
      {
          "ModelType": "XXX",
          "ModelNumber": "1"
      }
      ]
},
```

when i execute i have an error : 
`{
    "Status": "Object serialized to Array. JObject instance expected."
}`

is it a bug?

**Comment by StefH** [comment]
@MarwaAloui 
I tried to reproduce your error:
``` json
"Response": {  
      "StatusCode": 200,  
      "Headers": {  
        "Content-Type": "application/json"  
      },  
      "BodyAsJson": [  
        {  
          "id": 100,  
          "name": "Sofie",  
          "hasOwner": true,  
          "birthDate": "2019-12-05T11:00:30.573+01:00",  
          "animal": {  
            "id": 1,  
            "name": "Cat"  
          }  
        }  
      ]  
    }
```

However this works fine?
![image](https://user-images.githubusercontent.com/249938/153139302-0892498f-f9b0-4695-901e-ef57aeca04b7.png)

**Comment by MarwaAloui** [comment]
Thank you for your quick response
i retried without  "UseTransformer": true, and it works well.

**Comment by StefH** [comment]
I see.

I'll check the code.

**Comment by StefH** [comment]
It's fixed.

A new version will be released soon.
