### ISSUE TITLE
Adding request-response logging to a file

### ISSUE THREAD

**Issue by ZenwalkerD** [WireMock-Net/WireMock.Net#724]
I am using wiremock.net in my .NET CORE 5 project as shown:

``` c#
server = WireMockServer.Start(new WireMockServerSettings()
            {
                Urls = new[] { WireMockUrl },
                StartAdminInterface = true,
                AllowCSharpCodeMatcher = true
            });

server.Given(Request.Create().WithPath("/hello"))
               .RespondWith(Response.Create()
               .WithStatusCode(System.Net.HttpStatusCode.OK));
```

I want to have a log written to a file; whenever /hello path is hit by any client. How to do this? I searched wiki and also library; i could not find.

Thanks

**Comment by StefH** [comment]
@ZenwalkerD 
Currently there is no logic or callback functionality implemented which allows this.

BTW: your question looks a lot like this one: #723

**Comment by StefH** [comment]
@ZenwalkerD 
Actually there is simple solution.

You can just implement your own logger, like:
https://github.com/WireMock-Net/WireMock.Net/blob/master/examples/WireMock.Net.Service/WireMockLog4NetLogger.cs
And you use the `public void DebugRequestResponse(LogEntryModel logEntryModel, bool isAdminRequest)` to write the requests / responses.
