### ISSUE TITLE
How to match number with JsonPartialWildcardMatcher

### ISSUE THREAD

**Issue by robertmircea** [WireMock-Net/WireMock.Net#725]
I have the following body matcher in json mapping file and I would like to match any number for `price` field. 

```json
    "Body": {
      "Matcher": {
        "Name": "JsonPartialWildcardMatcher",
        "Pattern": {
          "applicationId": "*",
          "currency": "EUR",
          "price": *,
          "externalId": "*",
          "transactionDescription": "*",
        },
        "IgnoreCase": false
      }
    }
```
The file loading crashes with `File xyz.json could not be read. This file will be skipped.` probably because it is not a valid json file. If I specify:
```json
"price": "*"
```
no matching happens (`No matching mapping found`). Using `AllowPartialMapping=false`

**Comment by StefH** [comment]
@robertmircea 
No sorry.

This matcher can only match (at least for now) on string-values. I don't know yet how to implement this logic.

In the meantime, you could try to use the **csharp-code-csharpcodematcher**
[AutoGenerateBuilderSyntaxReceiver](https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching#csharp-code-csharpcodematcher)

**Comment by StefH** [comment]
@robertmircea 
I can fix this by allowing a regular expression:

So in your case:
``` json
    "Body": {
      "Matcher": {
        "Name": "JsonPartialWildcardMatcher",
        "Regex": true, // <--- add this property
        "Pattern": {
          "applicationId": "*",
          "currency": "EUR",
          "price": "^\d*$", // <--- use regex
          "externalId": "*",
          "transactionDescription": "*",
        },
        "IgnoreCase": false
      }
    }
```

**Comment by StefH** [comment]
@robertmircea : Can you please test that preview version to see if this works for you?

**Comment by StefH** [comment]
Merged to main and a new version is released to NuGet.

**Comment by robertmircea** [comment]
For me, I confirm that this release allows me to match numbers using regex expression. Thank you for support.
