### ISSUE TITLE
No password for custom certificate

### ISSUE THREAD

**Issue by arihantjain0894** [WireMock-Net/WireMock.Net#731]
Hi,
I have a scenario where my custom certificate has no password. I am not able to use it, i guess because of the below code.

``` c#
public bool IsDefined =>
      !string.IsNullOrEmpty(X509StoreName) && !string.IsNullOrEmpty(X509StoreLocation) ||
      !string.IsNullOrEmpty(X509CertificateFilePath) && !string.IsNullOrEmpty(X509CertificatePassword);
```
Any suggestion?

**Comment by StefH** [comment]
Hi @arihantjain0894,

Good point.

I think that a simple solution would be to change it to:
``` c#
&& X509CertificatePassword != null;
```
But also I need to add some logic to detect empty pwd.

Which means that if you provide an empty string `""` as X509CertificatePassword, this `IsDefined ` will return `true`.

OR

I could remove the check for X509CertificatePassword here, But also I need to add some logic to detect empty pwd.

**Comment by StefH** [comment]
@arihantjain0894 
Can you try preview version `1.4.36-ci-15933`? (https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions)

**Comment by arihantjain0894** [comment]
@StefH , thanks for the fix. Its working.
Should we remove entire "!string.IsNullOrEmpty(X509CertificatePassword)" or change the X509CertificatePassword != null as suggested earlier?
https://github.com/WireMock-Net/WireMock.Net/pull/732/commits/7f57d0ddbe0d8aa14cd499092f38dce2bd795f57

**Comment by StefH** [comment]
The exception will be like:
`"X509StoreName and X509StoreLocation OR X509CertificateFilePath are mandatory. Note that X509CertificatePassword is optional.`

I think this fine?

**Comment by arihantjain0894** [comment]
My initial thought was to let "X509CertificatePassword" still be mandatory, but including string.Empty as one of the valid password. If we are making Password as optional altogether then we are good.

**Comment by StefH** [comment]
OK

A new version will be released tomorrow.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/732
