### ISSUE TITLE
How best to manage/switch remote configuration for proxying(recording) versus matching(mocking) ?

### ISSUE THREAD

**Issue by PrzemekScott** [WireMock-Net/WireMock.Net#738]
After some local experiments with WM, now I started some with WM running as a Kubernetes pod.
When in local, each time I wanted to use WM for proxying or for matching I was simply restarting it with configuration changed appropriately. Mappings were kept on local folder so sucha a restart wasn’t a problem - mappings were not lost.

Yet now, when WM running as a pod its space for keeping folders/files will be vanished each time WM will be redeployed with changed configuration.  

So, @StefH could you please share if it is possible to change the configuration on the fly? - the /settings endpoint does not reach to Proxy settings.

**Comment by StefH** [comment]
@PrzemekScott 
In case of proxy mode; I could ignore all calls made to `/__admin/***`.

Would that help you?

**Comment by PrzemekScott** [comment]
@StefH 
hm... not sure

your context = thorough knowledge of WM
my context = still very basic knowledge of WM

so can you please elaborate more on your idea?
You mean "ignore all calls made to /__admin/*** " from being saved to mappings? 

P.S. I've tried to change settings on the fly - when WM is running as a pod - with POST /__admin/settings. 
WM is running with "AllowPartialMapping": false, 
so I've sent "AllowPartialMapping": true,
I got response 200 "Status": "Settings updated"
yet when sending GET /__admin/settings 
unfortunately got still "AllowPartialMapping": false

**Comment by StefH** [comment]
What I mean is that when WireMock.Net is running in proxy mode, it should still allow you to change the configuration by allowing calls to `/__admin/settings`. (This requires a change in the code.)

**Comment by PrzemekScott** [comment]
Ok, yes, that would be great. 

Maybe I missconcept something, so please @StefH  correct me.
But I understand that the best way to work with WM when testing is to create mappings (less often usage) during proxying/recording, and then to switch WM to matching mode (most of the time usage).

So I can configure it to work as proxy for recording (example below) - less often:  "WireMockServerSettings": {
    "StartAdminInterface": true,
    "Urls": [
      "http://localhost:8080/"
    ],
    "AllowPartialMapping": false,
    "HandleRequestsSynchronously": true,
    "ThrowExceptionWhenMatcherFails": true,
    **"ProxyAndRecordSettings": {
      "Url": “some url to proxy”,
      "SaveMapping": true,
      "SaveMappingToFile": true**
    }
  }
}


Or I can configure it to work as a matcher (example below) - most of the time:

"WireMockServerSettings": {
    "StartAdminInterface": true,
    "Urls": [
      "http://localhost:8080/"
    ],
    "AllowPartialMapping": false,
    "HandleRequestsSynchronously": true,
    "ThrowExceptionWhenMatcherFails": true,
    **"ReadStaticMappings": true,
    "ProxyAndRecordSettings": {
    }**
  }
}


  When WM is run remotely, as mine, as a Kubernetes pod, deployed from Azure as a web application, when initialised it reads configuration from appsettings.json file. 

But  it would be great to have option to switch between these ^ configurations when service is running, so by the usage of some endpoint, without a need of redeploying WM cause then all files and folders will be vanished, so one would need first to download them, then upload again etc. Well, this downloading and uploading is still doable. 

  Also maybe you see a different way of approaching this case (configuring WM), which I do not see cause still learning about WM options, so please share. Thanks!

**Comment by PrzemekScott** [comment]
Hey @StefH  have you had a chance to work on this ^, or if not when do you think you could? thanks

**Comment by PrzemekScott** [comment]
Hey @StefH . We went with solution of deploying WM with different settings each time its needed.

**Comment by StefH** [comment]
I noticed that when running WM in Proxy, you can GET and UPDATE the settings via the admin interface (WM still responds to calls to the `_admin` endpoint).

However, I found a small bug that not all settings were retrieved.

And there is no way yet to GET or SET the **ProxyAndRecordSettings**, I'll need to update the code to support these settings also.

**Comment by jatin-prusty-travelport** [comment]
@StefH I was checking the preview version and found taht post was able to update the proxy settings correctly. But after that when I try to mock a call I get error. So here is the sequence of steps:
1) Ran the mock server with proxy mode enabled (with ProxyAndRecordSettings)
2) Captured one mappings by calling the proxy URL
3) Used the API to update settings and got rid of ProxyAndRecordSettings
4) Made the same proxy URL call again expecting the response to be served from the mapping
But then I received this error response:
{
    "Status": "Object reference not set to an instance of an object."
}

Can you please check?
cc: @PrzemekScott

**Comment by StefH** [comment]
Please check preview version 1.4.40-ci-16018

**Comment by StefH** [comment]
@jatin-prusty-travelport 
@PrzemekScott 

I think the functionality works fine now:

1. Ran the mock server with proxy mode enabled (with ProxyAndRecordSettings)
2. Captured one mappings by calling the proxy URL
3. Used the API to update settings and got rid of ProxyAndRecordSettings
4. Made the same call again and it's served from the mapping

Please try version `1.4.40-ci-16022`.

**Comment by StefH** [comment]
@jatin-prusty-travelport
@PrzemekScott

Did you have time to test ?

**Comment by jatin-prusty-travelport** [comment]
@StefH I tested the versions today. It works fine in 1.4.40-ci-16018 but it's broken in 1.4.40-ci-16022.
cc: @PrzemekScott

**Comment by StefH** [comment]
Broken means incorrect behavior? 
Or 'Object reference not set to an instance of an object.'?

**Comment by jatin-prusty-travelport** [comment]
In 1.4.40-ci-16022 I see again the error - 'Object reference not set to an instance of an object.'.

**Comment by StefH** [comment]
Cool.

I'll merge this branch today and create a new official version.

**Comment by PrzemekScott** [comment]
Thanks @StefH !
