### ISSUE TITLE
WM is matching during proxy (recording) mode - why?

### ISSUE THREAD

**Issue by PrzemekScott** [WireMock-Net/WireMock.Net#742]
Hey @StefH we have some issue with a working flow for WM. As you may remember from my previous messages, we want to use WM in proxy mode for recording only, so then we could run our tests against that mappings created when the WM is run only in matching mode. 

But what we experienced is that when we are trying to prepare mappings, WM running on proxy mode, the WM is also doing matching with mappings which were created a moment ago. So basically this blocks us totally from recording proper mappings, and with continuing of our testing with the use of WM.

So can you please specify if there is any setting that we need to put a flag on which will block the matching when WM is run in proxy mode, so it will only record mappings. 

If there is no such a setting. Can you please develop it and add, cause it would make the WM more dynamic for different usage scenarios. Thx

**Comment by PrzemekScott** [comment]
I think, our needs are partially similar to this previous question https://github.com/WireMock-Net/WireMock.Net/issues/632

**Comment by StefH** [comment]
I understand your question.

I'll try to investigate the issue.

But please keep in mind that I'm also working on other issues and other projects.

**Comment by PrzemekScott** [comment]
Sure! Thanks for giving the sign :)

**Comment by StefH** [comment]
@PrzemekScott 
About this specific question, I tested this code:
``` c#
var server = WireMockServer.Start(new WireMockServerSettings
        {
            Urls = new[] { "http://localhost:9091/", "https://localhost:9443/" },
            StartAdminInterface = true,
            ReadStaticMappings = false,
            ProxyAndRecordSettings = new ProxyAndRecordSettings
            {
                Url = "http://postman-echo.com/post",
                SaveMapping = true,
                SaveMappingToFile = true
            }
        });
```

And when I do a call to WireMock.Net (using postman to post a body), everytime the proxied endpoint (http://postman-echo.com/post) is hit.

The internal saved mapping  is not used it seems?

Can you tell me your setup ?
Or provide an example program?

**Comment by PrzemekScott** [comment]
@StefH 

This is how the settings looks like:

```
"WireMockServerSettings": {
  "StartAdminInterface": true,
  "Urls": [
    "http://localhost:8080/"
  ],
  "AllowPartialMapping": false,
  "HandleRequestsSynchronously": true,
  "ThrowExceptionWhenMatcherFails": true,
  "ProxyAndRecordSettings": {
    "Url": "https://loremipsum",
    "SaveMapping": true
  }
}
```

And this is how we handel WireMock and a web app:

```
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        private static IHostBuilder CreateHostBuilder(string[] args)
            => Host.CreateDefaultBuilder(args)
                .ConfigureServices((host, services) => ConfigureServices(services, host.Configuration));

        private static void ConfigureServices(IServiceCollection services, IConfiguration configuration)
        {
            services.AddLogging(logging => logging.AddConsole().AddDebug());

            services.AddTransient<IWireMockService, WireMockService>();
            services.Configure<WireMockServerSettings>(configuration.GetSection("WireMockServerSettings"));

            services.AddHostedService<App>();
        }
    }
}
```

I will ask my team mate, Jatin, to comment here, cause he was specifically doing this experiment/testing when he noticed 'matching' happening when proxy settings were ON too. @jatin-prusty-travelport

**Comment by jatin-prusty-travelport** [comment]
@StefH I believe everytime you make a request to http://postman-echo.com/post, some header (like requestId or some other token) always changes and hence you are able to capture all the mappings. This can be verified by checking the generated mappings. But if you blacklist those headers then you can see that it first tries to serve the response from the captured mappings, and it goes to the proxy URL only if a matching mapping is not found.

**Comment by jatin-prusty-travelport** [comment]
Thanks @StefH! I have checked the preview version and it works exactly as we wanted. So in proxy mode it is not serving from the mapping. 
But For wiremock to be more dynamic, I would really like to have a appsetting to define whether we want to enable this feature or not. In some cases people might want it to switch to mock mode when a mapping is captured.
Will leave it upto you to decide. Can you please let us know when you can (update if required and) release this code?

**Comment by StefH** [comment]
@jatin-prusty-travelport 
For enabling / disabling proxy behaviour (by using settings), is described in my last comment here:
https://github.com/WireMock-Net/WireMock.Net/issues/738

**Comment by StefH** [comment]
@jatin-prusty-travelport 
I think I get your last question...

My current solution is to make sure that the priority is used --> the priority from the Proxy mapping is defined in such a way that this get preference over the just created mapping.

I need to think on a good way to change the code to make it switch to mock mode when a mapping is captured...

**Comment by StefH** [comment]
Closing this...
