### ISSUE TITLE
System.ArgumentOutOfRangeException when Timeout.InfiniteTimeSpan used as an argument for IResponseBuilder.WithDelay()

### ISSUE THREAD

**Issue by xzxzxc** [WireMock-Net/WireMock.Net#744]
### Describe the bug
Next code fails with 
`System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'delay')`

``` c#
Response.Create().WithDelay(Timeout.InfiniteTimeSpan);
```

### Expected behavior:
Method `WithDelay` should allow infinite timeout.

### Other related info
WireMock.Net version 1.4.40

**Comment by StefH** [comment]
InfiniteTimeSpan is a long time ;-)
