### ISSUE TITLE
FluentAssertions - assert the server has not received a call 

### ISSUE THREAD

**Issue by MeuLee** [WireMock-Net/WireMock.Net#753]
**Is your feature request related to a problem? Please describe.**
Using `HaveReceived(0).Calls()` throws an exception if no calls have been made.
"Expected StubServer to have been called at address matching the absolute url "https://localhost:62040/path/to/the/resource", but no calls were made."

**Describe the solution you'd like**
`HaveReceived(0).Calls()` should validate that no calls have been made to the stub server, optionally taking into account the specifications such as `.AtAbsoluteUrl()`
I suppose the method was not intended to be used this way, but I think it would be neat to leverage WireMock.FluentAssertions for this kind of tests.
A use case I have in mind is for caching server responses.

**Describe alternatives you've considered**
I am currently using the following - just FluentAssertions, not the WireMock version.
```cs
StubServer.LogEntries.Should().NotContain(logEntry => logEntry.RequestMessage.Path == "/path/to/the/resource");
```

**Comment by StefH** [comment]
@MeuLee 
Good point. I'll take a look.

**Comment by StefH** [comment]
Will be fixed in new version.
