### ISSUE TITLE
Is there an equivalent of withChunkedDribbleDelay?

### ISSUE THREAD

**Issue by jimiscott** [WireMock-Net/WireMock.Net#754]
Hello, is there an equivalent of the above (from wiremock.org)?

**Comment by StefH** [comment]
@jimiscott
Not yet.

Maybe you can take a look at the source code and make a PR?

**Comment by jimiscott** [comment]
@StefH Thanks for the reply.

A cursory glance means that I would probably need to change WireMock.Owin.Mappers.ResponseMapper and ResponseMessage.

To do this properly a possible introduction some sort of ResponseDelegate handler pattern....which would remove all that conditional logic.

**Comment by StefH** [comment]
Hello @jimiscott.
Did you have time to work on this?

**Comment by StefH** [comment]
@jimiscott 
I'm closing this issue for now, if you want this functionality, you can create a PR.
