### ISSUE TITLE
WireMockConsoleLogger aggregate exception handling bug?

### ISSUE THREAD

**Issue by siewers** [WireMock-Net/WireMock.Net#756]
It seems like the handling of the aggregate exception is wrong.

https://github.com/WireMock-Net/WireMock.Net/blob/d7173d34a3da7f828a0aa706c5283badf2d43da0/src/WireMock.Net/Logging/WireMockConsoleLogger.cs#L50-L57

Shouldn't it be like this?
```cs
ae.Handle(ex => 
{ 
    Console.WriteLine(Format("Error", "Exception {0}", ex.Message)); // ex instead of exception
    return true; 
}); 
```

**Comment by StefH** [comment]
@siewers 
I think you are correct. Can you make a PR?
