### ISSUE TITLE
Wrong mapping of method GetAdminMappingsAsync from IWireMockOrgApi

### ISSUE THREAD

**Issue by marspox** [WireMock-Net/WireMock.Net#764]
### Describe the bug
After executing  `await RestClient.For<IWireMockOrgApi>("http://127.0.0.1:8080").GetAdminMappingsAsync(default, default);`
I'm getting exception  "Method 'GetAdminMappingsByStubMappingIdAsync': unable to find a [Path(\"stubMappingId\")] property or parameter for the path placeholder '{stubMappingId}'"

### Expected behavior:
It should be executed GetAdminMappingsAsync

### Other related info
I'm using WireMock.Org.RestClient with version 1.5.0

**Comment by StefH** [comment]
#765

**Comment by StefH** [comment]
@marspox 
You can try preview version `WireMock.Org.RestClient.1.5.0-ci-16263`.
