### ISSUE TITLE
JsonMatcher should serialize enum as text if such attribute is defined

### ISSUE THREAD

**Issue by FredCni** [WireMock-Net/WireMock.Net#768]
### Describe the bug
The JsonMatcher does not respect the enum serialization attributes

### Expected behavior:
The matcher should match on a json containing the enum as a string instead of a number

### Test to reproduce
```
public enum MyType
{
	[JsonConverter(typeof(StringEnumConverter))]  // newtonsoft
	Type1
}

public class Request
{
	public MyType MyType { get; set; }
}

var request = new MyRequest { MyType = MyType.Type1 };

```

In the WireMock Given definition:
```
.WithBody(new JsonMatcher(MatchBehaviour.AcceptOnMatch, request, true))
```

The request won't be matched because the json matcher (see its private _valueAsJToken) tries to match on MyEnum = 0, instead of MyType1

### Other related info
What serializer is used? Is there a way to tweak it so it serializes enums as strings?

**Comment by StefH** [comment]
@FredCni 
Can you make a full working example project, or a PullRequest with a new unit-test which demonstrates this error?

**Comment by StefH** [comment]
#770

**Comment by StefH** [comment]
@FredCni 
The attribute is wrongly placed. Use this:

``` csharp
[JsonConverter(typeof(StringEnumConverter))]
public enum MyType
{
	Type1
}
```

**Comment by FredCni** [comment]
Thank you, that fixed it!
