### ISSUE TITLE
Update Scriban.Signed to support more functions, e.g math.random

### ISSUE THREAD

**Issue by dmytro-pryvedeniuk** [WireMock-Net/WireMock.Net#776]
**Is your feature request related to a problem? Please describe.**
I need to generate a random value in the response. The Scriban function _{{math.random 1 1000}}_ results in the error "The function `math.random` was not found". WireMock.Net 1.5.2 uses Scriban.Signed 3.3.2, but referencing Scriban.Signed 5.5.0 helps to resolve it.

**Describe the solution you'd like**
I would like WireMock.Net (and the corresponding docker image) to use the latest version of Scriban.Signed, so an extra reference of Scriban.Signed is not needed.

**Describe alternatives you've considered**
Reference Scriban.Signed separately, build own docker image.

**Is your feature request supported by [WireMock (java version)](https://www.wiremock.org)? Please provide details.**
No idea :)

**Additional context**

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/777

**Comment by StefH** [comment]
@dmytro-pryvedeniuk 
A new NuGet + docker will be released soon.
