### ISSUE TITLE
WireMock not working when attempting to access from anything other than localhost.

### ISSUE THREAD

**Issue by Curtis004** [WireMock-Net/WireMock.Net#78]
Hi there,

I've run into an issue when trying to access a wiremock mock instance running on 0.0.0.1 FROM an application running on 0.0.0.2 using http://0.0.0.1/things/other-things.

Can be replicated much simpler by trying to access a wiremock standalone instance on your local machine on your IP rather than localhost.

I'm getting a 400 Invalid Hostname.

Tried this using the java version of wiremock standalone also and it working fine.

Any ideas?

Cheers,

Josh

**Comment by Curtis004** [comment]
Just seen https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Server/FluentMockServer.cs#L156.

I'm using a dynamic port meaning that it's hardcoding the URL to be localhost.

Will continue digging.

**Comment by Curtis004** [comment]
Whoops.

**Comment by StefH** [comment]
You could use 'http://*:80' for an url? Which makes WireMock listen on all ip?

**Comment by Curtis004** [comment]
Yeah basically the second one. I just used PortUtil to get an available port and constructed a Url out of that port and a the host of the wiremock servers IP. Perhaps http://*:port would be more appropriate in the FluentMockServer.

Will close though as I don't think using PortUtil directly is a "bad" thing.
