### ISSUE TITLE
Matching for x-www-form-urlencoded request body

### ISSUE THREAD

**Issue by KyryloAntoshyn** [WireMock-Net/WireMock.Net#782]
Hi!

I need to mock POST request with `x-www-form-urlencoded` body: `param1=value1&param2=value2&param3=value3&param4=value4`. I've been reading wiki pages regarding request matching but haven't found any option for matching URL encoded body. Is it possible to achieve with `WireMock.Net`. If yes, how can I implement it?

Thanks in advance!

**Comment by StefH** [comment]
@KyryloAntoshyn 
Did you just try this:


For the body:
``` json
"Body": {
            "Matcher": {
                "Name": "ExactMatcher",
                "Pattern": "param1=value1&param2=value2&param3=value3&param4=value4"
            }
        }
```

And for the header:
``` json
"Headers": [
      {
        "Name": "Content-Type",
        "Matchers": [
          {
            "Name": "WildcardMatcher",
            "Pattern": "x-www-form-urlencoded",
            "IgnoreCase": true
          }
        ]
      }
    ]
```

**Comment by KyryloAntoshyn** [comment]
Thanks, it works fine for me!
