### ISSUE TITLE
Exchange json serializer

### ISSUE THREAD

**Issue by LadislavPataki** [WireMock-Net/WireMock.Net#786]
Is there a possibility to exchange the json serializer from Json.NET to System.Text.Json? I would like to use BodyAsJson method to create response or at least extend it somehow. Could you help me with that? Thanks.

**Comment by StefH** [comment]
This will be difficult because Newtonsoft is also used for replacing values in json using templating.

But it depends on how exactly you want to use `BodyAsJson` and  what you expect from it. Maybe adding a optional parameter to that method to indicate that you want to use System.Text.Json?

**Comment by LadislavPataki** [comment]
That would be sufficient. But this way I would have to pass the serializer options every time. For now I'm using an extension method. I was just wondering if it's even possible. Thanks for your reply.

**Comment by StefH** [comment]
Can you provide that extension method?

**Comment by LadislavPataki** [comment]
The extension method.
`public static class JsonSerializerExtensions
{
    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.CamelCase) },
        PropertyNameCaseInsensitive = true
    };

    public static T? Deserialize<T>(this string json) => JsonSerializer.Deserialize<T>(json, SerializerOptions);

    public static T? Deserialize<T>(this string json, JsonSerializerOptions serializerOptions) =>
        JsonSerializer.Deserialize<T>(json, serializerOptions);

    public static string Serialize<TValue>(this TValue value) => JsonSerializer.Serialize(value, SerializerOptions);

    public static string Serialize<TValue>(this TValue value, JsonSerializerOptions serializerOptions) =>
        JsonSerializer.Serialize(value, SerializerOptions);
}`


Usage:
`WireMockServer
            .Given(Request.Create()
                .UsingPost()
                .WithPath("..."))
            .AtPriority(LowPriority)
            .RespondWith(Response.Create()
                .WithSuccess()
                .WithBody(Fixture.Create<Response>().Serialize()));`

**Comment by StefH** [comment]
I see. I'll check if this can be added.

Note that I also started a new project https://github.com/StefH/JsonConverter which could maybe solve these issues.

**Comment by StefH** [comment]
@LadislavPataki 

See this preview version (`1.5.3-ci-16370`) where you can provide a different JsonConverter when using `WithBody`:
``` c#
public IResponseBuilder WithBody(object body, IJsonConverter converter, IJsonConverterOptions? options = null)
```

For implementations for **IJsonConverter**, see https://github.com/StefH/JsonConverter.

(how to install preview version: see https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions)

**Comment by StefH** [comment]
@LadislavPataki 
Did you have time to test this?

**Comment by LadislavPataki** [comment]
Hi @StefH , I'm sorry I didn't have time for this. I'll give it a try at the weekend.

**Comment by StefH** [comment]
@LadislavPataki 
Did you already have time to test it?

**Comment by LadislavPataki** [comment]
Hi @StefH, I'm not able to find version (1.5.3-ci-16370). Am I doing something wrong?

![image](https://user-images.githubusercontent.com/12115874/186148764-a5e86864-2b6e-4f59-9d65-66d2991b6d5d.png)

**Comment by StefH** [comment]
That version is already deleted I think.

Please try this one:
1.5.3-ci-16393

**Comment by StefH** [comment]
Yes

For all implementations, see https://github.com/StefH/JsonConverter 

I'll close it this and release a new official NuGet soon.
