### ISSUE TITLE
Request body is missing in generated pact file for requests that include matching on request body

### ISSUE THREAD

**Issue by shack05** [WireMock-Net/WireMock.Net#788]
### Describe the bug
The request body is missing in generated pact file for requests that include matching on request body.
More specifically, I am using the JsonPartialMatcher.

### Expected behavior:
The generated pact file includes the expectations of the request body as specified by the matchers used in the wiremock scenario.

### Test to reproduce

``` CSharp
server
   .WithConsumer("Consumer1")
   .WithProvider("Provider1");

server
   .Given(Request.Create().UsingPost().WithPath("/foo")
      .WithBody(new JsonPartialMatcher(@"{ ""name"": ""john"" }")))
   .WithTitle("Example1")
   .RespondWith(Response.Create().WithStatusCode(201)));

server.SavePact("...")
```

I'm not sure what the expected pact should look like, but I imagine request body should be included in some way.
The actual pact file is:
``` json
{
   "consumer": {
      "name": "Consumer1"
   },
   "interactions": [
      {
         "providerState": "Example1",
         "request": {
            "method": "POST",
            "path": "/foo",
         },
         "response": {
            "status": "201",
         } 
      }
   ],
   "provider": {
      "name": "Provider1"
   }
}
```

### Other related info
WIremock version - 1.5.3-ci-16331 (from #784).

**Comment by StefH** [comment]
The only possible solution would be that I deserialize the value from the matcher (`@"{ ""name"": ""john"" }"`), so that the pact could be:

``` json
{
   "consumer": {
      "name": "Consumer1"
   },
   "interactions": [
      {
         "providerState": "Example1",
         "request": {
            "method": "POST",
            "path": "/foo",
            "body": {
              "name" : "john"
            }
         },
         "response": {
            "status": "201",
         } 
      }
   ],
   "provider": {
      "name": "Provider1"
   }
}
```

Another option would be that you can add an example body like:
``` c#
server
   .Given(Request.Create().UsingPost().WithPath("/foo")
      .WithBody(new JsonPartialMatcher(@"{ ""name"": ""john"" }"))).WithExample( ... todo ...) 
```

**Comment by StefH** [comment]
@shack05 
Can you try preview version 1.5.3-ci-16359 ?

**Comment by shack05** [comment]
Hi @StefH, thank you, preview 1.5.3-ci-16359 works like a charm.

**Comment by StefH** [comment]
@shack05 Thanks for testing.
For now use the preview, in some time I'll release a new official.
