### ISSUE TITLE
How to specify response headers using json file?

### ISSUE THREAD

**Issue by rosemaryehlers** [WireMock-Net/WireMock.Net#791]
https://github.com/WireMock-Net/WireMock.Net/wiki/Stubbing
The wiki section on Stubbing shows how to specify headers for a response using code, but not how to specify them if using a json file for configuration. Could that be added? Seems like an oversight in documentation.

**Comment by StefH** [comment]
@rosemaryehlers 
I've updated that page.

Please note that when you use the C# mapping, you can always generate the json mappings using the SaveStaticMappings method:
https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Server/WireMockServer.Admin.cs#L112


See also here: [Admin-API-Reference](https://github.com/WireMock-Net/WireMock.Net/wiki/Admin-API-Reference)

**Comment by rosemaryehlers** [comment]
Thank you!
