### ISSUE TITLE
Why does Dispose not wait for HttpServer to actually stop?

### ISSUE THREAD

**Issue by emilpeder** [WireMock-Net/WireMock.Net#792]
In the WireMockServer class:
https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Server/WireMockServer.cs

The Dispose method calls `_httpServer?.StopAsync();` must does not wait for this operation to complete. Is there any reason for that?

On the contrary, the Stop method does wait.

If we want to make sure the WireMockServer is fully stopped and disposed we therefore need to call both Stop and then Dispose, is that correct?

**Comment by StefH** [comment]
@emilpeder 
There's no specific reason for that, other that dispose normally only cleans the resources.

But I could call Stop first.

For now you indeed need to call Stop and then Dispose it.

**Comment by emilpeder** [comment]
All right. For us this was a source of confusion, since we ended up with race conditions where sometimes tests failed because the HttpServer inside WireMock was still serving requests although we had disposed the WireMockServer instance.
Thanks for the clarification.
