### ISSUE TITLE
.net6 version

### ISSUE THREAD

**Issue by leozin** [WireMock-Net/WireMock.Net#807]
Hi, I have come from Java background and now that I moved to another company, I'm using loads of .NET.

I always loved WireMock and I wanted to use in one project, however it seems it is not supported by .net6.

Are there any plans to create a version which would be compatible with .net6?

Thanks

**Comment by StefH** [comment]
.NET 6 is supported:

![image](https://user-images.githubusercontent.com/249938/189188946-33bb4bcb-3c1b-4061-8441-ed6798b95206.png)

**Comment by StefH** [comment]
But I will create also a .NET 6 version.

**Comment by leozin** [comment]
Thanks for that Stef!
See, I'm trying to download it via VS2022 and I can see only this version:
<img width="939" alt="image" src="https://user-images.githubusercontent.com/1276142/189191106-7e6c074e-3a0e-418a-8dae-fc50be192bec.png">
Maybe I'm using the wrong source?

**Comment by StefH** [comment]
Indeed, that's a very old version. Maybe try refreshing?

**Comment by leozin** [comment]
It worked now :) I've added nuget.org as a source and I've changed the source when browsing the package, then it found the latest one with the nice icon etc.

Thanks for the help sir :)
