### ISSUE TITLE
Implementing WireMock.NET with appium for mobile automation testing

### ISSUE THREAD

**Issue by mikebgrep** [WireMock-Net/WireMock.Net#808]
I search over the internet, but I didn't find a good tutorial how to set up WireMock.NET to work with appium to mock API request from mobile app backend. I think first I need to set up an SSL certificate local on my machine and after this to use the ProxySettings to mock the response of the mobile app API. Any help are  welcomed or if any know some article online how can I configure the library.

**Comment by StefH** [comment]
The purpose of WireMock.Net is to replace the real backend.

1. Configure / create SSL (if needed)
2. Start WireMock.Net
3. Add mappings
4. Configure your app to connect to the url where wiremock.net is running


General idea:

**Go from this:**
![image](https://user-images.githubusercontent.com/249938/189731604-6efdda0e-0186-407a-8e94-78a14d6830f2.png)


**To this:**
![image](https://user-images.githubusercontent.com/249938/189731836-731a2f5b-c6c5-42e2-8cd7-117aaa56cfaa.png)

**Comment by mikebgrep** [comment]
Thank you for the answer. So I need first to set SSL certificate to can connect to https:
1. https://github.com/WireMock-Net/WireMock.Net/wiki/Using-HTTPS-(SSL)
I need to add mapping like so:
2.https://github.com/WireMock-Net/WireMock.Net/wiki/WireMock-as-a-standalone-process#option-3--coding-yourself
And finally, I need to configure connection to the app:
3. https://github.com/WireMock-Net/WireMock.Net/wiki/Using-WireMock-in-UnitTests
Please tell me if this is the right steps.
Also do installation of the SSL cert for MAC is same as Linux.

**Comment by StefH** [comment]
I think that should be it indeed, however I don't know exactly how your setup is.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/issues/645

**Comment by StefH** [comment]
I'm closing this issue for now.

If there are any Appium specific steps to take, I can create a new WIKI page, but I think that the general idea on how to use WireMock.Net is the same for all integrations.

Else, please create a new issue with a wiki-page proposal on this topic.
