### ISSUE TITLE
Is it possible to start a WireMockServer with http and https without specifying a port?

### ISSUE THREAD

**Issue by zidad** [WireMock-Net/WireMock.Net#811]
This only starts 1 the HTTPS url:
`var server1 = WireMockServer.Start(port: null, ssl: true);
`
And this requires me to specify ports:
```
var server2 = WireMockServer.Start(new WireMockServerSettings
{
    Urls = new[] { "http://localhost:9091", "https://localhost:9443" }
});
```
so something like this?
```
var server2 = WireMockServer.Start(new WireMockServerSettings
{
    Urls = new[] { "http://localhost:null", "https://localhost:null" }
});
```

**Comment by StefH** [comment]
@zidad 
This is not yet possible, I'll look into this.

**Comment by StefH** [comment]
@zidad 
You can try preview version `1.5.6-ci-16455` (https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions)

And use it like:
``` c#
var httpAndHttpsFree = WireMockServer.Start(new WireMockServerSettings
{
  HostingProtocol = HostingProtocol.HttpAndHttps,
});
```

**Comment by StefH** [comment]
@zidad, did you have time to test this?

**Comment by zidad** [comment]
Hi @StefH, testing it as you typed this comment :)... just a sec

**Comment by zidad** [comment]
@StefH it works for me, many thanks!

**Comment by StefH** [comment]
Thanks for testing.

I'll merge this PR.

Note that in the final version, the enum will be named `HostingScheme`/

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/818
