### ISSUE TITLE
WithHeader cannot handle multiple requests with the same header key values

### ISSUE THREAD

**Issue by robvangeloven** [WireMock-Net/WireMock.Net#814]
When using the assertion "WithHeader" it will fail if there are multiple requests with the same header value (e.g. "Accept"):

```csharp
Server.Should().HaveReceivedACall().WithHeader("Authorization", $"Bearer xxxxxxx");
```
This is because there is a ToDictionary in the WithHeader function that doesn't take into account that multiple calls might have been made before the assert fires.

**Comment by StefH** [comment]
@robvangeloven 

I think I've fixed both issues (this & _callscount).

Can you please test preview version `1.5.6-ci-16474`?

(https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions)

https://github.com/WireMock-Net/WireMock.Net/pull/816

**Comment by StefH** [comment]
@robvangeloven 

Did you have time to validate?

**Comment by robvangeloven** [comment]
@StefH  Sorry, only now have time to test. The package version you mention is (no longer) available. Which version should I take for testing?

**Comment by StefH** [comment]
can you please try `16510`?

**Comment by robvangeloven** [comment]
Tried it and failed, decompilation seems to show that the code isn't merged into that branch yet. Is that possible?

**Comment by StefH** [comment]
Sorry, wrong branch.

This id: 16511 should be it.

**Comment by StefH** [comment]
@robvangeloven 
Thanks for testing.

Can you please take a look at this unit test file?
https://github.com/WireMock-Net/WireMock.Net/pull/816/files#diff-e73254164873009a752dfd094e87fa8aae2d0c6c0c0b7ebe3b6d2f2b23b287c8

See line 463.

**Comment by robvangeloven** [comment]
> @robvangeloven Thanks for testing.
> 
> Can you please take a look at this unit test file? https://github.com/WireMock-Net/WireMock.Net/pull/816/files#diff-e73254164873009a752dfd094e87fa8aae2d0c6c0c0b7ebe3b6d2f2b23b287c8
> 
> See line 463.

I've checked the unit test, but that one doesn't actually check any headers?

**Comment by StefH** [comment]
Correct.

I did combine both your issues into 1 PR.

And I think both issues are solved.

In case you still have an issue, please provide a unit test.

**Comment by robvangeloven** [comment]
Yes, retested everything and both issues are fixed!

**Comment by StefH** [comment]
Thanks for retesting. A new NuGet version will be released this weekend.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/816
