### ISSUE TITLE
Why does UsingMethod check _callscount?

### ISSUE THREAD

**Issue by robvangeloven** [WireMock-Net/WireMock.Net#815]
When making this call:
```csharp
                ._wireMockFixture
                .Server
                .Should()
                .HaveReceived(1)
                .Calls()
                .AtUrl(mockUrl)
                .And
                .UsingPost();
```

My expectation is that this will work, but I get the error: 
Expected _wireMockFixture.Server to have been called using method "POST", but didn't find it among the methods {"GET", "POST", "POST"}.

However, I'm trying to check that there was a singular call that matches the specifics of the assert. And there is, but the UsingPost also checks the _callsCount for number of "POST" used.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/816
