### ISSUE TITLE
How can I have the latest version of admin api OpenApi (swagger) file ?

### ISSUE THREAD

**Issue by itsoli91** [WireMock-Net/WireMock.Net#825]
Hi,
How can I have the latest version of admin api OpenApi (swagger) file ?
Currently in Wiremock.net docs you are pointing to a out dated link (https://app.swaggerhub.com/apis/StefHeyenrath/WireMock/1.4.24)
How can I have the latest version?

**Comment by StefH** [comment]
There is a more updated version : https://app.swaggerhub.com/apis/StefHeyenrath/WireMock/1.4.7

However, not all 1.5.x changes are defined there.

**Comment by itsoli91** [comment]
Thanks
Is there any way that I can generate that myself?
Or it should be created manually?

**Comment by StefH** [comment]
It cannot be generated.

It's just a static document which I try to keep in sync with all the functionality in WireMock.Net

Please also take a look at the wiki : https://github.com/WireMock-Net/WireMock.Net/wiki/Admin-API-Reference

Are all questions resolved, can I close this issue ?
