### ISSUE TITLE
Dynamic Body not to be cached when a Func is used to created the body

### ISSUE THREAD

**Issue by paulmctigue** [WireMock-Net/WireMock.Net#826]
I'm using wirenet.net as a standalone process. The response func code below loads an existing file from disk, mutates the string and return it to the user. In my case it mutates all the dates relative to the todays date.

Because it a dynamics response I don't want the response to be cached. Currently (version 1.5.6), I think, the behaviour is caching the response every time its invoked increasing the memory on each request.

``` c#
server.Given(Request.Create()
	.WithPath($"/someurl/")
	.UsingPost())
	.RespondWith(Response.Create()
		.WithBody(req =>
		{
			var xml = File.ReadAllText($"./myxmlfile.xml");
		
			xml = MutateString(xml);
			return xml;
		})
	.WithStatusCode(200)
	.WithHeader("Content-Type", "application/xml"));
```

**Comment by StefH** [comment]
I'm not sure if there is caching when you use a Func to define your response.

Caching can only be enabled for `WithBodyFromFile`.

Can you please double?

**Comment by StefH** [comment]
@paulmctigue 
I did add a extra unit test: https://github.com/WireMock-Net/WireMock.Net/pull/828 which shows that it works correct.

**Comment by paulmctigue** [comment]
@StefH It always return the correct response string for the request. That bit is fine. However memory is increased for each new string that is returned. I'll double check it now

**Comment by StefH** [comment]
Yes I can understand that the memory is increased because the return value from that Func is a string, and this is saved internally.

However I think that this is only kept in memory for logging the request. So cleaning the logging could help, or I can investigate if in case it's a Func, the response is not saved to the logging.

**Comment by paulmctigue** [comment]
Yes its the log entries that are consuming the memory - this object WireMock.Util.BodyData. 
I didn't see DeleteLogEntry method.

```
 foreach (var log in logs)
  {
      server.DeleteLogEntry(log.Guid);
  }
```

This solves the issue.

**Comment by paulmctigue** [comment]
Maybe have a global setting to opt of this type of logging when setting up the server (in WireMockServerSettings). 
Is the internal logging separate for the general logging because using WireMockNullLogger wouldn't help in this circumstance?

**Comment by StefH** [comment]
Yes a good idea.

I'll see if this can be added, however, it will take some time because I first want merge some other PR's.

**Comment by StefH** [comment]
@paulmctigue 
You can now opt-out using `DoNotSaveDynamicResponseInLogEntry` = `true`

Preview version : `1.5.7-ci-16532`

https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by paulmctigue** [comment]
@StefH 

Tested this and the memory kept on increasing. 

```
<PackageReference Include="WireMock.Net" Version="1.5.7-ci-16532" />

settings.DoNotSaveDynamicResponseInLogEntry = true;
server = WireMockServer.Start(settings);

```
Are there log entries for request as well as responses?

**Comment by StefH** [comment]
A log entry defines the request AND the response.

So the memory will increase, but not as much as before (in case you had big xml-strings to return).

If you do not want log entries at all, you can set the `MaxRequestLogCount` to `0` in the settings.

**Comment by StefH** [comment]
@paulmctigue 
Is the explanation sufficient?

**Comment by StefH** [comment]
merged
