### ISSUE TITLE
How I can register my own Handlebars Helper

### ISSUE THREAD

**Issue by THenryT** [WireMock-Net/WireMock.Net#829]
I am trying to create a dynamic JWT token in response. I know Wiremock.NET does not support it, and if it is possible to that I can create a handlebars helper to generate a jwt token for example {{Jwt iss="localhost:9001"}} and then the response will return a jwt token?

**Comment by StefH** [comment]
@THenryT 
This is indeed possible, you can call your handlebars registration code in the **WireMockServerSettings** : **HandlebarsRegistrationCallback**.

Example:
``` c#
var server = WireMockServer.Start(new WireMockServerSettings
{
	
	HandlebarsRegistrationCallback = (handlebarsContext, fileSystemHandler) =>
	{
		// var transformer = new CustomNameTransformer();
		// handlebarsContext.RegisterHelper(transformer.Name, transformer.Render); TODO
	}
});
```
