### ISSUE TITLE
Reset single scenario using HTTP request

### ISSUE THREAD

**Issue by iparry7979** [WireMock-Net/WireMock.Net#833]
I am running WireMock as a standalone app.

Regarding resetting scenarios: I am able to reset all scenarios using an empty POST request such as: POST /__admin/scenarios/reset.

However, it fails when I try to reset a single scenario using an empty PUT request for example: PUT /__admin/scenarios/my_scenario/state

According to the documentation [here](https://wiremock.org/docs/stateful-behaviour/) this should work in the java version. Is this implemented in the C# version? If so am I doing something wrong to reset a single scenario?

**Comment by StefH** [comment]
Hello @iparry7979,

This is not yet implemented in the current version, however you can try a preview version which supports:
- DELETE to `/__admin/scenarios/ABC`
- POST to `/__admin/scenarios/ABC/reset`

Where `ABC` is the name from the scenario.


Preview version = "1.5.8-ci-16566".
Info: https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/834

**Comment by StefH** [comment]
@iparry7979 did you have to time to verify this logic in the preview NuGet ?

**Comment by StefH** [comment]
@iparry7979 Did you have time to test this?

**Comment by iparry7979** [comment]
@StefH Please disregard the second part of my comment above. I had updated Wiremock.Net.Standalone but not WireMock.Net. When I updated the package the POST to /__admin/scenarios/Scenario1/reset worked as expected in  version 1.5.8-ci-16566.

**Comment by StefH** [comment]
@iparry7979 Thanks for testing. I'll merge PR to master en close this issue.
