### ISSUE TITLE
Creating a request with OData parameters that includes a comma

### ISSUE THREAD

**Issue by loekensgard** [WireMock-Net/WireMock.Net#835]
Hi, I'm trying to create a wiremock response and request that matches on an OData query. 

I'm trying to create a basic request like this:

```csharp
public void SetUp(string body, string path) 
{
    var response = Response
       .Create()
       .WithBody(body)
       .WithHeader("content-type", "application/json; charset=utf-8")
       .WithStatusCode(200);
    
    var request = Request
       .Create()
       .WithPath(path)
       .WithParam("$filter", "startswith(name,'testName')")
       .UsingGet();
       
    _server.Given(request).RespondWith(response); 
}
```

I'm then faced with a problem where the response is returned as a partial match because of the request query, and if I inspect the query later on it appears as two queries (separated by the comma I guess). 
![image](https://user-images.githubusercontent.com/10920800/197513006-14d42b38-b411-4118-9029-9148e16e3903.png)

Is there anything I can do to make sure that the query-value is not split by the comma?

**Comment by StefH** [comment]
Hello @loekensgard 

By default, the application does split on `&`, `;` and `,`.

However I've changed this.


In the settings, set the value `QueryParameterMultipleValueSupport` to a desired value.

This new functionality is in the preview version `1.5.8-ci-16573`.

(https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions)

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/836

**Comment by StefH** [comment]
@loekensgard Did you have time to test this preview version?

**Comment by StefH** [comment]
@loekensgard Can you please test this?

**Comment by loekensgard** [comment]
@StefH 
Hi, sorry for my late reply. 
I did not get it to work, I tried to specify the QueryParameterMultipleValueSupport but it did not change the output for me. I ended up URL encoding my query params and then it worked without using the preview version. 😄
