### ISSUE TITLE
Support for .net6.0 on nuget package

### ISSUE THREAD

**Issue by allancascante** [WireMock-Net/WireMock.Net#841]
I tried creating a new console app using .net6.0 as framework and adding the nuget package for WireMock.Net but the version 202211019.10119.137 that gets installed shows a warning saying .net6.0 might not be compatible. I checked the sources and I see .net6.0 build config is there and I downloaded it and build it and the support for .net6.0 out of the source code seems to be ok. Is it .net6.0 officially supported? is there a problem with the latest nuget version? I am ok adding the compiled version manually, but I would say it is better to have .net6.0 support out of nuget directly; I am trying to drive usage of this lib for our project and having to manually add the dependencies might add up some resistance.

![image](https://user-images.githubusercontent.com/755488/199042162-80ae541b-b6c9-4014-8851-b3590e914714.png)

**Comment by StefH** [comment]
That's a strange version.

Did you download from nuget?

**Comment by allancascante** [comment]
I did a Package-Install WireMock.Net on the nuget console without any version.

**Comment by allancascante** [comment]
I tried providing the version and it worked, Installing NuGet package WireMock.Net 1.5.9. NuGet\Install-Package WireMock.Net -Version 1.5.9

**Comment by StefH** [comment]
Very strange. I wonder where you got that version? Via a different package provider?
