### ISSUE TITLE
Disable debug logging in WireMock dotnet tool

### ISSUE THREAD

**Issue by wolf8196** [WireMock-Net/WireMock.Net#844]
Hi.
Is there a way to set log level in WireMock dotnet tool to disable debug messages?
Or disable logging entirely?
It's useful to see request/response when you are setting everything up, but once that's done, those logs are just spam.

From what I understand the logger currently is created in Program.cs with debug level & passed into StandAloneApp logic.
https://github.com/WireMock-Net/WireMock.Net/blob/49b29d74dcc54171a6bb31817cf305a06e1f1018/src/dotnet-WireMock.Net/Program.cs#L23

And here
https://github.com/WireMock-Net/WireMock.Net/blob/49b29d74dcc54171a6bb31817cf305a06e1f1018/src/WireMock.Net/Settings/WireMockServerSettingsParser.cs#L65

The "logger is not null" check will always be true & just reassign the logger, without possibility to override it with console arguments.
And also there is only check for WireMockConsoleLogger, and no way to use the WireMockNullLogger, that probably disables the logging.

Please let me know if I missed something, or of any other way to get rid of request/response logging.
Thank you

**Comment by StefH** [comment]
@wolf8196 
I understand your question, and I've added support for WireMockNullLogger in the command line tool.

Please try preview version: `1.5.9-ci-16630`

(https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions)

**Comment by StefH** [comment]
The reason I've created an own simple logging class in WireMock, is that I cannot use Microsoft.Extensions.Logging.Abstractions because I'm still supporting older frameworks like 4.5.2 & 4.6

I need to think on this....

**Comment by wolf8196** [comment]
@StefH 
Just checked that version. All looks good to me. Thank you

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/845
