### ISSUE TITLE
Exception ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by arihantjain0894** [WireMock-Net/WireMock.Net#846]
Hi, I am getting the following exception:
```
System.ArgumentOutOfRangeException
Message: Index was out of range. Must be non-negative and less than the size of the collection.
InnerException: null 
StackTraceString: at System.Collections.Generic.List`1.get_Item(Int32 index)
at System.Collections.ObjectModel.ObservableCollection`1.RemoveItem(Int32 index)
at WireMock.Owin.WireMockMiddleware.LogRequest(LogEntry entry, Boolean addRequest)
at WireMock.Owin.WireMockMiddleware.InvokeInternalAsync(HttpContext ctx)
at WireMock.Owin.GlobalExceptionMiddleware.InvokeInternalAsync(HttpContext ctx)
```
Settings:
"MaxRequestLogCount": 0
"CustomDelay": 5000 ms

Version: 1.5.3

Usage: System stress testing.

When i increase the MaxRequestLogCount to let say 20, this is less frequent.
Also making custom delay to 0 fixes this.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/848

**Comment by StefH** [comment]
can you try preview version "1.5.10-ci-16658" ?

(https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions)

**Comment by arihantjain0894** [comment]
{
	"Status": "{\"ClassName\":\"System.ArgumentOutOfRangeException\",\"Message\":\"Index must be within the bounds of the List.\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at System.Collections.Generic.List`1.Insert(Int32 index, T item)\\r\\n   at System.Collections.ObjectModel.Collection`1.InsertItem(Int32 index, T item)\\r\\n   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)\\r\\n   at WireMock.Util.ConcurrentObservableCollection`1.InsertItem(Int32 index, T item)\\r\\n   at WireMock.Owin.WireMockMiddleware.LogRequest(LogEntry entry, Boolean addRequest)\\r\\n   at WireMock.Owin.WireMockMiddleware.InvokeInternalAsync(HttpContext ctx)\\r\\n   at WireMock.Owin.GlobalExceptionMiddleware.InvokeInternalAsync(HttpContext ctx)\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2146233086,\"Source\":\"System.Private.CoreLib\",\"WatsonBuckets\":null,\"ParamName\":\"index\",\"ActualValue\":null}"
}

Maybe we need to add try-catch when adding log also.

**Comment by StefH** [comment]
New preview version:

`16663`

Can you try this?

**Comment by StefH** [comment]
Preview version `16667` does also have extra logic --> do not add an entry at all if the MaxRequestLogCount is set to 0.

@arihantjain0894 can you test this version?

**Comment by arihantjain0894** [comment]
Shouldn't we do the same(condition) when removing from the log also?

**Comment by StefH** [comment]
Ok.
I did add some extra checks

**Comment by StefH** [comment]
latest version is 16669

**Comment by arihantjain0894** [comment]
Worked fine.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/848

**Comment by StefH** [comment]
New official version will be released shortly.
