### ISSUE TITLE
How can I correctly find or ignore the ? character from a request url in the RegexMatcher used via postman, not coded.

### ISSUE THREAD

**Issue by lszlszl** [WireMock-Net/WireMock.Net#847]
Latest stable wiremock version was downloaded and configured. I send messages to them via postman.

 I configured a RegexMatcher, what is okay, if I do not send a ? in the url.

**steps**

1. define RegexMatcher  
      `"Pattern": "(\/some\/service\/v1\/name)([?]{1})(param.source=SYSTEM){1}([&]{1})(param.id=123457890){1}$"`
2. do POST or PUT and configure a request / response via postman.
3. check it with GET "__admin/mappings"
4. send GET request to wiremock via postman. 
      https://localhost/wiremock/some/service/v1/name?param.source=SYSTEM&param.id=123457890         
5. check response message

**expected result:** 
answer arrives correctly with defined response message

**actual result:**
exception : \"ClassName\":\"System.NullReferenceException\",\"Message\":\"Object reference not set to an instance of an object.\

Please be specific so we can provide the best answer possible:
if I not use ? in the link and change it to other character (e.g. "a-z" "0-9" + & $ ), then the same expression will work correctly

I tried ([?]{1}), ([\\?]{1}) (.*{1}) ((/u003F){1})
How can I define the part from de regexp correctly ([?]{1}) to find or ignore ?

**Comment by StefH** [comment]
@lszlszl 
Please provide the mappping json you send to wiremock.

**Comment by lszlszl** [comment]
{
	"Request": {
		"Path": {
			"Matchers": [
				{
					"Name": "RegexMatcher",
					"Pattern": "(\/some\/service\/v3\/name)([?]{1})(param.source=SYSTEM){1}([&]{1})(param.id=123457890){1}$"
				}
			]
		},
		"Methods": [
			"get"
		]
	},
	"Response": {
		"StatusCode": 200,
		"Body": "{\"msg\": \"Hello my world!\"}",
		"Headers": {
			"Content-Type": "application/json; charset=utf-8"
		}
	}
}

**Comment by StefH** [comment]
What I would suggest is:

:one: 
Use a RegexMatcher for only the **path** : `(\/some\/service\/v1\/name)`
 

:two:
Use a RegexMatcher/ExactMatcher or WildcardMatcher for the Query Parameters:

``` json
"Params": [
        {
          "Name": "param.source",
          "Matchers": [
            {
              "Name": "ExactMatcher",
              "Pattern": "SYSTEM"
            }
          ]
        }
      ]
```

**Comment by lszlszl** [comment]
{
     "Request": {
        "Path": {
            "Matchers": [
                {
                    "Name": "ExactMatcher",
                    "Pattern": "/some/service/v3/name",
                    "IgnoreCase": false
                }
            ]
        },
        "Params": [
            {
                "Name": "param.source",
                "Matchers": [
                    {
                        "Name": "ExactMatcher",
                        "Pattern": "SYSTEM"
                    }
                ]
            },
            {
                "Name": "param.id",
                "Matchers": [
                    {
                        "Name": "ExactMatcher",
                        "Pattern": "123457890"
                    }
                ]
            }
        ],
        "Methods": [
            "get"
        ]
    },
    "Response": {
        "StatusCode": "200",
        "Body": "{\"msg\":\"Hello my world!\"}",
        "Headers": {
            "Content-Type": "application/json;charset=utf-8"
        }
    }
}

**Comment by lszlszl** [comment]
okay, thank you! That"s working fine.
