### ISSUE TITLE
Building with .Net Framework 4.5.2

### ISSUE THREAD

**Issue by Netizine** [WireMock-Net/WireMock.Net#864]
### Describe the bug
.Net framework 4.5.2 has gone end of life. https://dotnet.microsoft.com/en-us/download/dotnet-framework/net452

### Expected behavior:
Upgrade to 4.6.2 which has support

**Comment by StefH** [comment]
Good point. However for now I'll keep the backwards versions. (Also .NET 5.0 is out of supported, and also netcore2.1)
