### ISSUE TITLE
Cannot use WireMockServerSettings instance with URL specified

### ISSUE THREAD

**Issue by williambowsher-omnio** [WireMock-Net/WireMock.Net#866]
I am trying to instantiate a WireMockServer using the WireMockServerSettings with a URL specified as below:

``` c#
var settings = new WireMockServerSettings
{
    Urls = new[] { "http://+:6010/statement-databridge/v1/" }
};
_server = WireMockServer.Start(settings);
```

But every time I inspect the _server object, it has what appear to be 2 default URLS configured at ports 5000 and 5001.
I am using WireMock.NET 1.5.13 

Could you provide any pointers about what I am doing wrong

**Comment by StefH** [comment]
@williambowsher-omnio 
You cannot provide the full url.

WireMockServer always runs at the _root_ - url.

Can you try:
``` c#
var settings = new WireMockServerSettings
{
    Urls = new[] { "http://+:6010" }
};
_server = WireMockServer.Start(settings);
```

**Comment by williambowsher-omnio** [comment]
Yep that worked, thanks for the fast response.
