### ISSUE TITLE
Can not unsubscribe from LogEntriesChanged event.

### ISSUE THREAD

**Issue by IamHF** [WireMock-Net/WireMock.Net#870]
### Describe the bug
Cannot unsubscribe from "LogEntriesChanged" event handler because a new delegate is created inside the add method of the event.

### Expected behavior:
You should be able to unsubscribe from "LogEntriesChanged" with the same event handler that is used to subscribe to the event.

### Test to reproduce
``

### Other related info
`public event NotifyCollectionChangedEventHandler LogEntriesChanged
    {
        add
        {
            _options.LogEntries.CollectionChanged += (sender, eventRecordArgs) =>
            {
                try
                {
                    value(sender, eventRecordArgs);
                }
                catch (Exception exception)
                {
                    _options.Logger.Error("Error calling the LogEntriesChanged event handler: {0}", exception.Message);
                }
            };
        }
        remove => _options.LogEntries.CollectionChanged -= value;
    }`
[https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Server/WireMockServer.LogEntries.cs](url)

**Comment by StefH** [comment]
@IamHF 
Can you try preview version: `1.5.13-ci-16909`

https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/issues/870

**Comment by StefH** [comment]
@IamHF Can you please test that preview version?

**Comment by StefH** [comment]
@IamHF 
Can you please verify if that preview NuGet fixes your problem?

**Comment by StefH** [comment]
Code merged
