### ISSUE TITLE
Partial proxy stub mapping

### ISSUE THREAD

**Issue by ThokerWD** [WireMock-Net/WireMock.Net#873]
Is it possible to define a proxy stub mapping similar to the following one ?

```json
{
    "request": {
        "method": "GET",
        "urlPattern": "/other/service/.*"
    },
    "response": {
        "proxyBaseUrl": "http://otherhost.com/approot"
    }
}
```

So that requests matching this template get proxied to "http://otherhost.com" and other responses get matched by my local logic ?

**Comment by StefH** [comment]
You need two mappings.

This example should work (in case your real host is named "realhost.com")

``` json
[
{
    "Request": {
      "Path": {
        "Matchers": [
          {
            "Name": "WildcardMatcher",
            "Pattern": "/other/service"
          }
        ]
      },
      "Methods": [
        "get"
      ]
    },
    "Response": {
      "ProxyUrl": "http://otherhost.com"
    }
},
{
    "Request": {
      "Path": {
        "Matchers": [
          {
            "Name": "WildcardMatcher",
            "Pattern": "/other/abc"
          }
        ]
      },
      "Methods": [
        "get"
      ]
    },
    "Response": {
      "ProxyUrl": "http://realhost.com"
    }
}
]
```

**Comment by ThokerWD** [comment]
Thanks for the quick reply @StefH . Unfortunately I can't make this work together with client certificate authentication for a https server.

When this is configured under `ProxyAndRecordSettings`, then the authentication works fine, but then all requests get proxied to the configured URL. 

Is there a possibility to configure a ClientCertificate together with a ProxyUrl ?

**Comment by StefH** [comment]
In your case, do not define a global proxy, but only in the mappings.

Like here:
https://github.com/WireMock-Net/WireMock.Net/wiki/Proxying#proxyintercept

**Comment by ThokerWD** [comment]
Thank you, this way I can also specify a certificate for this proxy. I think this is currently only supported in code and not in json though.

```
// Low priority catch-all proxies to otherhost.com by default
server
  .Given(
    Request.Create()
      .WithPath("/*")
  )
  .AtPriority(10)
  .RespondWith(
    Response.Create()
      .WithProxy("http://otherhost.com","thumbprint_or_subject") // this is what I needed
  );
```
