### ISSUE TITLE
Bug: Standalone server throws 500 error when receiving concurrent requests

### ISSUE THREAD

**Issue by FSatmar** [WireMock-Net/WireMock.Net#88]
Hi,
I'm trying to use the WireMock Net as a standalone service but when I run multiple tests in parallel which call the admin api to create or delete mappings, the server often fails with a 500 error code. Any chance to to have this fixed?

> The stacktrace:
> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
>    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
>    at System.Collections.Generic.List`1.Enumerator.MoveNext()
>    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
>    at WireMock.Server.FluentMockServer.RegisterMapping(Mapping mapping)
>    at WireMock.Server.RespondWithAProvider.RespondWith(IResponseProvider provider)
>    at WireMock.Server.FluentMockServer.DeserializeAndAddMapping(String json, Nullable`1 guid)
>    at WireMock.Server.FluentMockServer.MappingsPost(RequestMessage requestMessage)

**Comment by StefH** [comment]
I will take a look.

**Comment by StefH** [comment]
Can you please try version 1.0.3.2 ?

**Comment by FSatmar** [comment]
You are awesome! Thanks!

**Comment by StefH** [comment]
Ok. Nice to hear.
