### ISSUE TITLE
Can Wiremock listen on different URLs?

### ISSUE THREAD

**Issue by chrisw11112** [WireMock-Net/WireMock.Net#883]
Thanks for any help! I'm trying to start a wiremock server with a url of http://ls-localhost:8080 but am getting a timeout error. Is This a valid use case?

This is my code
```
var settings = new WireMockServerSettings();
settings.Urls = new string[] { "http://ls-localhost:8080" };
settings.ReadStaticMappings = true;

var server = WireMockServer.Start(settings);

server.ReadStaticMappingAndAddOrUpdate("Mock.json");
```

I have a very specific use case for this and it needs to have the prefix to work correctly.

Thanks!

**Comment by StefH** [comment]
I think this will only work if you define `ls-localhost` in the hostfile?

**Comment by chrisw11112** [comment]
Are you referring to the windows host file are is there something I'm missing?

**Comment by StefH** [comment]
Correct.

**Comment by chrisw11112** [comment]
Thanks for the super quick replies! Are there by any chance any plans to change that functionality and would you like me to close the thread?
