### ISSUE TITLE
Request Matching Wiki - include JSON example (specification) of each matching part available

### ISSUE THREAD

**Issue by MichaelIDS** [WireMock-Net/WireMock.Net#891]
At present on this section of the Wiki, there isn't a clear list of what the names of matching parts are and if they are single objects or arrays.
https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching#one-request-matching

Ideally, a table or a simple JSON example of each would be ideal, like there is for Query Parameters.
https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching#query-parameters

Most of the matching parts can be found somewhere on that page via a search under one of the Matchers, however, I couldn't find any example of the 'Url' matching part.
I found it was Matchers (multiple) via trial and error.
```json
"Url": {
    "Matchers": [
        {
            "Name": "RegexMatcher",
            "Pattern": "/clients[?]"
        }
    ]
}
```

Also, it seems that some matching part types can't be used together. I hit this when trying to use 'Url' and 'Path' together. After a GitHub search and looking at code results, I noticed this:
https://github.com/WireMock-Net/WireMock.Net/blob/b1032c9dcdb9acee3915ac7f92b7bffb1bd1cf7e/src/WireMock.Org.Abstractions/Request.cs#L11
So just moved the logic from my `Path` into the `Url` and combined them into a single Regex to trigger when any parameters are provided for a specific URL.

**Comment by StefH** [comment]
Wiki updated.

https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching
