### ISSUE TITLE
Can I include a modified datetime in the response via a JSON definition?  

### ISSUE THREAD

**Issue by MichaelIDS** [WireMock-Net/WireMock.Net#895]
I'm trying to add an hour to the current DateTime and include that new DateTime in the response.

I know I can get the current DateTime via
```{{DateTime.Now}}```

But I can't see how I can manipulate this.

I wondered about using Handlebars and splitting the string, then using an each and if's to manipulate it, but I can't seem to nest the response value of `{{DateTime.Now}}` into a handlebars expression.

Is nesting `{{}}` within each other across handlers not supported I take it, i.e. the inner customer handler for `{{DateTime}}` isn't completed and substituted before the result is passed to handlebars for the `{{each}}` to be processed by that library.

EDIT: I originally misunderstood what Humanizer DateTime did and initially thought it could help with adding an hour to the time. hence the title and content change.

**Comment by StefH** [comment]
This is not yet possible, I'm working on an update on the DynamicLinq Handlebars helper.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/893

**Comment by StefH** [comment]
@MichaelIDS 

If you use version `1.5.17-ci-17109`, you can now use DynamicLinq to manipulate e.g. DateTime or do other logic.

Example mapping json:
``` json
"BodyAsJson": {
  "DynamicLinq.Expression 'DateTime.Now.AddHours(1)'": "{{DynamicLinq.Expression 'DateTime.Now.AddHours(1)'}}",
  "Path.Lookup data request.PathSegments.[1] 'N/A'": "{{Path.Lookup data request.PathSegments.[1] 'N/A'}}",
  "Path.Lookup data request.PathSegments.[4] 'N/A'": "{{Path.Lookup data request.PathSegments.[4] 'N/A'}}",
  "Linq data 'it[\"1\"] ?? \"n/a\"'": "{{Linq data 'it[\"1\"] ?? \"n/a\"'}}",
  "Linq data 'it[\"9\"] ?? \"n/a\"'": "{{Linq data 'it[\"9\"] ?? \"n/a\"'}}",
  "DynamicLinq.Expression data 'it[\"1\"] ?? \"n/a\"'": "{{DynamicLinq.Expression data 'it[\"1\"] ?? \"n/a\"'}}",
  "DynamicLinq.Expression data 'it[\"9\"] ?? \"n/a\"'": "{{DynamicLinq.Expression data 'it[\"9\"] ?? \"n/a\"'}}"
},
```

And when calling the url: `http://localhost/data/1`

Results into response body:
``` json
{
    "DynamicLinq.Expression 'DateTime.Now.AddHours(1)'": "2023-03-01T19:10:04.2367715+01:00",
    "Path.Lookup data request.PathSegments.[1] 'N/A'": "one",
    "Path.Lookup data request.PathSegments.[4] 'N/A'": "N/A",
    "Linq data 'it[\"1\"] ?? \"n/a\"'": "one",
    "Linq data 'it[\"9\"] ?? \"n/a\"'": "n/a",
    "DynamicLinq.Expression data 'it[\"1\"] ?? \"n/a\"'": "one",
    "DynamicLinq.Expression data 'it[\"9\"] ?? \"n/a\"'": "n/a"
}
```

**Comment by StefH** [comment]
@MichaelIDS Did you have time to verify this?

**Comment by MichaelIDS** [comment]
Unfortunately, I am still waiting to get time allocated to development/testing of these new WireMock features.
We haven't reached the point when we specifically need to do this, I was just looking ahead when I asked the question :)

**Comment by MichaelIDS** [comment]
I know it's very late, but yes. the date modification works nicely, thanks. 👍
