### ISSUE TITLE
Is it possible to access custom headers inside callback?

### ISSUE THREAD

**Issue by jamiemcl** [WireMock-Net/WireMock.Net#898]
Hi,

I have a scenario where I need to match based on a specific header, and then retrieve the value of this header inside the WithCallback method. I can get this mock to match, however, when I try to access the value from request message headers, the header does not exist and I therefore cannot retrieve the value.

``` c#
.Given(Request.Create()
                    .WithPath("/random-path")
                    .WithHeader("x-test-id", "*")
                    .UsingGet()
                )
                .RespondWith(Response.Create()
                    .WithCallback(requestMessage =>
                    {
                        // ALWAYS RETURNS FALSE
                        if (requestMessage.Headers is not null && requestMessage.Headers.TryGetValue("x-test-id", out var testId))
```

Is there anything I can do to retrieve the value of the x-test-id header here?

**Comment by StefH** [comment]
Are you sure the request you send to WireMock.Net contains the `x-test-id` header?

**Comment by jamiemcl** [comment]
Thanks so much for the rapid reply! 

Yes, I am sure that the Header is being passed to the request. As I mentioned, the issue isn’t with the match as the callback does get run with the above setup, but there are only 4 headers present on the requestMessage - none of which are my custom header but instead include Host and 3 others. 

Any further thoughts?

**Comment by StefH** [comment]
With this C# code:
``` c#
server
    .Given(Request.Create().WithPath("/random200or505").UsingGet())
    .RespondWith(Response.Create().WithCallback(request =>
    {
        int code = new Random().Next(1, 2) == 1 ? 505 : 200;
        return new ResponseMessage
        {
            BodyData = new BodyData
            {
                BodyAsString = "random200or505:" + code + ", HeadersFromRequest = " + string.Join(",", request.Headers),
                DetectedBodyType = Types.BodyType.String,
            },
            StatusCode = code
        };
    }));
```

And sending a GET to /random200or505

I get all headers back:
![image](https://user-images.githubusercontent.com/249938/221956890-0ff7200b-c074-42ce-b8d3-8f58241e7468.png)

**Comment by jamiemcl** [comment]
You are right, this is my mistake. I was adding the header to the initial request, which then subsequently made a second request inside of it. Sorry to waste your time, and thanks again for the prompt replies
