### ISSUE TITLE
Ignore OPTIONS request when using proxyandrecord

### ISSUE THREAD

**Issue by bhargavjulaganti** [WireMock-Net/WireMock.Net#899]
I am using wire mock as a standalone server, to record my web requests. Currently it is recording OPTIONS request as well when saving the mapping to the file .

Is there an extension I could use, so it does not save OPTIONS request, like how we are excluding specific headers not to save in mappings file

```cs
var url = "http://localhost:9095";

Console.WriteLine($"WireMock Recording on {url}");

var settings = new WireMockServerSettings
{
    Urls = new[] { url },
    StartAdminInterface = true,
    ProxyAndRecordSettings = new ProxyAndRecordSettings
    {
        Url = "random url",
        SaveMapping = true,
        SaveMappingToFile = true,
        SaveMappingForStatusCodePattern = "2xx,4xx",
        ExcludedHeaders = new[]
        {
            "Postman-Token",
            "Host",
            "Authorization",
            "User-Agent",
            "Cache-Control"
        }
    }
};

var server = WireMockServer.Start(settings);
```

**Comment by StefH** [comment]
@bhargavjulaganti 
This can be added.

I'll take a look.

**Comment by StefH** [comment]
Can you try preview version (1.5.17-ci-17145) ?

https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by bhargavjulaganti** [comment]
I updated the version to `1.5.17-ci-17145` and tried it. I am still seeing OPTIONS file is getting created


![image](https://user-images.githubusercontent.com/11901773/223725408-7a9a6688-4dc9-49e5-8264-bc42e914dfcb.png)

![image](https://user-images.githubusercontent.com/11901773/223725489-c2764338-cb12-48fb-b480-5a2af175cb81.png)

**Comment by StefH** [comment]
Please try 17147

**Comment by bhargavjulaganti** [comment]
still seeing the same issue. When I look at your [change](https://github.com/WireMock-Net/WireMock.Net/blob/7312688eea4ae2eabf0f0c1465b7358fcf817126/src/WireMock.Net/Serialization/ProxyMappingConverter.cs#L48) , I see you are looking for request matchers.

I do not have any request matchers in my code. I am just running wiremock as a standalone application

**Comment by StefH** [comment]
You are correct.

Actually a new setting like DoNotSaveMappingForHttpMethods should be added. Just like SaveMappingForStatusCodePattern.

**Comment by StefH** [comment]
@bhargavjulaganti 
New code works like:
``` c#
ProxyAndRecordSettings = new ProxyAndRecordSettings
            {
                Url = "http://www.google.com",
                SaveMapping = true,
                SaveMappingToFile = true,
                SaveMappingSettings = new ProxySaveMappingSettings
                {
                    StatusCodePattern = "2xx,4xx",
                    HttpMethods = new ProxySaveMappingSetting<string[]>(new string[] { "GET" }, MatchBehaviour.RejectOnMatch) // To make sure that we don't want this mapping
                }
            },
```

(new preview NuGet will be published within some minutes, just take the most recent version)

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/900

**Comment by StefH** [comment]
An official NuGet will be released in the next days.
