### ISSUE TITLE
SavePact() does not export actual interactions

### ISSUE THREAD

**Issue by codegolem** [WireMock-Net/WireMock.Net#902]
SavePact() does not save the actual interactions, but only the configured stubs.

I would have expected to see all entries from the LogEntries, with actual headers and body content, to be exported as interactions in the pact file.

Is this by design? Is it a missing feature?

**Comment by StefH** [comment]
As far I know / understood is pact used to test the contract.
So only the mappings are converted to Pact. Not all calls made to the service.
