### ISSUE TITLE
How to handle encrypted payload in requests and responses?

### ISSUE THREAD

**Issue by jsyrjala** [WireMock-Net/WireMock.Net#909]
I have message format where requests and responses have a JSON body where one of the elements contains 
an another JSON element as encrypted.

Both the request and response look essentially like this. All the interesting stuff is inside the `encryptedField`. 
```json
{
  "header":{"headerField":  "headerValue"},
  "encryptedField": "base64_encoded_encrypted_json_blob"
}
```

I'd like to decrypt the request,  then generate a response based on the decrypted request. And finally I should encrypt the response again before sending it to the client.

I know how to decrypt/encrypt the data but how to plug that into WireMock.Net?

I was hoping that there would be possibility to have functions that convert request bodies at the start of the flow and then convert response bodies at the end of the flow.

**Comment by jsyrjala** [comment]
After some digging, it seems that at least it is possible to implement IResponseProvider, and use that to handle the request and response as you want. However this, makes using for example WireMock's template functionality hard or impossible.

```csharp
server.Given(Request.Create().WithPath("/nexo/").UsingPost()).RespondWith(new MyResponse());

private class MyResponse : IResponseProvider
    {
        public async Task<(IResponseMessage Message, IMapping? Mapping)> ProvideResponseAsync(
            IMapping mapping,
            IRequestMessage requestMessage,
            WireMockServerSettings settings
        )
        {
            Console.WriteLine(requestMessage.BodyAsJson);
            var msg = new ResponseMessage()
            {
                StatusCode = 200,
                FaultType = FaultType.NONE,
                BodyData = new BodyData
                {
                    BodyAsString = "can_have_any_data_here",
                    DetectedBodyType = BodyType.String,
                },
            };
            return (msg, mapping);
        }
    }

```

**Comment by StefH** [comment]
However, if you want to use HandleBars.Net templating, you can use the base64decode Helper, see
https://github.com/Handlebars-Net/Handlebars.Net.Helpers/wiki/String#stringbase64decode


Or you can register you own specific Handlebars.Net.Helper:
Register this with the HandlebarsRegistrationCallback in the settings class.

**Comment by StefH** [comment]
@jsyrjala

**Comment by jsyrjala** [comment]
Thanks. It is working now.
