### ISSUE TITLE
Feature: adding excluded params to proxy and records settings

### ISSUE THREAD

**Issue by walidhaidarii** [WireMock-Net/WireMock.Net#912]
**Is your feature request related to a problem? Please describe.**
I have an issue when saving mapped JSON files from requests that have a timestamp as a query param, which will be different on every request, causing the matching to always call the proxy API and fail to locate the JSON file as expected.

**Describe the solution you'd like**
To add the property [ExcludedParams]  to the class [ProxyAndRecordSettings] so we can add those params to be excluded from saving into the JSON

**Describe alternatives you've considered**
no alternative as far as I know.

**Is your feature request supported by [WireMock (java version)](https://www.wiremock.org)? Please provide details.**
no idea as far as I know.

**Comment by StefH** [comment]
Did you try editing the saved proxy mapping file to allow a `*` for that specific Query param?

**Comment by walidhaidarii** [comment]
> Did you try editing the saved proxy mapping file to allow a `*` for that specific Query param?

But we delete all the files after every deployment to start with fresh data, not to say that the request having such param are so many
