### ISSUE TITLE
How to save the mapping as a json file when using admin api ?

### ISSUE THREAD

**Issue by bhargavjulaganti** [WireMock-Net/WireMock.Net#920]
I am usibg this example [project](https://github.com/WireMock-Net/WireMock.Net/tree/f3d52adbb2053ad5fb17fb10c31da698ff68f36e/examples/WireMock.Net.WebApplication.NETCore3)  for running wiremock 

When we use this POST admin endpoint (__admin/mappings) , I don't see the mapping not saved anywhere in the local disk. Is there a way we can enable to save the json file

**Comment by StefH** [comment]
When you post new mappings to `__admin/mappings` via the admin endpoint, these new / updated mappings are only saved in memory.

If you want to save these to disk, do post to `__admin/mappings/save`.
Save all persistent stub mappings to the disk. (by default this is \bin\{x}\__admin\mappings_. Where {x} is the platform + build configuration)
