### ISSUE TITLE
PortUtils class made internal

### ISSUE THREAD

**Issue by antoniovalentini** [WireMock-Net/WireMock.Net#921]
Hello, I noticed that with `v1.5.22` the `PortUtils` class has been [marked as internal](https://github.com/WireMock-Net/WireMock.Net/commit/651486f718f6c2e1a53d67f692f18192ec2bf487#diff-1eca73db0b0f849524e77b51fa0564ad052eba14c50e40013dbeafb493026917R12), but I don't see any reference in the [CHANGELOG](./CHANGELOG.md).

1. Should it be treated as a breaking change?
2. Is there any equivalent alternative we can use?

Thanks for your amazing work!

Antonio

**Comment by StefH** [comment]
@antoniovalentini 
There was no specific reason for this, else then keeping as much as possible internal.

Do you need it?

**Comment by antoniovalentini** [comment]
> Do you need it?

No worries. The implementation is rather short and can implement directly. I just wanted to make sure I wasn't missing an alternative way.

Thanks again!

**Comment by StefH** [comment]
I can make it public again.

There is also another PR related to that 

I'll take a look

**Comment by StefH** [comment]
In the next version this will be public again.

**Comment by antoniovalentini** [comment]
Wow! Thanks a lot 🙇
