### ISSUE TITLE
Match route parameters to types

### ISSUE THREAD

**Issue by Twinki14** [WireMock-Net/WireMock.Net#929]
Given I have a path like `/site/<guid>/org`, is there an easier syntax I could use instead of a regex/wild card? like `/site/{{guid}}/org` or `/site/{{long}}/org`, it'll match the route based on the type

**Comment by StefH** [comment]
@Twinki14 
The easiest way to achieve this is use a regular expression.

- guid = `^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$`
- long = `^[0-9]{1,19}$`

**Comment by StefH** [comment]
@Twinki14 
I'm closing this question for now.
