### ISSUE TITLE
Bug: FluentMockServer IsStarted after calling Start()

### ISSUE THREAD

**Issue by alexangas** [WireMock-Net/WireMock.Net#93]
Hello,

I'm calling `FluentMockServer.Start()` and then check the `IsStarted` property to find which port it has bound to.

However what I'm finding is, even after sleeping the thread for 5 seconds, that `IsStarted` is still false. I'm expecting that calling `Start()` will start the server and then set `IsStarted = true`.

It looks like the port is allocated anyway so I guess I don't need to wait for this flag, but thought I would still log this. I'm using version 1.0.2.13.

Thanks!

**Comment by StefH** [comment]
This should work actually, I'll double check the code and unit-tests.

**Comment by StefH** [comment]
Are you using net 452 or .net core 1.x / 2.x ?

**Comment by alexangas** [comment]
This is under .NET Core 2.x

**Comment by StefH** [comment]
Solved.
