### ISSUE TITLE
How to access the request's body params comming from PostMan body ?

### ISSUE THREAD

**Issue by pouyaSobhanipour** [WireMock-Net/WireMock.Net#936]
Hello . 

The complete question is : 
How to access the request's body params comming from PostMan? and put them inside the responce using templates 
{{ }} ?

**The request body should be this  :** 
```
 {
     "requestCode" :"ABC" ,
     "company":"XXX",
    "Code": "null",
     "vat" : "XX",
    "taxCode": "null",
    "province": "XX",
     "country": "XX"
 }
```
 * the params can be inside the post URL as well 
 **the response should be as :** 
` { result = "OK", description = "Request accepted", requestCode = "{{ request.bodyAsJson.requestCode}}" }`

which thi case should be 
` { result = "OK", description = "Request accepted", requestCode = "ABC" }`
****

**Comment by StefH** [comment]
Your code should work: ` { result = "OK", description = "Request accepted", requestCode = "{{ request.bodyAsJson.requestCode}}" }`

For more info see:
- https://github.com/WireMock-Net/WireMock.Net/wiki/Response-Templating
