### ISSUE TITLE
RequestMessage.GetParameter method missing from IRequestMessage interface

### ISSUE THREAD

**Issue by ShortIsLong** [WireMock-Net/WireMock.Net#941]
The RequestMessage.GetParameter method seems to be missing from the IRequestMessage interface. Wasn't sure if this is intentional or an oversight? Thanks.

https://github.com/WireMock-Net/WireMock.Net/blob/3956cd703b0343686b1e6981aca24b027bfe8545/src/WireMock.Net/RequestMessage.cs#L189

https://github.com/WireMock-Net/WireMock.Net/blob/3956cd703b0343686b1e6981aca24b027bfe8545/src/WireMock.Net.Abstractions/IRequestMessage.cs#L14

**Comment by StefH** [comment]
@ShortIsLong 
I think that for now this method is only used internally.

Do you need it ?

**Comment by ShortIsLong** [comment]
Our codebase is making use of the method to pull query values from the request and then build a response based the provided values. We can cast for now to RequestMessage and call the method that way (although it feels a bit unnecessary maybe?) but if the intent is to eventually make this internal then we'd have to roll our own version which would essentially be the same method. Is there some other mechanism we should be using to build a response based on the request param values rather than using GetParameter() inside the Response.WithBody() method? Apologies if this has been covered elsewhere.

**Comment by StefH** [comment]
Thanks for your explanation.

If you really need it, I'll add this method to the interface.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/942

**Comment by ShortIsLong** [comment]
Thanks for the quick turnaround! Much appreciated.
