### ISSUE TITLE
How to use environment variable

### ISSUE THREAD

**Issue by marspox** [WireMock-Net/WireMock.Net#953]
Hi there,
I have created Azure Web App Container
I have added the environment variable WIREMOCKSERVERSETTINGS__ALLOWPARTIALMAPPING then after restarting the app and getting the settings by calling /__admin/settings AllowPartialMapping was still false.
How the environment variable should look to set proxy URL etc?

![image](https://github.com/WireMock-Net/WireMock.Net-docker/assets/7716006/90af56f2-f3a0-45ab-a521-7b5163841b59)

![image](https://github.com/WireMock-Net/WireMock.Net-docker/assets/7716006/611277e0-7522-431b-9f02-fbe4ed8bbd13)

**Comment by StefH** [comment]
@marspox 

A preview version is available: 1.5.28-ci-17500



https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by StefH** [comment]
Will be included in next Docker release.
