### ISSUE TITLE
How to use brackets '[ ]' in Random String List HandleBar ?

### ISSUE THREAD

**Issue by pouyaSobhanipour** [WireMock-Net/WireMock.Net#956]
Hello 

i want to use `"{{Random Type=\"StringList\" Values=[\"a\", \"b\", \"c\"]}}"` to receive a random response from mock server each time i do a request. 

instead of a,b or c i want to use the following string : `"{\'errors\':[{\'detail\':\'Conditions must be seen\'}]}"`

it seems that when we have closed [] or {} wiremock does not responde . 
how should i by pass this issue ? 

Thanks

**Comment by StefH** [comment]
This is probably possible, however I do not know the answer.

Best is to take a approach where you use a switch statement.

See
https://stackoverflow.com/a/53398537/255966
