### ISSUE TITLE
[FluentAssertions] Should().HaveReceivedACall().WithHeader() only checks the first header with the matching key.

### ISSUE THREAD

**Issue by tlevesque-ueat** [WireMock-Net/WireMock.Net#958]
### Describe the bug
I have a scenario where I send 2 different requests to wiremock.
One has the header `Authorization: Bearer invalidToken`
The other has the header `Authorization: Bearer validToken`
I'm trying to assert that I received a request with each of these headers:

```csharp
_server.Should().HaveReceivedACall().WithHeader("Authorization", "Bearer invalidToken");
_server.Should().HaveReceivedACall().WithHeader("Authorization", "Bearer validToken");
```

However, the second assertion fails, because `WithHeader()` only checks the first `Authorization` header of all received requests.

### Expected behavior:

Both these assertions should succeed. `WithHeader` should check the headers of all requests, not just the first.

### Test to reproduce
```csharp
using var server  = WireMockServer.Start();
using var client = server.CreateClient();
await client.SendAsync(new HttpRequestMessage(HttpMethod.Get, "/")
{
    Headers =
    {
        Authorization = new AuthenticationHeaderValue("Bearer", "invalidToken")
    }
});
await client.SendAsync(new HttpRequestMessage(HttpMethod.Get, "/")
{
    Headers =
    {
        Authorization = new AuthenticationHeaderValue("Bearer", "validToken")
    }
});

server.Should().HaveReceivedACall().WithHeader("Authorization", "Bearer invalidToken");
server.Should().HaveReceivedACall().WithHeader("Authorization", "Bearer validToken");
```
### Other related info
Provide additional information if any.

**Comment by StefH** [comment]
Thanks for this detailed issue.

A fix will be released in the next version.


https://github.com/WireMock-Net/WireMock.Net/pull/959

**Comment by tlevesque-ueat** [comment]
Wow, that was fast! Thanks
