### ISSUE TITLE
JsonPathMatcher does not match json body nested objects

### ISSUE THREAD

**Issue by timurnes** [WireMock-Net/WireMock.Net#965]
### Describe the bug
JsonPathMatcher example in [official documentation](https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching-JsonPathMatcher) does not match json body with nested fields:
Pattern: `$.things[?(@.name == 'RequiredThing')]`
Json: `{ "things": { "name": "RequiredThing" } }`

First-level fields match works correctly

### Expected behavior:
JsonPathMatcher correctly matches json body with nested fields

### Test to reproduce
```
[Fact]
public void JsonPathMatcher_IsMatch_JsonStringWithNestedObjects()
{
	// Assign
	var json = "{ \"things\": { \"name\": \"RequiredThing\" } }";
	var matcher = new JsonPathMatcher("$.things[?(@.name == 'RequiredThing')]");

	// Act 
	double match = matcher.IsMatch(json);

	// Assert 
	Check.That(match).IsEqualTo(1);
}

The checked value is different from the expected one.
The checked value:
	[0]
The expected value:
	[1]
```

### Other related info
The same pattern works correctly with another json from example: 
`{ "things": [ { "name": "RequiredThing" }, { "name": "Wiremock" } ] }`

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/966

**Comment by StefH** [comment]
@timurnes 
You can check version 
`1.5.31-ci-17598`

https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by timurnes** [comment]
@StefH 
Thanks, 1.5.31-ci-17598 works correctly. Waiting for release package version :)

**Comment by StefH** [comment]
@timurnes 
You are correct. My fix is just a workaround for the first level.
To make it work for all levels, I need to call the code recursive. I'll check this.

BTW you know that you also can use a https://github.com/WireMock-Net/WireMock.Net/wiki/Request-Matching#dynamic-linq-linqmatcher

Which is much easier to use:
```
"things.nested.name == \"RequiredThing\""
```

**Comment by timurnes** [comment]
@StefH 
Sure, I used JsonPartialMatcher when I discovered that JsonPathMatcher does not work correctly - it looks better for my case

**Comment by StefH** [comment]
@timurnes 
Making the fix recursive is not that easy, so for now I'll merge this PR as-is.
