### ISSUE TITLE
Fluent Assertion Body 

### ISSUE THREAD

**Issue by chrisjainsley** [WireMock-Net/WireMock.Net#975]
Can the fluent assertion library be used to check the request body sent to Wiremock? Would you like me to write my own assertion using log entries?

**Comment by StefH** [comment]
@chrisjainsley 
Currently the project https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net.FluentAssertions does support these assertions:
![image](https://github.com/WireMock-Net/WireMock.Net/assets/249938/da1e4229-466a-48f2-925c-b390915c4417)


Body is not yet included.

You can make a PR for that.

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1014

**Comment by StefH** [comment]
@chrisjainsley 

You can try preview : 1.5.39-ci-17877

https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1014

**Comment by StefH** [comment]
@chrisjainsley 
This new functionality will be available in the next release which will be delivered this week.
