### ISSUE TITLE
IBodyResponseBuilder.WithBody* should receive the request as a parameter

### ISSUE THREAD

**Issue by davidshen84** [WireMock-Net/WireMock.Net#98]
Currently, the `IBodyResponseBuilder.WithBody*` methods only allow return fixed response. If we can get the request object as a parameter, it would allow it respond dynamic response.

**Comment by StefH** [comment]
Is this issue linked to your question?
https://github.com/WireMock-Net/WireMock.Net/issues/66

**Comment by davidshen84** [comment]
Yes, I think it would serve the same purpose.

**Comment by StefH** [comment]
Code added, new NuGet will be uploaded.
