### ISSUE TITLE
Why WireMock.Net.Testcontainers doesn't use official docker image?

### ISSUE THREAD

**Issue by iikuzmychov** [WireMock-Net/WireMock.Net#980]
As I see, [WireMock.Net.Testcontainers](https://github.com/WireMock-Net/WireMock.Net/wiki/Using-WireMock.Net.Testcontainers) uses non-official images (`sheyenrath/wiremock.net` & `sheyenrath/wiremock.net-windows`). 

![image](https://github.com/WireMock-Net/WireMock.Net/assets/37931581/32324588-633f-494f-a34b-61951f15937d)

What is the reason? Why we don't use `wiremock/wiremock` instead?

**Comment by StefH** [comment]
These are official ;-)

These images my images which I release for this WireMock.Net project. (it's .NET not Java)
(https://github.com/WireMock-Net/WireMock.Net-docker)

For `wiremock/wiremock` I think a C# .NET TestContainer will also be available in the future.

**Comment by iikuzmychov** [comment]
Okay, thank you for the response.

I have one more related question. I can't understand how the next is possible.

I see this request matcher in `/__admin/mappings`:

![image](https://github.com/WireMock-Net/WireMock.Net/assets/37931581/56c2f145-787e-41af-bf5a-ceafd0a203c7)

which was loaded from this .json file:
```
{
  "id" : "f14d4844-a3e0-4130-a830-03f71a7cdbe8",
  "name" : "managetoken_gettoken",
  "request" : {
    "url" : "/manageToken/getToken?Key=VETFUecmFcPIeW65HZecew6D2aka&Secret=rc6vEixBUf70fFsCFJfOvffrKDQa",
    "method" : "GET"
  },
  "response" : {
    "status" : 200,
    "body" : "{\"access_token\":\"62403ff8-46a7-3f03-b971-03c281259c42\",\"scope\":\"device_383334.0\",\"token_type\":\"Bearer\",\"expires_in\":3600}",
    "headers" : {
      "X-Frame-Options" : "DENY",
      "activityid" : "782ee60c-a48c-4d64-b9b3-8f99649df207",
      "Access-Control-Expose-Headers" : "",
      "Cache-Control" : "no-store",
      "Access-Control-Allow-Origin" : "*",
      "Access-Control-Allow-Methods" : "GET",
      "uber-trace-id" : "df44af849f44bab6%3Acccf9a31b54cfa0d%3A2d2865c70c60927b%3A1",
      "X-Content-Type-Options" : "nosniff",
      "Pragma" : "no-cache",
      "X-XSS-Protection" : "1; mode=block",
      "Access-Control-Allow-Headers" : "content-type",
      "Content-Type" : "application/json",
      "Date" : "Fri, 21 Jul 2023 15:08:55 GMT"
    }
  },
  "uuid" : "f14d4844-a3e0-4130-a830-03f71a7cdbe8",
  "persistent" : true,
  "insertionIndex" : 1
}
```

And this is correct, as I understand. But when I try call the URI (`/manageToken/getToken?Key=VETFUecmFcPIeW65HZecew6D2aka&Secret=rc6vEixBUf70fFsCFJfOvffrKDQa`), I got 404:

![image](https://github.com/WireMock-Net/WireMock.Net/assets/37931581/6499780c-e126-4959-9210-76c6d090b03e)

I'm using [WireMock.Net.Testcontainers](https://github.com/WireMock-Net/WireMock.Net/wiki/Using-WireMock.Net.Testcontainers) with static mounting. This is the container logs:

![image](https://github.com/WireMock-Net/WireMock.Net/assets/37931581/e1129fd4-111d-49db-a165-8492c5796be6)

**Comment by StefH** [comment]
@iikuzmychov 
Your mapping files are wiremock.org mapping files, which cannot be used in this project.

See- https://github.com/WireMock-Net/WireMock.Net/issues/979
