### ISSUE TITLE
Support returning 404 when file referenced by BodyAsFile isn't found

### ISSUE THREAD

**Issue by goldsam** [WireMock-Net/WireMock.Net#985]
**Is your feature request related to a problem? Please describe.**

Currently, a 500 error status is returned for a stub which uses `BodyAsFile` to reference a non-existent file.
it would be useful to specify a 404 status could be returned instead when this occurs.

**Describe the solution you'd like**

The easiest solution would be to add a flag to prevent the mock from faulting and return a 500 and instead let additional mocks be evaluated. Then, a 404 fallback stub could be specified which a priority that evaluates after the stub using `BodyAsFile`.

**Describe alternatives you've considered**

Additional additional fields to support an "error" case seems unnecessary and complicated and breaks the existing paradigm.

**Is your feature request supported by [WireMock (java version)](https://www.wiremock.org)? Please provide details.**

Don't know.

**Additional context**

n/a

**Comment by StefH** [comment]
Currently the response is indeed like this:
**http status 500**

``` JSON
{
    "Status": "Could not find file 'c:\\error.xml'."
}
```

---

> The easiest solution would be to add a flag to prevent the mock from faulting and return a 500 and instead let additional mocks be evaluated. Then, a 404 fallback stub could be specified which a priority that evaluates after the stub using BodyAsFile.

In that case a proposal could be like:
``` json
{
    "Guid": "fd8ca21b-db82-48bc-ae5a-fc2153c2b0db",
    "Request": {
        "Path": {
            "Matchers": [
                {
                    "Name": "WildcardMatcher",
                    "Pattern": "/bodyasfile_transform123"
                }
            ]
        },
        "Methods": [
            "get"
        ]
    },
    "Response": {
        "StatusCode": 200,
        "Headers": { "Content-Type": "application/xml" },
        "BodyAsFile": "c:\\error.xml",
        "BodyAsFileIsCached": true,
    	"UseTransformer": true,
    	"UseTransformerForBodyAsFile": true
    },
    "ResponseWhenException": {
     "StatusCode": 404
    }
}
```

What are your thoughts?

**Comment by goldsam** [comment]
That works for me, but I do think it might be adding more complexity than is necessary. You could also just add an `IgnoreException` flag instead and continue to the next stub when an exception occurs.

**Comment by StefH** [comment]
In this case:

The mapping is invalid (e.g. due to invalid referenced file), which results that the output mapping cannot be constructed. In that case 500 is returned.

Also for example in XPathMatcher, I've change the code so that:
- in case the input cannot be matched, the mapping is skipped (this is same as before)
- in case the pattern (defined in the mapping) is invalid, the exception is logged, and the mapping gets a score = 0, which means that it's skipped.
